// GENERATED BY NAPL from schemas_map.napl — edit the prompt, not this file

use schemas_ordered_map::OrderedMap;
use serde::{Deserialize, Serialize};

fn default_version() -> u32 {
    2
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PromptTargetRecord {
    #[serde(rename = "promptHashAtGen", default, skip_serializing_if = "Option::is_none")]
    pub prompt_hash_at_gen: Option<String>,
    #[serde(default)]
    pub files: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unattributed: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PromptRecord {
    pub module: String,
    #[serde(rename = "promptHash")]
    pub prompt_hash: String,
    #[serde(rename = "declaredTargets", default)]
    pub declared_targets: Vec<String>,
    #[serde(default)]
    pub targets: OrderedMap<PromptTargetRecord>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FileRecord {
    pub target: String,
    pub hash: String,
    #[serde(default)]
    pub prompts: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NaplMap {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub prompts: OrderedMap<PromptRecord>,
    #[serde(default)]
    pub files: OrderedMap<FileRecord>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModuleFile {
    pub target: String,
    pub file_path: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileInput {
    pub file_path: String,
    pub hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttributionInput {
    pub rel: String,
    pub module: String,
    pub prompt_hash: String,
    pub target: String,
    pub declared_targets: Vec<String>,
    pub files: Vec<FileInput>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnattributedInput {
    pub rel: String,
    pub module: String,
    pub prompt_hash: String,
    pub target: String,
    pub declared_targets: Vec<String>,
    pub files: Vec<String>,
}

pub fn empty_map() -> NaplMap {
    NaplMap {
        version: 2,
        prompts: OrderedMap::new(),
        files: OrderedMap::new(),
    }
}

pub fn parse_map(raw: &str) -> Result<NaplMap, String> {
    let map: NaplMap = serde_json::from_str(raw).map_err(|e| e.to_string())?;
    if map.version != 2 {
        return Err("unsupported map version".to_string());
    }
    Ok(map)
}

pub fn map_to_json(map: &NaplMap) -> String {
    let mut json = serde_json::to_string_pretty(map).expect("NaplMap always serializes");
    json.push('\n');
    json
}

pub fn prompts_for_module(map: &NaplMap, module: &str) -> Vec<String> {
    map.prompts
        .iter()
        .filter(|(_, record)| record.module == module)
        .map(|(rel, _)| rel.clone())
        .collect()
}

pub fn has_module(map: &NaplMap, module: &str) -> bool {
    map.prompts.iter().any(|(_, record)| record.module == module)
}

pub fn declared_targets_for_module(map: &NaplMap, module: &str) -> Vec<String> {
    let mut seen = Vec::new();
    for (_, record) in map.prompts.iter() {
        if record.module != module {
            continue;
        }
        for target in &record.declared_targets {
            if !seen.contains(target) {
                seen.push(target.clone());
            }
        }
    }
    seen
}

pub fn files_for_module(map: &NaplMap, module: &str) -> Vec<ModuleFile> {
    let mut result: Vec<ModuleFile> = Vec::new();
    for (_, record) in map.prompts.iter() {
        if record.module != module {
            continue;
        }
        for (target, target_record) in record.targets.iter() {
            for file_path in &target_record.files {
                let already = result
                    .iter()
                    .any(|mf| &mf.target == target && &mf.file_path == file_path);
                if !already {
                    result.push(ModuleFile {
                        target: target.clone(),
                        file_path: file_path.clone(),
                    });
                }
            }
        }
    }
    result
}

pub fn is_prompt_gen_stale(
    record: Option<&PromptRecord>,
    target: &str,
    prompt_hash: &str,
    force: bool,
) -> bool {
    if force {
        return true;
    }
    let Some(record) = record else {
        return true;
    };
    let Some(target_record) = record.targets.get(target) else {
        return true;
    };
    if target_record.unattributed == Some(true) {
        return true;
    }
    match &target_record.prompt_hash_at_gen {
        Some(hash) => hash != prompt_hash,
        None => true,
    }
}

fn detach_file(map: &mut NaplMap, rel: &str, file_path: &str) {
    let Some(file_record) = map.files.get_mut(file_path) else {
        return;
    };
    file_record.prompts.retain(|p| p != rel);
    if file_record.prompts.is_empty() {
        map.files.remove(file_path);
    }
}

pub fn record_attribution(map: &mut NaplMap, input: &AttributionInput) {
    let mut targets = map
        .prompts
        .get(&input.rel)
        .map(|record| record.targets.clone())
        .unwrap_or_default();

    let prior_files: Vec<String> = targets
        .get(&input.target)
        .map(|target_record| target_record.files.clone())
        .unwrap_or_default();

    let new_file_paths: Vec<String> = input.files.iter().map(|f| f.file_path.clone()).collect();

    for prior_file in &prior_files {
        if !new_file_paths.contains(prior_file) {
            detach_file(map, &input.rel, prior_file);
        }
    }

    targets.insert(
        input.target.clone(),
        PromptTargetRecord {
            prompt_hash_at_gen: Some(input.prompt_hash.clone()),
            files: new_file_paths.clone(),
            unattributed: None,
        },
    );

    map.prompts.insert(
        input.rel.clone(),
        PromptRecord {
            module: input.module.clone(),
            prompt_hash: input.prompt_hash.clone(),
            declared_targets: input.declared_targets.clone(),
            targets,
        },
    );

    for file in &input.files {
        match map.files.get_mut(&file.file_path) {
            Some(existing) => {
                existing.target = input.target.clone();
                existing.hash = file.hash.clone();
                if !existing.prompts.iter().any(|p| p == &input.rel) {
                    existing.prompts.push(input.rel.clone());
                }
            }
            None => {
                map.files.insert(
                    file.file_path.clone(),
                    FileRecord {
                        target: input.target.clone(),
                        hash: file.hash.clone(),
                        prompts: vec![input.rel.clone()],
                    },
                );
            }
        }
    }
}

pub fn record_unattributed(map: &mut NaplMap, input: &UnattributedInput) {
    let mut targets = map
        .prompts
        .get(&input.rel)
        .map(|record| record.targets.clone())
        .unwrap_or_default();

    let prior_files: Vec<String> = targets
        .get(&input.target)
        .map(|target_record| target_record.files.clone())
        .unwrap_or_default();

    for prior_file in &prior_files {
        detach_file(map, &input.rel, prior_file);
    }

    targets.insert(
        input.target.clone(),
        PromptTargetRecord {
            prompt_hash_at_gen: None,
            files: input.files.clone(),
            unattributed: Some(true),
        },
    );

    map.prompts.insert(
        input.rel.clone(),
        PromptRecord {
            module: input.module.clone(),
            prompt_hash: input.prompt_hash.clone(),
            declared_targets: input.declared_targets.clone(),
            targets,
        },
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_map_has_version_2_and_no_entries() {
        let map = empty_map();
        assert_eq!(map.version, 2);
        assert!(map.prompts.is_empty());
        assert!(map.files.is_empty());
    }

    #[test]
    fn map_round_trips_through_json() {
        let mut map = empty_map();
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec!["rust".to_string()],
                files: vec![FileInput {
                    file_path: "src/a.rs".to_string(),
                    hash: "fh1".to_string(),
                }],
            },
        );

        let json = map_to_json(&map);
        assert!(json.ends_with('\n'));
        let reparsed = parse_map(&json).unwrap();
        assert_eq!(reparsed, map);
    }

    #[test]
    fn parse_map_rejects_unsupported_version() {
        let raw = r#"{"version": 3, "prompts": {}, "files": {}}"#;
        let err = parse_map(raw).unwrap_err();
        assert_eq!(err, "unsupported map version");
    }

    #[test]
    fn parse_map_rejects_corrupt_json() {
        let raw = "{not json";
        assert!(parse_map(raw).is_err());
    }

    #[test]
    fn parse_map_defaults_absent_fields() {
        let raw = r#"{"version": 2}"#;
        let map = parse_map(raw).unwrap();
        assert!(map.prompts.is_empty());
        assert!(map.files.is_empty());
    }

    #[test]
    fn prompt_target_record_omits_none_fields_in_json() {
        let record = PromptTargetRecord {
            prompt_hash_at_gen: None,
            files: vec!["a.rs".to_string()],
            unattributed: None,
        };
        let json = serde_json::to_string(&record).unwrap();
        assert_eq!(json, r#"{"files":["a.rs"]}"#);
    }

    #[test]
    fn prompts_for_module_returns_matching_keys_in_order() {
        let mut map = empty_map();
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m1".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![],
            },
        );
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "b.napl".to_string(),
                module: "m2".to_string(),
                prompt_hash: "h2".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![],
            },
        );
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "c.napl".to_string(),
                module: "m1".to_string(),
                prompt_hash: "h3".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![],
            },
        );

        assert_eq!(
            prompts_for_module(&map, "m1"),
            vec!["a.napl".to_string(), "c.napl".to_string()]
        );
        assert_eq!(has_module(&map, "m1"), true);
        assert_eq!(has_module(&map, "nope"), false);
    }

    #[test]
    fn declared_targets_for_module_deduplicates_in_first_seen_order() {
        let mut map = empty_map();
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec!["rust".to_string(), "ts".to_string()],
                files: vec![],
            },
        );
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "b.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h2".to_string(),
                target: "rust".to_string(),
                declared_targets: vec!["ts".to_string(), "go".to_string()],
                files: vec![],
            },
        );

        assert_eq!(
            declared_targets_for_module(&map, "m"),
            vec!["rust".to_string(), "ts".to_string(), "go".to_string()]
        );
    }

    #[test]
    fn files_for_module_dedupes_by_target_and_path() {
        let mut map = empty_map();
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![
                    FileInput { file_path: "src/a.rs".to_string(), hash: "f1".to_string() },
                    FileInput { file_path: "src/b.rs".to_string(), hash: "f2".to_string() },
                ],
            },
        );
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "b.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h2".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![FileInput { file_path: "src/a.rs".to_string(), hash: "f1".to_string() }],
            },
        );

        let files = files_for_module(&map, "m");
        assert_eq!(
            files,
            vec![
                ModuleFile { target: "rust".to_string(), file_path: "src/a.rs".to_string() },
                ModuleFile { target: "rust".to_string(), file_path: "src/b.rs".to_string() },
            ]
        );
    }

    #[test]
    fn is_prompt_gen_stale_covers_all_cases() {
        assert!(is_prompt_gen_stale(None, "rust", "h1", true));
        assert!(is_prompt_gen_stale(None, "rust", "h1", false));

        let mut targets = OrderedMap::new();
        targets.insert(
            "rust".to_string(),
            PromptTargetRecord {
                prompt_hash_at_gen: Some("h1".to_string()),
                files: vec!["a.rs".to_string()],
                unattributed: None,
            },
        );
        let record = PromptRecord {
            module: "m".to_string(),
            prompt_hash: "h1".to_string(),
            declared_targets: vec![],
            targets,
        };

        assert!(!is_prompt_gen_stale(Some(&record), "rust", "h1", false));
        assert!(is_prompt_gen_stale(Some(&record), "rust", "h2", false));
        assert!(is_prompt_gen_stale(Some(&record), "ts", "h1", false));

        let mut targets2 = OrderedMap::new();
        targets2.insert(
            "rust".to_string(),
            PromptTargetRecord {
                prompt_hash_at_gen: None,
                files: vec!["a.rs".to_string()],
                unattributed: Some(true),
            },
        );
        let record2 = PromptRecord {
            module: "m".to_string(),
            prompt_hash: "h1".to_string(),
            declared_targets: vec![],
            targets: targets2,
        };
        assert!(is_prompt_gen_stale(Some(&record2), "rust", "h1", false));
    }

    #[test]
    fn record_attribution_detaches_orphaned_prior_files() {
        let mut map = empty_map();
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![
                    FileInput { file_path: "src/a.rs".to_string(), hash: "f1".to_string() },
                    FileInput { file_path: "src/b.rs".to_string(), hash: "f2".to_string() },
                ],
            },
        );
        assert!(map.files.contains_key("src/a.rs"));
        assert!(map.files.contains_key("src/b.rs"));

        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h2".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![FileInput { file_path: "src/a.rs".to_string(), hash: "f1b".to_string() }],
            },
        );

        assert!(map.files.contains_key("src/a.rs"));
        assert!(!map.files.contains_key("src/b.rs"));
        let record = map.prompts.get("a.napl").unwrap();
        let target_record = record.targets.get("rust").unwrap();
        assert_eq!(target_record.prompt_hash_at_gen, Some("h2".to_string()));
        assert_eq!(target_record.files, vec!["src/a.rs".to_string()]);
    }

    #[test]
    fn record_attribution_keeps_shared_file_prompts_list() {
        let mut map = empty_map();
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![FileInput { file_path: "src/shared.rs".to_string(), hash: "f1".to_string() }],
            },
        );
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "b.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h2".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![FileInput { file_path: "src/shared.rs".to_string(), hash: "f1".to_string() }],
            },
        );

        let file_record = map.files.get("src/shared.rs").unwrap();
        assert_eq!(
            file_record.prompts,
            vec!["a.napl".to_string(), "b.napl".to_string()]
        );
    }

    #[test]
    fn record_attribution_keeps_other_targets_for_same_prompt() {
        let mut map = empty_map();
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![FileInput { file_path: "src/a.rs".to_string(), hash: "f1".to_string() }],
            },
        );
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "ts".to_string(),
                declared_targets: vec![],
                files: vec![FileInput { file_path: "src/a.ts".to_string(), hash: "f2".to_string() }],
            },
        );

        let record = map.prompts.get("a.napl").unwrap();
        assert!(record.targets.contains_key("rust"));
        assert!(record.targets.contains_key("ts"));
    }

    #[test]
    fn record_unattributed_detaches_all_prior_files_and_creates_no_file_records() {
        let mut map = empty_map();
        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![FileInput { file_path: "src/a.rs".to_string(), hash: "f1".to_string() }],
            },
        );
        assert!(map.files.contains_key("src/a.rs"));

        record_unattributed(
            &mut map,
            &UnattributedInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h2".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec!["src/a.rs".to_string(), "src/orphan.rs".to_string()],
            },
        );

        assert!(!map.files.contains_key("src/a.rs"));
        assert!(!map.files.contains_key("src/orphan.rs"));

        let record = map.prompts.get("a.napl").unwrap();
        let target_record = record.targets.get("rust").unwrap();
        assert_eq!(target_record.unattributed, Some(true));
        assert_eq!(target_record.prompt_hash_at_gen, None);
        assert_eq!(
            target_record.files,
            vec!["src/a.rs".to_string(), "src/orphan.rs".to_string()]
        );
    }

    #[test]
    fn record_attribution_after_unattributed_overwrites_and_clears_flag() {
        let mut map = empty_map();
        record_unattributed(
            &mut map,
            &UnattributedInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h1".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec!["src/a.rs".to_string()],
            },
        );

        record_attribution(
            &mut map,
            &AttributionInput {
                rel: "a.napl".to_string(),
                module: "m".to_string(),
                prompt_hash: "h2".to_string(),
                target: "rust".to_string(),
                declared_targets: vec![],
                files: vec![FileInput { file_path: "src/a.rs".to_string(), hash: "f1".to_string() }],
            },
        );

        let record = map.prompts.get("a.napl").unwrap();
        let target_record = record.targets.get("rust").unwrap();
        assert_eq!(target_record.unattributed, None);
        assert_eq!(target_record.prompt_hash_at_gen, Some("h2".to_string()));
        assert!(map.files.contains_key("src/a.rs"));
    }
}
