// GENERATED BY NAPL from schemas_ml.napl — edit the prompt, not this file

use schemas_line_range::LineRange;
use serde::Deserialize;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MlKind {
    Ambiguity,
    Assumption,
    Note,
    NoOp,
}

fn default_reasoning() -> String {
    String::new()
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct MlEntry {
    #[serde(rename = "promptLines")]
    pub prompt_lines: LineRange,
    pub kind: MlKind,
    pub message: String,
    #[serde(default = "default_reasoning")]
    pub reasoning: String,
    #[serde(default)]
    pub suggestion: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct Ml {
    pub module: String,
    pub target: String,
    #[serde(default)]
    pub entries: Vec<MlEntry>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MlError {
    Parse(String),
    EmptyModule,
    EmptyTarget,
    EmptyMessage,
}

impl std::fmt::Display for MlError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MlError::Parse(msg) => write!(f, "failed to parse ml document: {msg}"),
            MlError::EmptyModule => write!(f, "module must not be empty"),
            MlError::EmptyTarget => write!(f, "target must not be empty"),
            MlError::EmptyMessage => write!(f, "entry message must not be empty"),
        }
    }
}

impl std::error::Error for MlError {}

pub fn validate_ml(value: serde_json::Value) -> Result<Ml, MlError> {
    let ml: Ml = serde_json::from_value(value).map_err(|e| MlError::Parse(e.to_string()))?;

    if ml.module.is_empty() {
        return Err(MlError::EmptyModule);
    }
    if ml.target.is_empty() {
        return Err(MlError::EmptyTarget);
    }
    for entry in &ml.entries {
        if entry.message.is_empty() {
            return Err(MlError::EmptyMessage);
        }
    }

    Ok(ml)
}

pub fn parse_ml_entries(value: serde_json::Value) -> Result<Vec<MlEntry>, MlError> {
    if !value.is_array() {
        return Ok(Vec::new());
    }

    let entries: Vec<MlEntry> =
        serde_json::from_value(value).map_err(|e| MlError::Parse(e.to_string()))?;

    for entry in &entries {
        if entry.message.is_empty() {
            return Err(MlError::EmptyMessage);
        }
    }

    Ok(entries)
}

pub fn ml_entries_at_body_line(ml: &Ml, body_line: u32) -> Vec<&MlEntry> {
    ml.entries
        .iter()
        .filter(|entry| entry.prompt_lines.start <= body_line && body_line <= entry.prompt_lines.end)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn kind_kebab_case_spellings() {
        assert_eq!(
            serde_json::from_value::<MlKind>(json!("ambiguity")).unwrap(),
            MlKind::Ambiguity
        );
        assert_eq!(
            serde_json::from_value::<MlKind>(json!("assumption")).unwrap(),
            MlKind::Assumption
        );
        assert_eq!(
            serde_json::from_value::<MlKind>(json!("note")).unwrap(),
            MlKind::Note
        );
        assert_eq!(
            serde_json::from_value::<MlKind>(json!("no-op")).unwrap(),
            MlKind::NoOp
        );
    }

    #[test]
    fn unknown_kind_is_error() {
        assert!(serde_json::from_value::<MlKind>(json!("bogus")).is_err());
    }

    #[test]
    fn entry_defaults_reasoning_and_suggestion() {
        let entry: MlEntry = serde_json::from_value(json!({
            "promptLines": 18,
            "kind": "note",
            "message": "hello"
        }))
        .unwrap();
        assert_eq!(entry.prompt_lines, LineRange::new(18, 18));
        assert_eq!(entry.kind, MlKind::Note);
        assert_eq!(entry.message, "hello");
        assert_eq!(entry.reasoning, "");
        assert_eq!(entry.suggestion, None);
    }

    #[test]
    fn entry_with_reasoning_and_suggestion() {
        let entry: MlEntry = serde_json::from_value(json!({
            "promptLines": [3, 5],
            "kind": "assumption",
            "message": "m",
            "reasoning": "r",
            "suggestion": "s"
        }))
        .unwrap();
        assert_eq!(entry.prompt_lines, LineRange::new(3, 5));
        assert_eq!(entry.reasoning, "r");
        assert_eq!(entry.suggestion, Some("s".to_string()));
    }

    #[test]
    fn prompt_lines_string_is_deserialize_error() {
        let result: Result<MlEntry, _> = serde_json::from_value(json!({
            "promptLines": "1-2",
            "kind": "note",
            "message": "m"
        }));
        assert!(result.is_err());
    }

    #[test]
    fn validate_ml_accepts_valid_document() {
        let ml = validate_ml(json!({
            "module": "m",
            "target": "t",
            "entries": [
                {"promptLines": [1, 2], "kind": "ambiguity", "message": "a"}
            ]
        }))
        .unwrap();
        assert_eq!(ml.module, "m");
        assert_eq!(ml.target, "t");
        assert_eq!(ml.entries.len(), 1);
    }

    #[test]
    fn validate_ml_defaults_missing_entries_to_empty() {
        let ml = validate_ml(json!({"module": "m", "target": "t"})).unwrap();
        assert!(ml.entries.is_empty());
    }

    #[test]
    fn validate_ml_rejects_empty_module() {
        let result = validate_ml(json!({"module": "", "target": "t"}));
        assert_eq!(result.unwrap_err(), MlError::EmptyModule);
    }

    #[test]
    fn validate_ml_rejects_empty_target() {
        let result = validate_ml(json!({"module": "m", "target": ""}));
        assert_eq!(result.unwrap_err(), MlError::EmptyTarget);
    }

    #[test]
    fn validate_ml_rejects_empty_entry_message() {
        let result = validate_ml(json!({
            "module": "m",
            "target": "t",
            "entries": [{"promptLines": 1, "kind": "note", "message": ""}]
        }));
        assert_eq!(result.unwrap_err(), MlError::EmptyMessage);
    }

    #[test]
    fn validate_ml_rejects_unknown_kind() {
        let result = validate_ml(json!({
            "module": "m",
            "target": "t",
            "entries": [{"promptLines": 1, "kind": "bogus", "message": "m"}]
        }));
        assert!(matches!(result.unwrap_err(), MlError::Parse(_)));
    }

    #[test]
    fn validate_ml_rejects_string_prompt_lines() {
        let result = validate_ml(json!({
            "module": "m",
            "target": "t",
            "entries": [{"promptLines": "1-2", "kind": "note", "message": "m"}]
        }));
        assert!(matches!(result.unwrap_err(), MlError::Parse(_)));
    }

    #[test]
    fn parse_ml_entries_returns_empty_for_non_array() {
        assert_eq!(parse_ml_entries(json!({"not": "an array"})).unwrap(), vec![]);
        assert_eq!(parse_ml_entries(json!("string")).unwrap(), vec![]);
        assert_eq!(parse_ml_entries(json!(42)).unwrap(), vec![]);
    }

    #[test]
    fn parse_ml_entries_parses_valid_array() {
        let entries = parse_ml_entries(json!([
            {"promptLines": [1, 2], "kind": "note", "message": "a"},
            {"promptLines": 5, "kind": "no-op", "message": "b"}
        ]))
        .unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].message, "a");
        assert_eq!(entries[1].kind, MlKind::NoOp);
    }

    #[test]
    fn parse_ml_entries_rejects_empty_message() {
        let result = parse_ml_entries(json!([{"promptLines": 1, "kind": "note", "message": ""}]));
        assert_eq!(result.unwrap_err(), MlError::EmptyMessage);
    }

    #[test]
    fn parse_ml_entries_rejects_malformed_list() {
        let result = parse_ml_entries(json!([{"promptLines": 1, "kind": "bogus", "message": "m"}]));
        assert!(matches!(result.unwrap_err(), MlError::Parse(_)));
    }

    fn sample_ml() -> Ml {
        validate_ml(json!({
            "module": "m",
            "target": "t",
            "entries": [
                {"promptLines": [1, 2], "kind": "note", "message": "a"},
                {"promptLines": [5, 7], "kind": "note", "message": "b"}
            ]
        }))
        .unwrap()
    }

    #[test]
    fn lookup_finds_covering_entries_in_order() {
        let ml = sample_ml();
        let at1 = ml_entries_at_body_line(&ml, 1);
        assert_eq!(at1.len(), 1);
        assert_eq!(at1[0].message, "a");

        let at6 = ml_entries_at_body_line(&ml, 6);
        assert_eq!(at6.len(), 1);
        assert_eq!(at6[0].message, "b");
    }

    #[test]
    fn lookup_returns_empty_for_uncovered_line() {
        let ml = sample_ml();
        assert!(ml_entries_at_body_line(&ml, 4).is_empty());
    }
}
