// GENERATED BY NAPL from body_lines.napl — edit the prompt, not this file
//! Map between absolute line numbers of a `.napl` prompt document and the
//! 1-based line numbers of its prose body (the text following the YAML
//! frontmatter). Pure: no I/O, no dependencies.

/// The body of a prompt document: the prose that follows any YAML frontmatter.
pub struct PromptBody {
    /// Absolute, 0-based document line index at which the body begins.
    pub body_start_line: usize,
    /// The body's lines, in order, as owned strings.
    pub lines: Vec<String>,
}

/// Split a document into lines on the newline character, stripping a single
/// trailing carriage return from each line so that `\r\n` and `\n` line endings
/// yield identical results. Never drops a line: a document without a trailing
/// newline still yields its last line, and one ending in a newline yields a
/// final empty line.
fn split_lines(raw: &str) -> Vec<String> {
    raw.split('\n')
        .map(|line| line.strip_suffix('\r').unwrap_or(line).to_string())
        .collect()
}

/// Whether a line, compared after ignoring trailing whitespace, is exactly the
/// frontmatter delimiter `---`.
fn is_delimiter(line: &str) -> bool {
    line.trim_end() == "---"
}

/// Split the raw text of a prompt file into its frontmatter and body, returning
/// the body's absolute start line and its lines.
///
/// Frontmatter is recognised when the very first line is exactly `---` (ignoring
/// trailing whitespace) and some later line is also exactly `---`. When both
/// delimiters are present the body is everything after the closing `---`;
/// otherwise the whole document is the body and `body_start_line` is 0.
pub fn prompt_body_lines(raw: &str) -> PromptBody {
    let lines = split_lines(raw);

    if lines.first().is_some_and(|first| is_delimiter(first)) {
        if let Some(offset) = lines[1..].iter().position(|line| is_delimiter(line)) {
            let close = offset + 1;
            let body_start_line = close + 1;
            return PromptBody {
                body_start_line,
                lines: lines[body_start_line..].to_vec(),
            };
        }
    }

    PromptBody {
        body_start_line: 0,
        lines,
    }
}

/// Convert an absolute, 0-based document line number into a 1-based line number
/// within the body.
///
/// The body line is `doc_line - body_start_line + 1`; it is returned only when
/// it is a valid body position (at least 1 and no greater than the number of
/// body lines). Document lines above the body or past its final line yield
/// `None`. `doc_line` may be negative or out of range; arithmetic is checked so
/// that extreme values never panic.
pub fn body_line_for_doc_line(body: &PromptBody, doc_line: i64) -> Option<u64> {
    let body_line = doc_line
        .checked_sub(body.body_start_line as i64)
        .and_then(|value| value.checked_add(1))?;

    if body_line >= 1 && body_line <= body.lines.len() as i64 {
        Some(body_line as u64)
    } else {
        None
    }
}

/// Render a slice of lines as a single string for display. Each line is prefixed
/// by its 1-based position followed by `": "`, and the results are joined by
/// newlines.
pub fn number_lines(lines: &[String]) -> String {
    lines
        .iter()
        .enumerate()
        .map(|(index, line)| format!("{}: {}", index + 1, line))
        .collect::<Vec<String>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crlf_and_lf_produce_identical_lines() {
        let unix = prompt_body_lines("first\nsecond\nthird");
        let windows = prompt_body_lines("first\r\nsecond\r\nthird");
        assert_eq!(unix.lines, vec!["first", "second", "third"]);
        assert_eq!(windows.lines, unix.lines);
    }

    #[test]
    fn no_trailing_newline_keeps_last_line() {
        let body = prompt_body_lines("a\nb");
        assert_eq!(body.lines, vec!["a", "b"]);
    }

    #[test]
    fn trailing_newline_yields_final_empty_line() {
        let body = prompt_body_lines("a\nb\n");
        assert_eq!(body.lines, vec!["a", "b", ""]);
    }

    #[test]
    fn empty_document_is_one_empty_line() {
        let body = prompt_body_lines("");
        assert_eq!(body.body_start_line, 0);
        assert_eq!(body.lines, vec![""]);
    }

    #[test]
    fn frontmatter_body_starts_after_closing_delimiter() {
        let body = prompt_body_lines("---\ntitle: x\ntags: y\n---\nhello\nworld");
        assert_eq!(body.body_start_line, 4);
        assert_eq!(body.lines, vec!["hello", "world"]);
    }

    #[test]
    fn delimiters_ignore_trailing_whitespace() {
        let body = prompt_body_lines("---  \ntitle: x\n---\t\nprose");
        assert_eq!(body.body_start_line, 3);
        assert_eq!(body.lines, vec!["prose"]);
    }

    #[test]
    fn no_frontmatter_when_first_line_is_not_delimiter() {
        let body = prompt_body_lines("not front\n---\nmore");
        assert_eq!(body.body_start_line, 0);
        assert_eq!(body.lines, vec!["not front", "---", "more"]);
    }

    #[test]
    fn no_frontmatter_when_closing_delimiter_missing() {
        let body = prompt_body_lines("---\ntitle: x\nno close here");
        assert_eq!(body.body_start_line, 0);
        assert_eq!(body.lines, vec!["---", "title: x", "no close here"]);
    }

    #[test]
    fn frontmatter_followed_by_nothing_has_one_empty_body_line() {
        let body = prompt_body_lines("---\ntitle: x\n---\n");
        assert_eq!(body.body_start_line, 3);
        assert_eq!(body.lines, vec![""]);
    }

    #[test]
    fn body_line_within_range_is_one_based() {
        // Body starts at document line 4; body lines are "hello", "world".
        let body = prompt_body_lines("---\ntitle: x\ntags: y\n---\nhello\nworld");
        assert_eq!(body_line_for_doc_line(&body, 4), Some(1));
        assert_eq!(body_line_for_doc_line(&body, 5), Some(2));
    }

    #[test]
    fn body_line_above_body_is_none() {
        let body = prompt_body_lines("---\ntitle: x\ntags: y\n---\nhello\nworld");
        assert_eq!(body_line_for_doc_line(&body, 3), None);
        assert_eq!(body_line_for_doc_line(&body, 0), None);
    }

    #[test]
    fn body_line_past_body_is_none() {
        let body = prompt_body_lines("---\ntitle: x\ntags: y\n---\nhello\nworld");
        assert_eq!(body_line_for_doc_line(&body, 6), None);
    }

    #[test]
    fn body_line_negative_or_extreme_does_not_panic() {
        let body = prompt_body_lines("hello\nworld");
        assert_eq!(body_line_for_doc_line(&body, -1), None);
        assert_eq!(body_line_for_doc_line(&body, i64::MIN), None);
        assert_eq!(body_line_for_doc_line(&body, i64::MAX), None);
    }

    #[test]
    fn number_lines_matches_spec_example() {
        let lines = vec!["a".to_string(), "b".to_string()];
        assert_eq!(number_lines(&lines), "1: a\n2: b");
    }

    #[test]
    fn number_lines_of_empty_slice_is_empty_string() {
        assert_eq!(number_lines(&[]), "");
    }
}
