// GENERATED BY NAPL from text_diff.md — edit the prompt, not this file
//! Line-oriented text diffing.
//!
//! Produces and parses a unified diff between two texts, line by line, using a
//! longest-common-subsequence alignment. Pure: no I/O, no dependencies on other
//! project modules.

/// The kind of a hunk line.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HunkKind {
    Context,
    Del,
    Ins,
}

/// A single line within a hunk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HunkLine {
    pub kind: HunkKind,
    pub text: String,
}

/// A parsed unified-diff hunk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Hunk {
    pub old_start: usize,
    pub old_count: usize,
    pub new_start: usize,
    pub new_count: usize,
    pub lines: Vec<HunkLine>,
}

/// Split `text` into its lines as owned strings.
///
/// Empty text has no lines. Otherwise a single trailing terminator (`\n` or
/// `\r\n`) is removed, then the text is split on each `\n`; a `\r` immediately
/// before a split `\n` is consumed with it, but a lone `\r` stays in the line.
pub fn to_lines(text: &str) -> Vec<String> {
    if text.is_empty() {
        return Vec::new();
    }

    // Strip a single trailing terminator.
    let body = if let Some(stripped) = text.strip_suffix("\r\n") {
        stripped
    } else if let Some(stripped) = text.strip_suffix('\n') {
        stripped
    } else {
        text
    };

    body.split('\n')
        .map(|line| line.strip_suffix('\r').unwrap_or(line).to_string())
        .collect()
}

/// An aligned entry between `before` and `after`.
enum Entry {
    Context { old: usize, new: usize, text: String },
    Del { old: usize, text: String },
    Ins { new: usize, text: String },
}

/// Align `before` and `after` lines via longest-common-subsequence.
fn align(before: &[String], after: &[String]) -> Vec<Entry> {
    let n = before.len();
    let m = after.len();

    // LCS length table.
    let mut lcs = vec![vec![0usize; m + 1]; n + 1];
    for i in (0..n).rev() {
        for j in (0..m).rev() {
            lcs[i][j] = if before[i] == after[j] {
                lcs[i + 1][j + 1] + 1
            } else {
                lcs[i + 1][j].max(lcs[i][j + 1])
            };
        }
    }

    let mut entries = Vec::new();
    let mut i = 0;
    let mut j = 0;
    while i < n && j < m {
        if before[i] == after[j] {
            entries.push(Entry::Context {
                old: i + 1,
                new: j + 1,
                text: before[i].clone(),
            });
            i += 1;
            j += 1;
        } else if lcs[i + 1][j] >= lcs[i][j + 1] {
            entries.push(Entry::Del {
                old: i + 1,
                text: before[i].clone(),
            });
            i += 1;
        } else {
            entries.push(Entry::Ins {
                new: j + 1,
                text: after[j].clone(),
            });
            j += 1;
        }
    }
    while i < n {
        entries.push(Entry::Del {
            old: i + 1,
            text: before[i].clone(),
        });
        i += 1;
    }
    while j < m {
        entries.push(Entry::Ins {
            new: j + 1,
            text: after[j].clone(),
        });
        j += 1;
    }
    entries
}

/// Produce a unified diff with 3 lines of surrounding context.
pub fn unified_diff(before: &str, after: &str) -> String {
    unified_diff_with_context(before, after, 3)
}

/// Produce a unified diff with a caller-chosen context width.
pub fn unified_diff_with_context(before: &str, after: &str, context: usize) -> String {
    let before_lines = to_lines(before);
    let after_lines = to_lines(after);
    let entries = align(&before_lines, &after_lines);

    let is_change = |e: &Entry| matches!(e, Entry::Del { .. } | Entry::Ins { .. });

    // Mark which entries lie within `context` positions of a change.
    let mut included = vec![false; entries.len()];
    for (idx, e) in entries.iter().enumerate() {
        if is_change(e) {
            let lo = idx.saturating_sub(context);
            let hi = (idx + context).min(entries.len().saturating_sub(1));
            for slot in included.iter_mut().take(hi + 1).skip(lo) {
                *slot = true;
            }
        }
    }

    // Group consecutive included entries into hunks and emit.
    let mut out: Vec<String> = Vec::new();
    let mut idx = 0;
    while idx < entries.len() {
        if !included[idx] {
            idx += 1;
            continue;
        }
        let start = idx;
        while idx < entries.len() && included[idx] {
            idx += 1;
        }
        let hunk = &entries[start..idx];

        let mut old_start = 0;
        let mut new_start = 0;
        let mut old_count = 0;
        let mut new_count = 0;
        for e in hunk {
            match e {
                Entry::Context { old, new, .. } => {
                    if old_start == 0 {
                        old_start = *old;
                    }
                    if new_start == 0 {
                        new_start = *new;
                    }
                    old_count += 1;
                    new_count += 1;
                }
                Entry::Del { old, .. } => {
                    if old_start == 0 {
                        old_start = *old;
                    }
                    old_count += 1;
                }
                Entry::Ins { new, .. } => {
                    if new_start == 0 {
                        new_start = *new;
                    }
                    new_count += 1;
                }
            }
        }

        out.push(format!(
            "@@ -{},{} +{},{} @@",
            old_start, old_count, new_start, new_count
        ));
        for e in hunk {
            match e {
                Entry::Context { text, .. } => out.push(format!(" {}", text)),
                Entry::Del { text, .. } => out.push(format!("-{}", text)),
                Entry::Ins { text, .. } => out.push(format!("+{}", text)),
            }
        }
    }

    out.join("\n")
}

/// Parse the header shape `@@ -A,B +C,D @@` into its four numbers.
fn parse_header(line: &str) -> Option<(usize, usize, usize, usize)> {
    let rest = line.strip_prefix("@@ -")?;
    let rest = rest.strip_suffix(" @@")?;
    let (old_part, new_part) = rest.split_once(" +")?;
    let (a, b) = old_part.split_once(',')?;
    let (c, d) = new_part.split_once(',')?;
    Some((
        a.parse().ok()?,
        b.parse().ok()?,
        c.parse().ok()?,
        d.parse().ok()?,
    ))
}

/// Parse the hunks contained in a unified-diff string.
pub fn parse_hunks(diff: &str) -> Vec<Hunk> {
    if diff.trim().is_empty() {
        return Vec::new();
    }

    let mut hunks: Vec<Hunk> = Vec::new();
    for line in to_lines(diff) {
        if let Some((old_start, old_count, new_start, new_count)) = parse_header(&line) {
            hunks.push(Hunk {
                old_start,
                old_count,
                new_start,
                new_count,
                lines: Vec::new(),
            });
            continue;
        }

        let Some(hunk) = hunks.last_mut() else {
            continue;
        };
        let mut chars = line.chars();
        let marker = chars.next();
        let text = chars.as_str().to_string();
        let kind = match marker {
            Some(' ') => HunkKind::Context,
            Some('-') => HunkKind::Del,
            Some('+') => HunkKind::Ins,
            _ => continue,
        };
        hunk.lines.push(HunkLine { kind, text });
    }
    hunks
}

/// Reconstruct the diff's target from the original text and parsed hunks.
pub fn apply_hunks(before: &str, hunks: &[Hunk]) -> String {
    let before_lines = to_lines(before);
    let mut out: Vec<String> = Vec::new();
    let mut pos = 0; // 0-based position within before_lines

    for hunk in hunks {
        // Copy original lines before this hunk's start.
        // old_start is 1-based; a hunk with no old lines uses 0.
        let target = if hunk.old_start == 0 {
            pos
        } else {
            hunk.old_start - 1
        };
        while pos < target && pos < before_lines.len() {
            out.push(before_lines[pos].clone());
            pos += 1;
        }

        for line in &hunk.lines {
            match line.kind {
                HunkKind::Context => {
                    if pos < before_lines.len() {
                        out.push(before_lines[pos].clone());
                    } else {
                        out.push(line.text.clone());
                    }
                    pos += 1;
                }
                HunkKind::Del => {
                    pos += 1;
                }
                HunkKind::Ins => {
                    out.push(line.text.clone());
                }
            }
        }
    }

    while pos < before_lines.len() {
        out.push(before_lines[pos].clone());
        pos += 1;
    }

    out.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn to_lines_empty() {
        assert_eq!(to_lines(""), Vec::<String>::new());
    }

    #[test]
    fn to_lines_trailing_newline() {
        assert_eq!(to_lines("a\nb\n"), vec!["a", "b"]);
        assert_eq!(to_lines("a\nb"), vec!["a", "b"]);
    }

    #[test]
    fn to_lines_crlf() {
        assert_eq!(to_lines("a\r\nb\r\n"), vec!["a", "b"]);
        assert_eq!(to_lines("a\r\nb"), vec!["a", "b"]);
    }

    #[test]
    fn to_lines_lone_cr() {
        assert_eq!(to_lines("a\rb\n"), vec!["a\rb"]);
    }

    #[test]
    fn to_lines_no_trailing_newline() {
        assert_eq!(to_lines("hello"), vec!["hello"]);
    }

    #[test]
    fn to_lines_blank_lines() {
        assert_eq!(to_lines("a\n\nb\n"), vec!["a", "", "b"]);
    }

    #[test]
    fn unified_diff_empty_to_content() {
        assert_eq!(unified_diff("", "a\nb\n"), "@@ -0,0 +1,2 @@\n+a\n+b");
    }

    #[test]
    fn unified_diff_content_to_empty() {
        assert_eq!(unified_diff("a\nb\n", ""), "@@ -1,2 +0,0 @@\n-a\n-b");
    }

    #[test]
    fn unified_diff_identical() {
        assert_eq!(unified_diff("a\nb\n", "a\nb\n"), "");
        assert_eq!(unified_diff("", ""), "");
    }

    #[test]
    fn unified_diff_mixed() {
        let before = "a\nb\nc\nd\ne\n";
        let after = "a\nb\nC\nd\ne\n";
        let diff = unified_diff(before, after);
        assert_eq!(
            diff,
            "@@ -1,5 +1,5 @@\n a\n b\n-c\n+C\n d\n e"
        );
    }

    #[test]
    fn unified_diff_insert_and_delete() {
        let before = "one\ntwo\nthree\n";
        let after = "one\ntwo-and-a-half\ntwo\nthree\n";
        let diff = unified_diff(before, after);
        let hunks = parse_hunks(&diff);
        assert_eq!(apply_hunks(before, &hunks), to_lines(after).join("\n"));
    }

    #[test]
    fn unified_diff_with_context_narrow() {
        // Two separate changes far apart; with context 1 they stay separate hunks,
        // with context 3 (default) they would merge.
        let before = "a\nb\nc\nd\ne\nf\ng\nh\ni\n";
        let after = "a\nB\nc\nd\ne\nf\ng\nH\ni\n";
        let diff = unified_diff_with_context(before, after, 1);
        assert_eq!(
            diff,
            "@@ -1,3 +1,3 @@\n a\n-b\n+B\n c\n@@ -7,3 +7,3 @@\n g\n-h\n+H\n i"
        );
    }

    #[test]
    fn parse_hunks_example() {
        let diff = "@@ -1,3 +1,3 @@\n a\n-b\n+B\n c";
        let hunks = parse_hunks(diff);
        assert_eq!(hunks.len(), 1);
        let h = &hunks[0];
        assert_eq!(h.old_start, 1);
        assert_eq!(h.old_count, 3);
        assert_eq!(h.new_start, 1);
        assert_eq!(h.new_count, 3);
        assert_eq!(
            h.lines,
            vec![
                HunkLine { kind: HunkKind::Context, text: "a".to_string() },
                HunkLine { kind: HunkKind::Del, text: "b".to_string() },
                HunkLine { kind: HunkKind::Ins, text: "B".to_string() },
                HunkLine { kind: HunkKind::Context, text: "c".to_string() },
            ]
        );
    }

    #[test]
    fn parse_hunks_empty_and_whitespace() {
        assert_eq!(parse_hunks(""), Vec::new());
        assert_eq!(parse_hunks("   \n  \n"), Vec::new());
    }

    #[test]
    fn parse_hunks_ignores_unknown_lines() {
        let diff = "@@ -1,1 +1,1 @@\n a\n?noise\n";
        let hunks = parse_hunks(diff);
        assert_eq!(hunks.len(), 1);
        assert_eq!(hunks[0].lines.len(), 1);
        assert_eq!(hunks[0].lines[0].kind, HunkKind::Context);
    }

    #[test]
    fn apply_hunks_example() {
        let before = "a\nb\nc\n";
        let diff = "@@ -1,3 +1,3 @@\n a\n-b\n+B\n c";
        let hunks = parse_hunks(diff);
        assert_eq!(apply_hunks(before, &hunks), "a\nB\nc");
    }

    #[test]
    fn apply_hunks_no_hunks_copies_all() {
        let before = "a\nb\nc\n";
        assert_eq!(apply_hunks(before, &[]), "a\nb\nc");
    }

    fn roundtrip(before: &str, after: &str) {
        let diff = unified_diff(before, after);
        let hunks = parse_hunks(&diff);
        assert_eq!(
            apply_hunks(before, &hunks),
            to_lines(after).join("\n"),
            "roundtrip failed for {:?} -> {:?}",
            before,
            after
        );
    }

    #[test]
    fn roundtrip_property() {
        roundtrip("", "a\nb\n");
        roundtrip("a\nb\n", "");
        roundtrip("a\nb\n", "a\nb\n");
        roundtrip("a\nb\nc\nd\ne\n", "a\nb\nC\nd\ne\n");
        roundtrip("one\ntwo\nthree\n", "one\ntwo-and-a-half\ntwo\nthree\n");
        roundtrip("a\nb\nc\nd\ne\nf\ng\nh\ni\n", "a\nB\nc\nd\ne\nf\ng\nH\ni\n");
        roundtrip("x\ny\nz\n", "z\ny\nx\n");
        roundtrip("hello world\n", "goodbye world\nand more\n");
        roundtrip("same\nlines\nhere\n", "same\nlines\nhere\n");
        roundtrip("trailing", "trailing\nextra");
    }
}
