// GENERATED BY NAPL from schemas_line_range.napl — edit the prompt, not this file

use serde::de::{self, Deserialize, Deserializer, Visitor};
use std::fmt;

/// A 1-based inclusive line range.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LineRange {
    pub start: u32,
    pub end: u32,
}

impl LineRange {
    pub fn new(start: u32, end: u32) -> Self {
        LineRange { start, end }
    }
}

fn number_to_line(n: serde_json::Number) -> Result<u32, String> {
    if let Some(i) = n.as_u64() {
        if i < 1 {
            return Err(format!("line number must be at least 1, got {i}"));
        }
        u32::try_from(i).map_err(|_| format!("line number out of range: {i}"))
    } else if let Some(f) = n.as_f64() {
        if f.fract() != 0.0 {
            return Err(format!("line number must be an integer, got {f}"));
        }
        if f < 1.0 {
            return Err(format!("line number must be at least 1, got {f}"));
        }
        Ok(f as u32)
    } else {
        Err(format!("line number must be an integer, got {n}"))
    }
}

struct LineRangeVisitor;

impl<'de> Visitor<'de> for LineRangeVisitor {
    type Value = LineRange;

    fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        formatter.write_str("a line number, or a 1- or 2-element array of line numbers")
    }

    fn visit_u64<E>(self, v: u64) -> Result<Self::Value, E>
    where
        E: de::Error,
    {
        let n = number_to_line(serde_json::Number::from(v)).map_err(de::Error::custom)?;
        Ok(LineRange::new(n, n))
    }

    fn visit_i64<E>(self, v: i64) -> Result<Self::Value, E>
    where
        E: de::Error,
    {
        if v < 0 {
            return Err(de::Error::custom(format!(
                "line number must be at least 1, got {v}"
            )));
        }
        self.visit_u64(v as u64)
    }

    fn visit_f64<E>(self, v: f64) -> Result<Self::Value, E>
    where
        E: de::Error,
    {
        let n = serde_json::Number::from_f64(v)
            .ok_or_else(|| de::Error::custom(format!("invalid number: {v}")))?;
        let n = number_to_line(n).map_err(de::Error::custom)?;
        Ok(LineRange::new(n, n))
    }

    fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
    where
        A: de::SeqAccess<'de>,
    {
        let mut values: Vec<serde_json::Number> = Vec::new();
        while let Some(v) = seq.next_element::<serde_json::Value>()? {
            match v {
                serde_json::Value::Number(n) => values.push(n),
                other => {
                    return Err(de::Error::custom(format!(
                        "expected a number in line range array, got {other}"
                    )))
                }
            }
        }
        match values.len() {
            1 => {
                let n = number_to_line(values.into_iter().next().unwrap())
                    .map_err(de::Error::custom)?;
                Ok(LineRange::new(n, n))
            }
            2 => {
                let mut it = values.into_iter();
                let start = number_to_line(it.next().unwrap()).map_err(de::Error::custom)?;
                let end = number_to_line(it.next().unwrap()).map_err(de::Error::custom)?;
                Ok(LineRange::new(start, end))
            }
            n => Err(de::Error::custom(format!(
                "line range array must have 1 or 2 elements, got {n}"
            ))),
        }
    }
}

impl<'de> Deserialize<'de> for LineRange {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        deserializer.deserialize_any(LineRangeVisitor)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(json: &str) -> Result<LineRange, serde_json::Error> {
        serde_json::from_str(json)
    }

    #[test]
    fn new_constructor_and_equality() {
        let a = LineRange::new(1, 3);
        let b = LineRange::new(1, 3);
        assert_eq!(a, b);
        assert_eq!(a.start, 1);
        assert_eq!(a.end, 3);
        let c = a;
        assert_eq!(a, c);
    }

    #[test]
    fn bare_number_becomes_single_line_range() {
        assert_eq!(parse("5").unwrap(), LineRange::new(5, 5));
    }

    #[test]
    fn one_element_array_becomes_single_line_range() {
        assert_eq!(parse("[5]").unwrap(), LineRange::new(5, 5));
    }

    #[test]
    fn two_element_array_becomes_range() {
        assert_eq!(parse("[2, 7]").unwrap(), LineRange::new(2, 7));
    }

    #[test]
    fn bare_zero_is_rejected() {
        assert!(parse("0").is_err());
    }

    #[test]
    fn zero_in_array_is_rejected() {
        assert!(parse("[0, 2]").is_err());
    }

    #[test]
    fn fractional_bare_number_is_rejected() {
        assert!(parse("1.5").is_err());
    }

    #[test]
    fn fractional_number_in_array_is_rejected() {
        assert!(parse("[1.5, 2]").is_err());
    }

    #[test]
    fn whole_valued_float_is_accepted() {
        assert_eq!(parse("2.0").unwrap(), LineRange::new(2, 2));
    }

    #[test]
    fn three_element_array_is_rejected() {
        assert!(parse("[1, 2, 3]").is_err());
    }

    #[test]
    fn empty_array_is_rejected() {
        assert!(parse("[]").is_err());
    }

    #[test]
    fn string_is_rejected() {
        assert!(parse("\"nope\"").is_err());
    }

    #[test]
    fn boolean_is_rejected() {
        assert!(parse("true").is_err());
    }

    #[test]
    fn object_is_rejected() {
        assert!(parse("{\"start\": 1, \"end\": 2}").is_err());
    }

    #[test]
    fn negative_number_is_rejected() {
        assert!(parse("-1").is_err());
    }
}
