// GENERATED BY NAPL from body_lines.napl — edit the prompt, not this file

/// The prose body of a `.napl` prompt document, split into lines, along with
/// the absolute document line at which it begins.
pub struct PromptBody {
    pub body_start_line: usize,
    pub lines: Vec<String>,
}

fn split_lines(raw: &str) -> Vec<String> {
    raw.split('\n')
        .map(|line| line.strip_suffix('\r').unwrap_or(line).to_string())
        .collect()
}

/// Split a prompt document into its frontmatter-delimited body.
pub fn prompt_body_lines(raw: &str) -> PromptBody {
    let lines = split_lines(raw);

    let has_opening = lines
        .first()
        .is_some_and(|line| line.trim_end() == "---");

    if has_opening {
        if let Some(close_idx) = lines
            .iter()
            .enumerate()
            .skip(1)
            .find(|(_, line)| line.trim_end() == "---")
            .map(|(idx, _)| idx)
        {
            let body_start_line = close_idx + 1;
            let body = if body_start_line >= lines.len() {
                vec![String::new()]
            } else {
                lines[body_start_line..].to_vec()
            };
            return PromptBody {
                body_start_line,
                lines: body,
            };
        }
    }

    PromptBody {
        body_start_line: 0,
        lines,
    }
}

/// Convert an absolute, 0-based document line number into a 1-based line
/// number within the body, or `None` if it falls outside the body.
pub fn body_line_for_doc_line(body: &PromptBody, doc_line: i64) -> Option<usize> {
    let body_line = doc_line
        .checked_sub(body.body_start_line as i64)
        .and_then(|n| n.checked_add(1))?;
    if body_line >= 1 && body_line as usize <= body.lines.len() {
        Some(body_line as usize)
    } else {
        None
    }
}

/// Render lines for display, each prefixed with its 1-based position.
pub fn number_lines(lines: &[String]) -> String {
    lines
        .iter()
        .enumerate()
        .map(|(idx, line)| format!("{}: {}", idx + 1, line))
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splits_on_unix_and_windows_newlines() {
        let unix = prompt_body_lines("a\nb\nc");
        let windows = prompt_body_lines("a\r\nb\r\nc");
        assert_eq!(unix.lines, windows.lines);
        assert_eq!(unix.lines, vec!["a", "b", "c"]);
    }

    #[test]
    fn no_trailing_newline_keeps_last_line() {
        let body = prompt_body_lines("a\nb");
        assert_eq!(body.lines, vec!["a", "b"]);
    }

    #[test]
    fn trailing_newline_yields_final_empty_line() {
        let body = prompt_body_lines("a\nb\n");
        assert_eq!(body.lines, vec!["a", "b", ""]);
    }

    #[test]
    fn no_frontmatter_body_is_whole_document() {
        let body = prompt_body_lines("hello\nworld");
        assert_eq!(body.body_start_line, 0);
        assert_eq!(body.lines, vec!["hello", "world"]);
    }

    #[test]
    fn first_line_not_delimiter_means_no_frontmatter() {
        let body = prompt_body_lines("title\n---\nbody");
        assert_eq!(body.body_start_line, 0);
        assert_eq!(body.lines, vec!["title", "---", "body"]);
    }

    #[test]
    fn missing_closing_delimiter_means_no_frontmatter() {
        let body = prompt_body_lines("---\nkey: value\nno closing here");
        assert_eq!(body.body_start_line, 0);
        assert_eq!(body.lines, vec!["---", "key: value", "no closing here"]);
    }

    #[test]
    fn frontmatter_is_stripped() {
        let body = prompt_body_lines("---\nkey: value\n---\nline one\nline two");
        assert_eq!(body.body_start_line, 3);
        assert_eq!(body.lines, vec!["line one", "line two"]);
    }

    #[test]
    fn delimiters_compared_ignoring_trailing_whitespace() {
        let body = prompt_body_lines("---  \nkey: value\n---\t\nbody line");
        assert_eq!(body.body_start_line, 3);
        assert_eq!(body.lines, vec!["body line"]);
    }

    #[test]
    fn frontmatter_followed_by_nothing_has_one_empty_body_line() {
        let body = prompt_body_lines("---\nkey: value\n---");
        assert_eq!(body.body_start_line, 3);
        assert_eq!(body.lines, vec![""]);
    }

    #[test]
    fn body_line_for_doc_line_maps_within_range() {
        let body = prompt_body_lines("---\nkey: value\n---\nfirst\nsecond");
        assert_eq!(body_line_for_doc_line(&body, 3), Some(1));
        assert_eq!(body_line_for_doc_line(&body, 4), Some(2));
    }

    #[test]
    fn body_line_for_doc_line_before_body_is_none() {
        let body = prompt_body_lines("---\nkey: value\n---\nfirst\nsecond");
        assert_eq!(body_line_for_doc_line(&body, 0), None);
        assert_eq!(body_line_for_doc_line(&body, 2), None);
    }

    #[test]
    fn body_line_for_doc_line_past_end_is_none() {
        let body = prompt_body_lines("---\nkey: value\n---\nfirst\nsecond");
        assert_eq!(body_line_for_doc_line(&body, 5), None);
    }

    #[test]
    fn body_line_for_doc_line_handles_negative_and_large_values() {
        let body = prompt_body_lines("first\nsecond");
        assert_eq!(body_line_for_doc_line(&body, -5), None);
        assert_eq!(body_line_for_doc_line(&body, i64::MAX), None);
        assert_eq!(body_line_for_doc_line(&body, i64::MIN), None);
    }

    #[test]
    fn number_lines_renders_with_positions() {
        let lines = vec!["a".to_string(), "b".to_string()];
        assert_eq!(number_lines(&lines), "1: a\n2: b");
    }

    #[test]
    fn number_lines_empty_slice_is_empty_string() {
        let lines: Vec<String> = vec![];
        assert_eq!(number_lines(&lines), "");
    }
}
