//! Guard-rail content: the generated-tree AGENTS.md/CLAUDE.md doc, the
//! pre-commit hook, the Claude deny rules, and the `.claude/settings.json`
//! merge logic. Pure strings and pure JSON merging.

/// The guard doc written into every generated target tree.
pub const GUARD_DOC: &str = "Files in this tree are GENERATED by NAPL from the .napl prompt files in the project root. Do not edit them directly — edit the prompts and run napl gen. Direct edits are detected as DRIFT and block compilation.\n";

/// The guard file names written into each target tree.
pub const GUARD_FILE_NAMES: [&str; 2] = ["AGENTS.md", "CLAUDE.md"];

/// The POSIX pre-commit hook that gates commits on `napl status`.
pub const PRE_COMMIT_HOOK: &str = "#!/bin/sh\nif ! napl status; then\n\techo \"napl: commit blocked — generated code has drifted from its prompts (see above).\" >&2\n\techo \"napl: to commit anyway (work in progress), run: git commit --no-verify\" >&2\n\texit 1\nfi\n";

/// The single line users are told to add to a pre-existing hook.
pub const PRE_COMMIT_HOOK_LINE: &str = "napl status";

/// The Claude Code deny rules NAPL installs.
pub const NAPL_DENY_RULES: [&str; 1] = ["Edit(/.napl/src/**)"];

fn deny_settings_value() -> serde_json::Value {
    serde_json::json!({
        "permissions": {
            "deny": NAPL_DENY_RULES.to_vec(),
        }
    })
}

/// The `.claude/settings.json` snippet created on a fresh init.
#[must_use]
pub fn claude_settings_snippet() -> String {
    let mut out = serde_json::to_string_pretty(&deny_settings_value()).expect("settings serialize");
    out.push('\n');
    out
}

/// The outcome kind of a settings merge.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SettingsMergeAction {
    /// No file existed; create one.
    Create,
    /// The file existed and gained the deny rule.
    Update,
    /// The file already denied the rule.
    Unchanged,
    /// The file could not be safely merged.
    Manual,
}

/// The result of merging the deny rule into an existing settings file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SettingsMergeResult {
    /// What happened.
    pub action: SettingsMergeAction,
    /// The new file content to write, when applicable.
    pub content: Option<String>,
    /// The rules that were added.
    pub added: Vec<String>,
}

fn manual() -> SettingsMergeResult {
    SettingsMergeResult {
        action: SettingsMergeAction::Manual,
        content: None,
        added: Vec::new(),
    }
}

/// Merge the NAPL deny rule into an existing `.claude/settings.json`, mirroring
/// `mergeClaudeSettings`.
#[must_use]
pub fn merge_claude_settings(existing: Option<&str>) -> SettingsMergeResult {
    let Some(existing) = existing else {
        return SettingsMergeResult {
            action: SettingsMergeAction::Create,
            content: Some(claude_settings_snippet()),
            added: NAPL_DENY_RULES.iter().map(ToString::to_string).collect(),
        };
    };

    let Ok(parsed) = serde_json::from_str::<serde_json::Value>(existing) else {
        return manual();
    };
    let serde_json::Value::Object(root) = &parsed else {
        return manual();
    };

    let permissions = root.get("permissions");
    let perm_object = match permissions {
        None => serde_json::Map::new(),
        Some(serde_json::Value::Object(map)) => map.clone(),
        Some(_) => return manual(),
    };

    let deny = perm_object.get("deny");
    let mut deny_array = match deny {
        None => Vec::new(),
        Some(serde_json::Value::Array(items)) => items.clone(),
        Some(_) => return manual(),
    };

    let mut added: Vec<String> = Vec::new();
    for rule in NAPL_DENY_RULES {
        let rule_value = serde_json::Value::String(rule.to_string());
        if !deny_array.contains(&rule_value) {
            deny_array.push(rule_value);
            added.push(rule.to_string());
        }
    }
    if added.is_empty() {
        return SettingsMergeResult {
            action: SettingsMergeAction::Unchanged,
            content: None,
            added: Vec::new(),
        };
    }

    let mut new_perm = perm_object;
    new_perm.insert("deny".to_string(), serde_json::Value::Array(deny_array));
    let mut merged = root.clone();
    merged.insert(
        "permissions".to_string(),
        serde_json::Value::Object(new_perm),
    );
    let mut content =
        serde_json::to_string_pretty(&serde_json::Value::Object(merged)).expect("merge serialize");
    content.push('\n');
    SettingsMergeResult {
        action: SettingsMergeAction::Update,
        content: Some(content),
        added,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snippet_is_pretty_with_trailing_newline() {
        assert_eq!(
            claude_settings_snippet(),
            "{\n  \"permissions\": {\n    \"deny\": [\n      \"Edit(/.napl/src/**)\"\n    ]\n  }\n}\n"
        );
    }

    #[test]
    fn create_when_absent() {
        let result = merge_claude_settings(None);
        assert_eq!(result.action, SettingsMergeAction::Create);
        assert_eq!(result.content, Some(claude_settings_snippet()));
    }

    #[test]
    fn unchanged_when_rule_present() {
        let existing = claude_settings_snippet();
        let result = merge_claude_settings(Some(&existing));
        assert_eq!(result.action, SettingsMergeAction::Unchanged);
        assert!(result.content.is_none());
    }

    #[test]
    fn update_merges_without_clobbering() {
        let existing =
            "{\n  \"other\": true,\n  \"permissions\": {\n    \"allow\": [\"Read\"]\n  }\n}";
        let result = merge_claude_settings(Some(existing));
        assert_eq!(result.action, SettingsMergeAction::Update);
        let content = result.content.unwrap();
        assert!(content.contains("\"other\": true"));
        assert!(content.contains("\"allow\""));
        assert!(content.contains("Edit(/.napl/src/**)"));
        assert!(content.ends_with("}\n"));
    }

    #[test]
    fn manual_on_garbage() {
        assert_eq!(
            merge_claude_settings(Some("not json")).action,
            SettingsMergeAction::Manual
        );
        assert_eq!(
            merge_claude_settings(Some("[1,2,3]")).action,
            SettingsMergeAction::Manual
        );
        assert_eq!(
            merge_claude_settings(Some("{\"permissions\": 5}")).action,
            SettingsMergeAction::Manual
        );
    }
}
