//! Target adapters: per-language configuration for generation, testing, and
//! attribution filtering. Pure data, mirroring the TypeScript target registry.

/// A target's test invocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TestRunCommand {
    /// The executable to run.
    pub command: String,
    /// Its arguments.
    pub args: Vec<String>,
}

/// Per-target configuration consumed by `gen`/`test`.
#[derive(Debug, Clone)]
pub struct TargetAdapter {
    /// The target name (also the src subdirectory).
    pub name: &'static str,
    /// Idiom guidance injected into the coding-agent task.
    pub idiom_guidance: String,
    /// Tools the coding agent is allowed to use.
    pub agent_tools: Vec<String>,
    /// Directory names excluded from attribution snapshots.
    pub attribution_exclude_dirs: Vec<String>,
    /// File names excluded from attribution snapshots.
    pub attribution_exclude_files: Vec<String>,
    /// File names excluded from attribution snapshots **only at the target-dir
    /// root** — sibling files of the same name deeper in the tree stay
    /// attributed. Used for toolchain-owned root manifests (the Cargo workspace
    /// `Cargo.toml`) whose per-module namesakes remain agent-owned.
    pub attribution_exclude_root_files: Vec<String>,
    /// File suffixes excluded from attribution snapshots.
    pub attribution_exclude_suffixes: Vec<String>,
    /// Human-facing label for the test command.
    pub test_command_label: &'static str,
    /// The test invocation that gates generation and backs `napl test`.
    pub test_run: TestRunCommand,
    /// When true the target dir is a Cargo-style workspace: each module is a
    /// member crate in a subdirectory named after the module, and the toolchain
    /// owns a root manifest listing every member. When false the target dir
    /// holds a single package rooted at the target dir.
    pub workspace_layout: bool,
}

/// The toolchain-owned header stamped onto a generated workspace root manifest.
const WORKSPACE_MANIFEST_HEADER: &str =
    "# GENERATED BY NAPL — Cargo workspace manifest (toolchain-owned; do not edit).\n# Members are the generated module crates; each is regenerated from its .napl prompt.\n";

/// Render the workspace root `Cargo.toml` for a Cargo-workspace target, listing
/// `members` (each a module-named member crate directory). The caller supplies
/// members already sorted; the output is deterministic for a given member set.
#[must_use]
pub fn workspace_manifest_toml(members: &[String]) -> String {
    let mut out = String::from(WORKSPACE_MANIFEST_HEADER);
    out.push_str("[workspace]\nresolver = \"2\"\nmembers = [\n");
    for member in members {
        out.push_str("    \"");
        out.push_str(member);
        out.push_str("\",\n");
    }
    out.push_str("]\n");
    out
}

impl TargetAdapter {
    /// The test command to run in `target_dir` (the command is fixed per target).
    #[must_use]
    pub fn test_command(&self, _target_dir: &str) -> TestRunCommand {
        self.test_run.clone()
    }
}

fn vitest_run() -> TestRunCommand {
    TestRunCommand {
        command: "npx".to_string(),
        args: vec!["vitest".to_string(), "run".to_string()],
    }
}

fn cargo_test() -> TestRunCommand {
    TestRunCommand {
        command: "cargo".to_string(),
        args: vec!["test".to_string()],
    }
}

fn base_agent_tools() -> Vec<String> {
    [
        "Read",
        "Edit",
        "Write",
        "Bash(npm:*)",
        "Bash(npx:*)",
        "Bash(node:*)",
        "Bash(mkdir:*)",
        "Bash(ls:*)",
        "Bash(cat:*)",
        "Bash(rm:*)",
        "Bash(mv:*)",
        "Bash(cp:*)",
        "Bash(touch:*)",
        "Bash(echo:*)",
        "Bash(sed:*)",
    ]
    .iter()
    .map(ToString::to_string)
    .collect()
}

fn rust_agent_tools() -> Vec<String> {
    [
        "Read",
        "Edit",
        "Write",
        "Bash(cargo:*)",
        "Bash(rustc:*)",
        "Bash(rustfmt:*)",
        "Bash(mkdir:*)",
        "Bash(ls:*)",
        "Bash(cat:*)",
        "Bash(rm:*)",
        "Bash(mv:*)",
        "Bash(cp:*)",
        "Bash(touch:*)",
        "Bash(echo:*)",
        "Bash(sed:*)",
    ]
    .iter()
    .map(ToString::to_string)
    .collect()
}

fn base_exclude_dirs() -> Vec<String> {
    ["node_modules", "dist", ".git", "build", "coverage", ".vite"]
        .iter()
        .map(ToString::to_string)
        .collect()
}

fn base_exclude_files() -> Vec<String> {
    ["package-lock.json", "AGENTS.md", "CLAUDE.md"]
        .iter()
        .map(ToString::to_string)
        .collect()
}

fn base_exclude_suffixes() -> Vec<String> {
    [".tsbuildinfo", ".d.ts"]
        .iter()
        .map(ToString::to_string)
        .collect()
}

const TYPESCRIPT_IDIOM: &str = "Target: a TypeScript library package (ESM, strict mode) tested with vitest.\nIf the workspace has no package.json, scaffold one in place: a \"type\": \"module\" package,\nadd vitest and typescript as devDependencies, add a \"test\" script running \"vitest run\",\nand run \"npm install\".\nWrite idiomatic, modern TypeScript. Use named exports only — never default exports.\nPrefer plain functions; never introduce a class when a function suffices.\nCo-locate a *.test.ts vitest suite that asserts the described behavior.\nBegin every source file you create with a first-line comment exactly of the form:\n// GENERATED BY NAPL from <prompt filename> — edit the prompt, not this file\nsubstituting the driving prompt file name.\nEnsure \"npx vitest run\" passes from this directory before finishing.";

const REACT_IDIOM: &str = "Target: a React single-page app built with Vite + React + TypeScript.\nIf the workspace is empty, scaffold a Vite React + TypeScript project in place:\npackage.json, index.html, vite.config.ts, tsconfig.json, tsconfig.node.json,\nsrc/main.tsx and src/App.tsx — then run \"npm install\".\nUse function components and hooks only — never class components.\nUse named exports for your own modules and keep components small and composable.\nAdd test tooling: vitest, @testing-library/react, @testing-library/jest-dom, jsdom.\nConfigure vitest to use the \"jsdom\" environment (test.environment) and a setup file\nthat imports \"@testing-library/jest-dom\" — put this in vite.config.ts or vitest.config.ts.\nWrite component tests with @testing-library/react that exercise every described behavior\n(rendering, user events via fireEvent/userEvent, and assertions on the DOM).\nKeep styling clean and minimal — a single plain CSS file is fine.\nBegin every source file you create with a first-line comment exactly of the form:\n// GENERATED BY NAPL from <prompt filename> — edit the prompt, not this file\n(use the comment syntax of the file: // for TS/TSX, /* ... */ for CSS),\nsubstituting the driving prompt file name.\nEnsure \"npx vitest run\" passes from this directory before finishing.";

const RUST_IDIOM: &str = "Target: a Rust library crate tested with `cargo test`.\nThe working directory is a Cargo WORKSPACE whose root `Cargo.toml` is written and\nowned by the toolchain — DO NOT create, edit, or delete the workspace-root\n`Cargo.toml`, and do not add a `[workspace]` section of your own.\nCreate this module as its own member crate in a subdirectory named EXACTLY after\nthe module (see the \"Module:\" line below): `<module>/Cargo.toml` (a [package]\nsection whose name is the module name, with an edition) and `<module>/src/lib.rs`\nas the entry point. Touch only files under `<module>/`; leave every sibling module\ncrate untouched. Add no external dependencies unless the described behavior\ngenuinely requires one.\nWrite idiomatic, modern Rust. Prefer free functions and plain data structs; never\nintroduce a trait or an inherent-impl method when a free function suffices.\nExpose the public API as `pub` items with clear names, matching any names the prompt states.\nCo-locate a `#[cfg(test)] mod tests` unit suite that asserts every described behavior.\nBegin every source file you create with a first-line comment exactly of the form:\n// GENERATED BY NAPL from <prompt filename> — edit the prompt, not this file\nsubstituting the driving prompt file name.\nEnsure `cargo test` passes from the workspace root before finishing.";

fn rust_exclude_dirs() -> Vec<String> {
    ["target", ".git"].iter().map(ToString::to_string).collect()
}

fn rust_exclude_files() -> Vec<String> {
    ["Cargo.lock", "AGENTS.md", "CLAUDE.md"]
        .iter()
        .map(ToString::to_string)
        .collect()
}

fn typescript_adapter() -> TargetAdapter {
    TargetAdapter {
        name: "typescript",
        idiom_guidance: TYPESCRIPT_IDIOM.to_string(),
        agent_tools: base_agent_tools(),
        attribution_exclude_dirs: base_exclude_dirs(),
        attribution_exclude_files: base_exclude_files(),
        attribution_exclude_root_files: Vec::new(),
        attribution_exclude_suffixes: base_exclude_suffixes(),
        test_command_label: "npx vitest run",
        test_run: vitest_run(),
        workspace_layout: false,
    }
}

fn rust_adapter() -> TargetAdapter {
    TargetAdapter {
        name: "rust",
        idiom_guidance: RUST_IDIOM.to_string(),
        agent_tools: rust_agent_tools(),
        attribution_exclude_dirs: rust_exclude_dirs(),
        attribution_exclude_files: rust_exclude_files(),
        attribution_exclude_root_files: vec!["Cargo.toml".to_string()],
        attribution_exclude_suffixes: Vec::new(),
        test_command_label: "cargo test",
        test_run: cargo_test(),
        workspace_layout: true,
    }
}

fn react_adapter() -> TargetAdapter {
    let mut exclude_files = base_exclude_files();
    exclude_files.push("vite.config.js".to_string());
    TargetAdapter {
        name: "react",
        idiom_guidance: REACT_IDIOM.to_string(),
        agent_tools: base_agent_tools(),
        attribution_exclude_dirs: base_exclude_dirs(),
        attribution_exclude_files: exclude_files,
        attribution_exclude_root_files: Vec::new(),
        attribution_exclude_suffixes: base_exclude_suffixes(),
        test_command_label: "npx vitest run",
        test_run: vitest_run(),
        workspace_layout: false,
    }
}

/// The registered target names, in registry order.
#[must_use]
pub fn list_targets() -> Vec<&'static str> {
    vec!["typescript", "react", "rust"]
}

/// The targets whose guard directory `napl init` pre-creates for the starter
/// project. Any registered target's guard docs are (re)written on its first
/// `napl gen`, so a target absent here is still fully usable — it is simply not
/// scaffolded up front.
#[must_use]
pub fn starter_targets() -> Vec<&'static str> {
    vec!["typescript", "react"]
}

/// Look up a target adapter by name, mirroring `getAdapter`.
///
/// # Errors
/// Returns the `unknown target` message when the name is not registered.
pub fn get_adapter(name: &str) -> Result<TargetAdapter, String> {
    match name {
        "typescript" => Ok(typescript_adapter()),
        "react" => Ok(react_adapter()),
        "rust" => Ok(rust_adapter()),
        _ => Err(format!(
            "unknown target '{name}'. Available targets: {}",
            list_targets().join(", ")
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lists_registered_targets() {
        assert_eq!(list_targets(), vec!["typescript", "react", "rust"]);
    }

    #[test]
    fn starter_targets_are_a_subset_of_registered() {
        assert_eq!(starter_targets(), vec!["typescript", "react"]);
        for target in starter_targets() {
            assert!(list_targets().contains(&target));
        }
    }

    #[test]
    fn typescript_adapter_shape() {
        let adapter = get_adapter("typescript").unwrap();
        assert_eq!(adapter.name, "typescript");
        assert_eq!(adapter.test_command_label, "npx vitest run");
        assert_eq!(adapter.test_command("/x").args, vec!["vitest", "run"]);
        assert!(adapter.agent_tools.contains(&"Read".to_string()));
        assert!(!adapter
            .attribution_exclude_files
            .contains(&"vite.config.js".to_string()));
    }

    #[test]
    fn react_adapter_excludes_vite_config_js() {
        let adapter = get_adapter("react").unwrap();
        assert!(adapter
            .attribution_exclude_files
            .contains(&"vite.config.js".to_string()));
    }

    #[test]
    fn rust_adapter_shape() {
        let adapter = get_adapter("rust").unwrap();
        assert_eq!(adapter.name, "rust");
        assert_eq!(adapter.test_command_label, "cargo test");
        assert_eq!(adapter.test_command("/x").command, "cargo");
        assert_eq!(adapter.test_command("/x").args, vec!["test"]);
        assert!(adapter.agent_tools.contains(&"Bash(cargo:*)".to_string()));
        assert!(!adapter.agent_tools.contains(&"Bash(npx:*)".to_string()));
        assert!(adapter
            .attribution_exclude_dirs
            .contains(&"target".to_string()));
        assert!(adapter
            .attribution_exclude_files
            .contains(&"Cargo.lock".to_string()));
    }

    #[test]
    fn rust_adapter_is_a_workspace_with_root_manifest_excluded() {
        let adapter = get_adapter("rust").unwrap();
        assert!(adapter.workspace_layout);
        assert!(adapter
            .attribution_exclude_root_files
            .contains(&"Cargo.toml".to_string()));
        assert!(adapter.idiom_guidance.contains("Cargo WORKSPACE"));
    }

    #[test]
    fn single_package_targets_are_not_workspaces() {
        for name in ["typescript", "react"] {
            let adapter = get_adapter(name).unwrap();
            assert!(!adapter.workspace_layout);
            assert!(adapter.attribution_exclude_root_files.is_empty());
        }
    }

    #[test]
    fn workspace_manifest_lists_members_deterministically() {
        let manifest = workspace_manifest_toml(&[
            "body_lines".to_string(),
            "extensions".to_string(),
            "hash".to_string(),
        ]);
        assert!(manifest.contains("[workspace]"));
        assert!(manifest.contains("resolver = \"2\""));
        assert!(manifest.contains("    \"body_lines\",\n"));
        assert!(manifest.contains("    \"extensions\",\n"));
        assert!(manifest.contains("    \"hash\",\n"));
        assert_eq!(manifest, workspace_manifest_toml(&[
            "body_lines".to_string(),
            "extensions".to_string(),
            "hash".to_string(),
        ]));
    }

    #[test]
    fn workspace_manifest_empty_members() {
        let manifest = workspace_manifest_toml(&[]);
        assert!(manifest.contains("members = [\n]\n"));
    }

    #[test]
    fn unknown_target_errors() {
        let err = get_adapter("cobol").unwrap_err();
        assert!(err.contains("unknown target 'cobol'"));
        assert!(err.contains("typescript, react, rust"));
    }
}
