//! Target adapters: per-language configuration for generation, testing, and
//! attribution filtering. Pure data, mirroring the TypeScript target registry.

/// A target's test invocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TestRunCommand {
    /// The executable to run.
    pub command: String,
    /// Its arguments.
    pub args: Vec<String>,
}

/// Per-target configuration consumed by `gen`/`test`.
#[derive(Debug, Clone)]
pub struct TargetAdapter {
    /// The target name (also the src subdirectory).
    pub name: &'static str,
    /// Idiom guidance injected into the coding-agent task.
    pub idiom_guidance: String,
    /// Tools the coding agent is allowed to use.
    pub agent_tools: Vec<String>,
    /// Directory names excluded from attribution snapshots.
    pub attribution_exclude_dirs: Vec<String>,
    /// File names excluded from attribution snapshots.
    pub attribution_exclude_files: Vec<String>,
    /// File suffixes excluded from attribution snapshots.
    pub attribution_exclude_suffixes: Vec<String>,
    /// Human-facing label for the test command.
    pub test_command_label: &'static str,
}

impl TargetAdapter {
    /// The test command to run in `target_dir` (both adapters ignore it).
    #[must_use]
    pub fn test_command(&self, _target_dir: &str) -> TestRunCommand {
        TestRunCommand {
            command: "npx".to_string(),
            args: vec!["vitest".to_string(), "run".to_string()],
        }
    }
}

fn base_agent_tools() -> Vec<String> {
    [
        "Read",
        "Edit",
        "Write",
        "Bash(npm:*)",
        "Bash(npx:*)",
        "Bash(node:*)",
        "Bash(mkdir:*)",
        "Bash(ls:*)",
        "Bash(cat:*)",
        "Bash(rm:*)",
        "Bash(mv:*)",
        "Bash(cp:*)",
        "Bash(touch:*)",
        "Bash(echo:*)",
        "Bash(sed:*)",
    ]
    .iter()
    .map(ToString::to_string)
    .collect()
}

fn base_exclude_dirs() -> Vec<String> {
    ["node_modules", "dist", ".git", "build", "coverage", ".vite"]
        .iter()
        .map(ToString::to_string)
        .collect()
}

fn base_exclude_files() -> Vec<String> {
    ["package-lock.json", "AGENTS.md", "CLAUDE.md"]
        .iter()
        .map(ToString::to_string)
        .collect()
}

fn base_exclude_suffixes() -> Vec<String> {
    [".tsbuildinfo", ".d.ts"]
        .iter()
        .map(ToString::to_string)
        .collect()
}

const TYPESCRIPT_IDIOM: &str = "Target: a TypeScript library package (ESM, strict mode) tested with vitest.\nIf the workspace has no package.json, scaffold one in place: a \"type\": \"module\" package,\nadd vitest and typescript as devDependencies, add a \"test\" script running \"vitest run\",\nand run \"npm install\".\nWrite idiomatic, modern TypeScript. Use named exports only — never default exports.\nPrefer plain functions; never introduce a class when a function suffices.\nCo-locate a *.test.ts vitest suite that asserts the described behavior.\nBegin every source file you create with a first-line comment exactly of the form:\n// GENERATED BY NAPL from <prompt filename> — edit the prompt, not this file\nsubstituting the driving prompt file name.\nEnsure \"npx vitest run\" passes from this directory before finishing.";

const REACT_IDIOM: &str = "Target: a React single-page app built with Vite + React + TypeScript.\nIf the workspace is empty, scaffold a Vite React + TypeScript project in place:\npackage.json, index.html, vite.config.ts, tsconfig.json, tsconfig.node.json,\nsrc/main.tsx and src/App.tsx — then run \"npm install\".\nUse function components and hooks only — never class components.\nUse named exports for your own modules and keep components small and composable.\nAdd test tooling: vitest, @testing-library/react, @testing-library/jest-dom, jsdom.\nConfigure vitest to use the \"jsdom\" environment (test.environment) and a setup file\nthat imports \"@testing-library/jest-dom\" — put this in vite.config.ts or vitest.config.ts.\nWrite component tests with @testing-library/react that exercise every described behavior\n(rendering, user events via fireEvent/userEvent, and assertions on the DOM).\nKeep styling clean and minimal — a single plain CSS file is fine.\nBegin every source file you create with a first-line comment exactly of the form:\n// GENERATED BY NAPL from <prompt filename> — edit the prompt, not this file\n(use the comment syntax of the file: // for TS/TSX, /* ... */ for CSS),\nsubstituting the driving prompt file name.\nEnsure \"npx vitest run\" passes from this directory before finishing.";

fn typescript_adapter() -> TargetAdapter {
    TargetAdapter {
        name: "typescript",
        idiom_guidance: TYPESCRIPT_IDIOM.to_string(),
        agent_tools: base_agent_tools(),
        attribution_exclude_dirs: base_exclude_dirs(),
        attribution_exclude_files: base_exclude_files(),
        attribution_exclude_suffixes: base_exclude_suffixes(),
        test_command_label: "npx vitest run",
    }
}

fn react_adapter() -> TargetAdapter {
    let mut exclude_files = base_exclude_files();
    exclude_files.push("vite.config.js".to_string());
    TargetAdapter {
        name: "react",
        idiom_guidance: REACT_IDIOM.to_string(),
        agent_tools: base_agent_tools(),
        attribution_exclude_dirs: base_exclude_dirs(),
        attribution_exclude_files: exclude_files,
        attribution_exclude_suffixes: base_exclude_suffixes(),
        test_command_label: "npx vitest run",
    }
}

/// The registered target names, in registry order.
#[must_use]
pub fn list_targets() -> Vec<&'static str> {
    vec!["typescript", "react"]
}

/// Look up a target adapter by name, mirroring `getAdapter`.
///
/// # Errors
/// Returns the `unknown target` message when the name is not registered.
pub fn get_adapter(name: &str) -> Result<TargetAdapter, String> {
    match name {
        "typescript" => Ok(typescript_adapter()),
        "react" => Ok(react_adapter()),
        _ => Err(format!(
            "unknown target '{name}'. Available targets: {}",
            list_targets().join(", ")
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lists_registered_targets() {
        assert_eq!(list_targets(), vec!["typescript", "react"]);
    }

    #[test]
    fn typescript_adapter_shape() {
        let adapter = get_adapter("typescript").unwrap();
        assert_eq!(adapter.name, "typescript");
        assert_eq!(adapter.test_command_label, "npx vitest run");
        assert_eq!(adapter.test_command("/x").args, vec!["vitest", "run"]);
        assert!(adapter.agent_tools.contains(&"Read".to_string()));
        assert!(!adapter
            .attribution_exclude_files
            .contains(&"vite.config.js".to_string()));
    }

    #[test]
    fn react_adapter_excludes_vite_config_js() {
        let adapter = get_adapter("react").unwrap();
        assert!(adapter
            .attribution_exclude_files
            .contains(&"vite.config.js".to_string()));
    }

    #[test]
    fn unknown_target_errors() {
        let err = get_adapter("cobol").unwrap_err();
        assert!(err.contains("unknown target 'cobol'"));
        assert!(err.contains("typescript, react"));
    }
}
