import { existsSync, statSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

export const GUARD_DOC = `Files in this tree are GENERATED by NAPL from the .napl prompt files in the project root. Do not edit them directly — edit the prompts and run napl gen. Direct edits are detected as DRIFT and block compilation.
`;

export const GUARD_FILE_NAMES = ['AGENTS.md', 'CLAUDE.md'] as const;

export async function writeGuardFiles(targetDir: string): Promise<void> {
  await mkdir(targetDir, { recursive: true });
  for (const name of GUARD_FILE_NAMES) {
    await writeFile(join(targetDir, name), GUARD_DOC, 'utf8');
  }
}

export const PRE_COMMIT_HOOK = `#!/bin/sh
if ! napl status; then
	echo "napl: commit blocked — generated code has drifted from its prompts (see above)." >&2
	echo "napl: to commit anyway (work in progress), run: git commit --no-verify" >&2
	exit 1
fi
`;

export const PRE_COMMIT_HOOK_LINE = 'napl status';

export function findGitDir(root: string): string | null {
  let dir = root;
  for (;;) {
    const candidate = join(dir, '.git');
    if (existsSync(candidate) && statSync(candidate).isDirectory()) return candidate;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

export const NAPL_DENY_RULES = ['Edit(/.napl/src/**)'] as const;

export const CLAUDE_SETTINGS_SNIPPET = `${JSON.stringify({ permissions: { deny: [...NAPL_DENY_RULES] } }, null, 2)}
`;

export type SettingsMergeAction = 'create' | 'update' | 'unchanged' | 'manual';

export interface SettingsMergeResult {
  action: SettingsMergeAction;
  content: string | null;
  added: string[];
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export function mergeClaudeSettings(existing: string | null): SettingsMergeResult {
  if (existing === null) {
    return { action: 'create', content: CLAUDE_SETTINGS_SNIPPET, added: [...NAPL_DENY_RULES] };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(existing);
  } catch {
    return { action: 'manual', content: null, added: [] };
  }
  if (!isPlainObject(parsed)) return { action: 'manual', content: null, added: [] };

  const permissions = parsed.permissions;
  if (permissions !== undefined && !isPlainObject(permissions)) {
    return { action: 'manual', content: null, added: [] };
  }
  const permObject: Record<string, unknown> = isPlainObject(permissions) ? { ...permissions } : {};
  const deny = permObject.deny;
  if (deny !== undefined && !Array.isArray(deny)) return { action: 'manual', content: null, added: [] };
  const denyArray: unknown[] = Array.isArray(deny) ? [...deny] : [];

  const added: string[] = [];
  for (const rule of NAPL_DENY_RULES) {
    if (!denyArray.includes(rule)) {
      denyArray.push(rule);
      added.push(rule);
    }
  }
  if (added.length === 0) return { action: 'unchanged', content: null, added: [] };

  const merged = { ...parsed, permissions: { ...permObject, deny: denyArray } };
  return { action: 'update', content: `${JSON.stringify(merged, null, 2)}\n`, added };
}
