import { mkdtemp, mkdir, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  GUARD_DOC,
  GUARD_FILE_NAMES,
  NAPL_DENY_RULES,
  PRE_COMMIT_HOOK,
  findGitDir,
  mergeClaudeSettings,
  writeGuardFiles,
} from '../src/core/guard.js';

let dir: string;

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), 'napl-guard-'));
});

afterEach(async () => {
  await rm(dir, { recursive: true, force: true });
});

describe('writeGuardFiles', () => {
  it('writes AGENTS.md and CLAUDE.md with the identical guard notice', async () => {
    const target = join(dir, 'src', 'typescript');
    await writeGuardFiles(target);
    for (const name of GUARD_FILE_NAMES) {
      const content = await readFile(join(target, name), 'utf8');
      expect(content).toBe(GUARD_DOC);
      expect(content).toContain('GENERATED by NAPL');
      expect(content).toContain('block compilation');
    }
  });
});

describe('findGitDir', () => {
  it('returns null when no .git exists in or above the root', () => {
    expect(findGitDir(dir)).toBeNull();
  });

  it('finds a .git directory at the root', async () => {
    await mkdir(join(dir, '.git'), { recursive: true });
    expect(findGitDir(dir)).toBe(join(dir, '.git'));
  });

  it('finds a .git directory in a parent', async () => {
    await mkdir(join(dir, '.git'), { recursive: true });
    const nested = join(dir, 'a', 'b');
    await mkdir(nested, { recursive: true });
    expect(findGitDir(nested)).toBe(join(dir, '.git'));
  });
});

describe('PRE_COMMIT_HOOK', () => {
  it('is a POSIX sh hook that runs napl status and offers the --no-verify escape hatch', () => {
    expect(PRE_COMMIT_HOOK.startsWith('#!/bin/sh')).toBe(true);
    expect(PRE_COMMIT_HOOK).toContain('napl status');
    expect(PRE_COMMIT_HOOK).toContain('git commit --no-verify');
  });
});

describe('mergeClaudeSettings', () => {
  it('creates a fresh settings file with the deny rule when none exists', () => {
    const result = mergeClaudeSettings(null);
    expect(result.action).toBe('create');
    expect(result.content).not.toBeNull();
    const parsed = JSON.parse(result.content ?? '{}');
    expect(parsed.permissions.deny).toEqual([...NAPL_DENY_RULES]);
    expect(NAPL_DENY_RULES[0]).toBe('Edit(/.napl/src/**)');
  });

  it('adds the deny rule to an existing file that has no permissions block, preserving other keys', () => {
    const existing = JSON.stringify({ model: 'opus', env: { FOO: 'bar' } }, null, 2);
    const result = mergeClaudeSettings(existing);
    expect(result.action).toBe('update');
    const parsed = JSON.parse(result.content ?? '{}');
    expect(parsed.model).toBe('opus');
    expect(parsed.env.FOO).toBe('bar');
    expect(parsed.permissions.deny).toEqual([...NAPL_DENY_RULES]);
  });

  it('merges into an existing permissions.deny array, keeping prior rules', () => {
    const existing = JSON.stringify({ permissions: { allow: ['Bash(ls)'], deny: ['Read(./.env)'] } }, null, 2);
    const result = mergeClaudeSettings(existing);
    expect(result.action).toBe('update');
    const parsed = JSON.parse(result.content ?? '{}');
    expect(parsed.permissions.allow).toEqual(['Bash(ls)']);
    expect(parsed.permissions.deny).toEqual(['Read(./.env)', ...NAPL_DENY_RULES]);
  });

  it('reports unchanged when the deny rule is already present', () => {
    const existing = JSON.stringify({ permissions: { deny: [...NAPL_DENY_RULES] } }, null, 2);
    const result = mergeClaudeSettings(existing);
    expect(result.action).toBe('unchanged');
    expect(result.content).toBeNull();
  });

  it('defers to a manual edit when the file is not valid JSON', () => {
    const result = mergeClaudeSettings('{ not json');
    expect(result.action).toBe('manual');
    expect(result.content).toBeNull();
  });

  it('defers to a manual edit when permissions.deny is not an array', () => {
    const result = mergeClaudeSettings(JSON.stringify({ permissions: { deny: 'nope' } }));
    expect(result.action).toBe('manual');
  });
});
