// GENERATED BY NAPL from discovery_core.napl — edit the prompt, not this file
//
// Location-free prompt identity: the pure decisions.
//
// A NAPL prompt is identified by its frontmatter `module` name, never by its
// path on disk. This module carries the pure decisions the CLI's discovery shell
// makes over prompt files it has already read: reading a prompt's declared member
// crate, rejecting two prompts that declare the same module, and building the
// `module -> current path` index. The filesystem walk and reads stay in the
// hand-written shell; this module receives already-read
// `(raw_contents, relative_path)` pairs and decides. No filesystem, no
// environment.

use std::collections::BTreeMap;

use schemas_frontmatter::parse_frontmatter;

/// Parse the prompt's frontmatter and return its declared member crate.
///
/// `crate: shared` yields `Some("shared")`; an absent `crate` key yields `None`;
/// frontmatter that fails to parse yields `None` (a prompt whose frontmatter does
/// not parse carries no usable identity).
pub fn declared_crate(raw: &str) -> Option<String> {
    parse_frontmatter(raw).ok()?.frontmatter.crate_name
}

/// Walk `(raw_contents, relative_path)` pairs in discovery order and detect the
/// first module declared by two prompts.
///
/// Prompts whose frontmatter fails to parse are skipped (their parse error is
/// surfaced elsewhere). The first relative path seen for each module is recorded;
/// the moment a module name is seen a second time, the error message below is
/// returned and the walk stops. If no module repeats, returns `None`.
///
/// Identity is the module, so a copied prompt must be renamed in the copy — two
/// prompts sharing a module is a hard error, never a silent fork.
pub fn find_duplicate_module(files: &[(String, String)]) -> Option<String> {
    let mut first_path_by_module: BTreeMap<String, &str> = BTreeMap::new();

    for (raw, relative_path) in files {
        let Ok(parsed) = parse_frontmatter(raw) else {
            continue;
        };
        let module = parsed.frontmatter.module;

        if let Some(existing) = first_path_by_module.get(&module) {
            return Some(format!(
                "duplicate module '{module}' is declared by two prompts: {existing} and {new}. \
                 Copied a prompt? Rename the module in the copy.",
                new = relative_path,
            ));
        }

        first_path_by_module.insert(module, relative_path);
    }

    None
}

/// Build the derived `module -> relative_path` index.
///
/// Each tuple is `(raw_contents, relative_path)`. Parse each prompt's
/// frontmatter, skipping any that fails to parse, and insert
/// `module -> relative_path` into a `BTreeMap`. When two files declare the same
/// module (the caller has already rejected that via `find_duplicate_module`), a
/// later entry overwrites an earlier one. This is how a prompt's location is
/// resolved now that identity is keyed by module and no path is stored: the path
/// is always the one found on disk this run.
pub fn module_paths_from(files: &[(String, String)]) -> BTreeMap<String, String> {
    let mut index = BTreeMap::new();

    for (raw, relative_path) in files {
        if let Ok(parsed) = parse_frontmatter(raw) {
            index.insert(parsed.frontmatter.module, relative_path.clone());
        }
    }

    index
}

#[cfg(test)]
mod tests {
    use super::*;

    fn prompt(module: &str) -> String {
        format!("---\nmodule: {module}\n---\nBody.\n")
    }

    // --- declared_crate ---------------------------------------------------

    #[test]
    fn declared_crate_returns_the_crate_key() {
        let raw = "---\nmodule: alpha\ncrate: shared\n---\nBody.\n";
        assert_eq!(declared_crate(raw), Some("shared".to_string()));
    }

    #[test]
    fn declared_crate_is_none_when_key_absent() {
        let raw = "---\nmodule: alpha\n---\nBody.\n";
        assert_eq!(declared_crate(raw), None);
    }

    #[test]
    fn declared_crate_is_none_when_frontmatter_unparseable() {
        assert_eq!(declared_crate("no frontmatter here"), None);
    }

    #[test]
    fn declared_crate_is_none_when_module_missing() {
        // Frontmatter without a `module` fails to parse -> no usable identity.
        let raw = "---\ncrate: shared\n---\nBody.\n";
        assert_eq!(declared_crate(raw), None);
    }

    // --- find_duplicate_module -------------------------------------------

    #[test]
    fn no_duplicate_returns_none() {
        let files = vec![
            (prompt("alpha"), "a.napl".to_string()),
            (prompt("beta"), "b.napl".to_string()),
            (prompt("gamma"), "c.napl".to_string()),
        ];
        assert_eq!(find_duplicate_module(&files), None);
    }

    #[test]
    fn duplicate_reports_first_and_second_path() {
        let files = vec![
            (prompt("alpha"), "src/a.napl".to_string()),
            (prompt("beta"), "src/b.napl".to_string()),
            (prompt("alpha"), "copy/a.napl".to_string()),
        ];
        assert_eq!(
            find_duplicate_module(&files),
            Some(
                "duplicate module 'alpha' is declared by two prompts: src/a.napl and copy/a.napl. \
                 Copied a prompt? Rename the module in the copy."
                    .to_string()
            )
        );
    }

    #[test]
    fn duplicate_stops_at_first_repeat() {
        // The second `alpha` (idx 2) triggers; the later `beta` repeat is never
        // reached, proving the walk stops at the first duplicate.
        let files = vec![
            (prompt("alpha"), "first.napl".to_string()),
            (prompt("beta"), "b1.napl".to_string()),
            (prompt("alpha"), "second.napl".to_string()),
            (prompt("beta"), "b2.napl".to_string()),
        ];
        let msg = find_duplicate_module(&files).expect("should detect duplicate");
        assert!(msg.contains("duplicate module 'alpha'"));
        assert!(msg.contains("first.napl and second.napl"));
    }

    #[test]
    fn unparseable_prompts_are_skipped_not_matched() {
        // Two unparseable entries must not be treated as a shared (empty) module.
        let files = vec![
            ("garbage one".to_string(), "x.napl".to_string()),
            ("garbage two".to_string(), "y.napl".to_string()),
            (prompt("alpha"), "a.napl".to_string()),
        ];
        assert_eq!(find_duplicate_module(&files), None);
    }

    #[test]
    fn unparseable_does_not_reserve_a_module_name() {
        let files = vec![
            (prompt("alpha"), "a.napl".to_string()),
            ("garbage".to_string(), "bad.napl".to_string()),
            (prompt("alpha"), "dup.napl".to_string()),
        ];
        let msg = find_duplicate_module(&files).expect("should detect duplicate");
        assert!(msg.contains("a.napl and dup.napl"));
    }

    #[test]
    fn empty_input_has_no_duplicate() {
        assert_eq!(find_duplicate_module(&[]), None);
    }

    // --- module_paths_from -----------------------------------------------

    #[test]
    fn builds_module_to_path_index() {
        let files = vec![
            (prompt("alpha"), "a.napl".to_string()),
            (prompt("beta"), "b.napl".to_string()),
        ];
        let index = module_paths_from(&files);
        assert_eq!(index.len(), 2);
        assert_eq!(index.get("alpha"), Some(&"a.napl".to_string()));
        assert_eq!(index.get("beta"), Some(&"b.napl".to_string()));
    }

    #[test]
    fn later_entry_overwrites_earlier_for_same_module() {
        let files = vec![
            (prompt("alpha"), "old.napl".to_string()),
            (prompt("alpha"), "new.napl".to_string()),
        ];
        let index = module_paths_from(&files);
        assert_eq!(index.len(), 1);
        assert_eq!(index.get("alpha"), Some(&"new.napl".to_string()));
    }

    #[test]
    fn unparseable_prompts_are_omitted_from_index() {
        let files = vec![
            (prompt("alpha"), "a.napl".to_string()),
            ("garbage".to_string(), "bad.napl".to_string()),
        ];
        let index = module_paths_from(&files);
        assert_eq!(index.len(), 1);
        assert_eq!(index.get("alpha"), Some(&"a.napl".to_string()));
    }

    #[test]
    fn empty_input_yields_empty_index() {
        assert!(module_paths_from(&[]).is_empty());
    }
}
