// GENERATED BY NAPL from targets.napl — edit the prompt, not this file

/// A test invocation: an executable and its arguments.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TestRunCommand {
    pub command: String,
    pub args: Vec<String>,
}

/// Per-language target adapter: idiom guidance, agent tools, attribution
/// exclusion rules, and the test command that gates generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TargetAdapter {
    pub name: &'static str,
    pub idiom_guidance: String,
    pub agent_tools: Vec<String>,
    pub attribution_exclude_dirs: Vec<String>,
    pub attribution_exclude_files: Vec<String>,
    pub attribution_exclude_root_files: Vec<String>,
    pub attribution_exclude_suffixes: Vec<String>,
    pub test_command_label: &'static str,
    pub test_run: TestRunCommand,
    pub workspace_layout: bool,
}

impl TargetAdapter {
    /// The test invocation that gates generation for this target. The
    /// command is fixed per target; `target_dir` is accepted but not
    /// consulted.
    pub fn test_command(&self, _target_dir: &str) -> TestRunCommand {
        self.test_run.clone()
    }
}

fn strings(items: &[&str]) -> Vec<String> {
    items.iter().map(|s| s.to_string()).collect()
}

fn typescript_adapter() -> TargetAdapter {
    TargetAdapter {
        name: "typescript",
        idiom_guidance: "Target: a TypeScript library tested with `npx vitest run`. \
            Write idiomatic, modern TypeScript with named exports."
            .to_string(),
        agent_tools: strings(&[
            "Read",
            "Write",
            "Edit",
            "Bash(npm:*)",
            "Bash(npx:*)",
            "Bash(node:*)",
        ]),
        attribution_exclude_dirs: strings(&[
            "node_modules",
            "dist",
            ".git",
            "build",
            "coverage",
            ".vite",
        ]),
        attribution_exclude_files: strings(&["package-lock.json", "AGENTS.md", "CLAUDE.md"]),
        attribution_exclude_root_files: Vec::new(),
        attribution_exclude_suffixes: strings(&[".tsbuildinfo", ".d.ts"]),
        test_command_label: "npx vitest run",
        test_run: TestRunCommand {
            command: "npx".to_string(),
            args: strings(&["vitest", "run"]),
        },
        workspace_layout: false,
    }
}

fn react_adapter() -> TargetAdapter {
    let mut adapter = typescript_adapter();
    adapter.name = "react";
    adapter.idiom_guidance = "Target: a React component library tested with `npx vitest run`. \
        Write idiomatic, modern React with function components and hooks."
        .to_string();
    adapter
        .attribution_exclude_files
        .push("vite.config.js".to_string());
    adapter
}

fn rust_adapter() -> TargetAdapter {
    TargetAdapter {
        name: "rust",
        idiom_guidance: "Target: a Rust library crate tested with `cargo test`. \
            The working directory is a Cargo WORKSPACE whose root `Cargo.toml` is \
            written and owned by the toolchain — do not create, edit, or delete it. \
            Write idiomatic, modern Rust."
            .to_string(),
        agent_tools: strings(&[
            "Read",
            "Write",
            "Edit",
            "Bash(cargo:*)",
            "Bash(rustc:*)",
            "Bash(rustfmt:*)",
        ]),
        attribution_exclude_dirs: strings(&["target", ".git"]),
        attribution_exclude_files: strings(&["Cargo.lock", "AGENTS.md", "CLAUDE.md"]),
        attribution_exclude_root_files: strings(&["Cargo.toml"]),
        attribution_exclude_suffixes: Vec::new(),
        test_command_label: "cargo test",
        test_run: TestRunCommand {
            command: "cargo".to_string(),
            args: strings(&["test"]),
        },
        workspace_layout: true,
    }
}

fn registry() -> Vec<TargetAdapter> {
    vec![typescript_adapter(), react_adapter(), rust_adapter()]
}

/// Registered target names, in registry order.
pub fn list_targets() -> Vec<&'static str> {
    registry().into_iter().map(|adapter| adapter.name).collect()
}

/// Targets whose guard directory `napl init` pre-creates — a subset of the
/// registered set.
pub fn starter_targets() -> Vec<&'static str> {
    vec!["typescript", "react"]
}

/// Look up an adapter by name.
pub fn get_adapter(name: &str) -> Result<TargetAdapter, String> {
    registry()
        .into_iter()
        .find(|adapter| adapter.name == name)
        .ok_or_else(|| {
            format!(
                "unknown target '{}'. Available targets: {}",
                name,
                list_targets().join(", ")
            )
        })
}

/// Render the workspace root `Cargo.toml` for a Cargo-workspace target.
/// Deterministic: the same member slice always yields byte-identical output.
pub fn workspace_manifest_toml(members: &[String]) -> String {
    let mut out = String::new();
    out.push_str("[workspace]\n");
    out.push_str("resolver = \"2\"\n");
    out.push_str("members = [\n");
    for member in members {
        out.push_str(&format!("    \"{member}\",\n"));
    }
    out.push_str("]\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn list_targets_is_registry_order() {
        assert_eq!(list_targets(), vec!["typescript", "react", "rust"]);
    }

    #[test]
    fn starter_targets_is_subset() {
        let starters = starter_targets();
        assert_eq!(starters, vec!["typescript", "react"]);
        let all = list_targets();
        for starter in &starters {
            assert!(all.contains(starter));
        }
        assert!(!starters.contains(&"rust"));
    }

    #[test]
    fn get_adapter_returns_known_targets() {
        assert_eq!(get_adapter("typescript").unwrap().name, "typescript");
        assert_eq!(get_adapter("react").unwrap().name, "react");
        assert_eq!(get_adapter("rust").unwrap().name, "rust");
    }

    #[test]
    fn get_adapter_errors_on_unknown_target() {
        let err = get_adapter("cobol").unwrap_err();
        assert!(err.contains("unknown target 'cobol'"));
        assert!(err.contains("typescript, react, rust"));
    }

    #[test]
    fn typescript_adapter_shape() {
        let adapter = get_adapter("typescript").unwrap();
        assert_eq!(adapter.test_command_label, "npx vitest run");
        assert_eq!(
            adapter.test_run,
            TestRunCommand {
                command: "npx".to_string(),
                args: strings(&["vitest", "run"]),
            }
        );
        assert!(adapter.agent_tools.contains(&"Read".to_string()));
        for dir in ["node_modules", "dist", ".git", "build", "coverage", ".vite"] {
            assert!(adapter.attribution_exclude_dirs.contains(&dir.to_string()));
        }
        for file in ["package-lock.json", "AGENTS.md", "CLAUDE.md"] {
            assert!(adapter.attribution_exclude_files.contains(&file.to_string()));
        }
        assert!(!adapter
            .attribution_exclude_files
            .contains(&"vite.config.js".to_string()));
        for suffix in [".tsbuildinfo", ".d.ts"] {
            assert!(adapter
                .attribution_exclude_suffixes
                .contains(&suffix.to_string()));
        }
        assert!(!adapter.workspace_layout);
        assert!(adapter.attribution_exclude_root_files.is_empty());
    }

    #[test]
    fn react_adapter_shape() {
        let adapter = get_adapter("react").unwrap();
        assert_eq!(adapter.test_command_label, "npx vitest run");
        assert_eq!(
            adapter.test_run,
            TestRunCommand {
                command: "npx".to_string(),
                args: strings(&["vitest", "run"]),
            }
        );
        assert!(adapter.agent_tools.contains(&"Read".to_string()));
        for dir in ["node_modules", "dist", ".git", "build", "coverage", ".vite"] {
            assert!(adapter.attribution_exclude_dirs.contains(&dir.to_string()));
        }
        for file in [
            "package-lock.json",
            "AGENTS.md",
            "CLAUDE.md",
            "vite.config.js",
        ] {
            assert!(adapter.attribution_exclude_files.contains(&file.to_string()));
        }
        assert!(!adapter.workspace_layout);
        assert!(adapter.attribution_exclude_root_files.is_empty());
    }

    #[test]
    fn rust_adapter_shape() {
        let adapter = get_adapter("rust").unwrap();
        assert_eq!(adapter.test_command_label, "cargo test");
        assert_eq!(
            adapter.test_run,
            TestRunCommand {
                command: "cargo".to_string(),
                args: strings(&["test"]),
            }
        );
        assert!(adapter.agent_tools.contains(&"Read".to_string()));
        assert!(adapter.agent_tools.contains(&"Bash(cargo:*)".to_string()));
        assert!(!adapter.agent_tools.contains(&"Bash(npx:*)".to_string()));
        assert!(adapter.attribution_exclude_dirs.contains(&"target".to_string()));
        assert!(adapter
            .attribution_exclude_files
            .contains(&"Cargo.lock".to_string()));
        assert!(adapter
            .attribution_exclude_root_files
            .contains(&"Cargo.toml".to_string()));
        assert!(adapter.workspace_layout);
        assert!(adapter.idiom_guidance.contains("Cargo WORKSPACE"));
    }

    #[test]
    fn test_command_ignores_target_dir_argument() {
        let adapter = get_adapter("rust").unwrap();
        assert_eq!(adapter.test_command("anything"), adapter.test_run);
        assert_eq!(adapter.test_command(""), adapter.test_run);
    }

    #[test]
    fn workspace_manifest_toml_lists_members() {
        let members = strings(&["body_lines", "extensions", "hash"]);
        let manifest = workspace_manifest_toml(&members);
        assert!(manifest.contains("[workspace]"));
        assert!(manifest.contains("resolver = \"2\""));
        assert!(manifest.contains("\"body_lines\","));
        assert!(manifest.contains("\"extensions\","));
        assert!(manifest.contains("\"hash\","));
    }

    #[test]
    fn workspace_manifest_toml_is_deterministic() {
        let members = strings(&["a", "b"]);
        assert_eq!(
            workspace_manifest_toml(&members),
            workspace_manifest_toml(&members)
        );
    }

    #[test]
    fn workspace_manifest_toml_empty_members() {
        let manifest = workspace_manifest_toml(&[]);
        assert!(manifest.contains("members = [\n]") || manifest.contains("members = [\n]\n"));
    }
}
