// GENERATED BY NAPL from drift.napl — edit the prompt, not this file

/// Why a generated file is considered drifted.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DriftReason {
    /// The file was edited by hand.
    Edited,
    /// The locked file was deleted.
    Missing,
}

/// A single generated file that has drifted from what the prompt describes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DriftedFile {
    /// Path relative to the project root.
    pub file: String,
    pub reason: DriftReason,
    /// The hash recorded in the map, if known.
    pub expected_hash: Option<String>,
    /// The hash of the current on-disk content, if present.
    pub actual_hash: Option<String>,
    /// The journal-reconstructed baseline content, if recoverable.
    pub baseline: Option<String>,
    /// The current on-disk content, if present.
    pub current: Option<String>,
    /// The baseline-to-current unified diff, if computable.
    pub diff: Option<String>,
}

/// Drift found within a single module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModuleDrift {
    pub module: String,
    pub prompt_file: String,
    pub target: String,
    pub files: Vec<DriftedFile>,
}

fn indent(text: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    text.lines()
        .map(|line| format!("{prefix}{line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn format_drifted_file(file: &DriftedFile) -> Vec<String> {
    let mut lines = Vec::new();
    match file.reason {
        DriftReason::Missing => {
            lines.push(format!(
                "    {} (missing — the locked file was deleted)",
                file.file
            ));
            if let Some(hash) = &file.expected_hash {
                lines.push(format!("      recorded hash: {hash}"));
            }
        }
        DriftReason::Edited => {
            lines.push(format!("    {} (edited by hand)", file.file));
            let has_diff = file
                .diff
                .as_ref()
                .is_some_and(|d| !d.trim().is_empty());
            if has_diff {
                lines.push("      recorded baseline -> current:".to_string());
                lines.push(indent(file.diff.as_ref().unwrap(), 6));
            } else {
                lines.push(
                    "      baseline content is not recoverable from the journal (pre-journal state); comparing hashes only:"
                        .to_string(),
                );
                let recorded = file.expected_hash.as_deref().unwrap_or("(none)");
                let current = file.actual_hash.as_deref().unwrap_or("(none)");
                lines.push(format!("      recorded: {recorded}"));
                lines.push(format!("      current:  {current}"));
            }
        }
    }
    lines
}

/// Formats a guided drift report for the given drifts, blocking `napl gen <target>`.
pub fn format_gen_drift_report(drifts: &[ModuleDrift], target: &str) -> String {
    let mut lines = Vec::new();

    lines.push(format!(
        "BLOCKED  drift detected — cannot run 'napl gen {target}' while generated files have hand edits that are not reflected in any prompt."
    ));
    lines.push(String::new());

    for module in drifts {
        lines.push(format!(
            "  module {} ({}) — {} file(s) drifted (from {}):",
            module.module,
            module.target,
            module.files.len(),
            module.prompt_file
        ));

        for file in &module.files {
            lines.extend(format_drifted_file(file));
        }

        lines.push(String::new());
        lines.push("  Resolve it one of three ways:".to_string());
        lines.push(format!(
            "    1) napl reconcile {}  — fold this edit back into your prompt",
            module.module
        ));
        lines.push(format!(
            "    2) napl gen {} --module {} --force  — discard the edit, the prompt wins",
            module.target, module.module
        ));
        lines.push(format!(
            "    3) edit the prompt to describe the change, then napl gen {}",
            module.target
        ));
        lines.push(String::new());
    }

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn edited_file_with_diff() {
        let drifts = vec![ModuleDrift {
            module: "greeting".to_string(),
            prompt_file: "examples/greeting.napl".to_string(),
            target: "typescript".to_string(),
            files: vec![DriftedFile {
                file: ".napl/src/typescript/greet.ts".to_string(),
                reason: DriftReason::Edited,
                expected_hash: Some("aaa".to_string()),
                actual_hash: Some("bbb".to_string()),
                baseline: Some("hello".to_string()),
                current: Some("hello there".to_string()),
                diff: Some("-hello\n+hello there".to_string()),
            }],
        }];

        let report = format_gen_drift_report(&drifts, "typescript");

        assert!(report.contains("drift detected"));
        assert!(report.contains("module greeting (typescript)"));
        assert!(report.contains(".napl/src/typescript/greet.ts (edited by hand)"));
        assert!(report.contains("recorded baseline -> current:"));
        assert!(report.contains("      -hello"));
        assert!(report.contains("      +hello there"));
        assert!(report.contains("1) napl reconcile greeting"));
        assert!(report.contains("2) napl gen typescript --module greeting --force"));
        assert!(report.contains("3) edit the prompt to describe the change, then napl gen typescript"));
    }

    #[test]
    fn edited_file_without_diff_compares_hashes() {
        let drifts = vec![ModuleDrift {
            module: "greeting".to_string(),
            prompt_file: "examples/greeting.napl".to_string(),
            target: "typescript".to_string(),
            files: vec![DriftedFile {
                file: ".napl/src/typescript/greet.ts".to_string(),
                reason: DriftReason::Edited,
                expected_hash: Some("aaa".to_string()),
                actual_hash: Some("bbb".to_string()),
                baseline: None,
                current: None,
                diff: None,
            }],
        }];

        let report = format_gen_drift_report(&drifts, "typescript");

        assert!(report.contains("comparing hashes only"));
        assert!(report.contains("recorded: aaa"));
        assert!(report.contains("current:  bbb"));
    }

    #[test]
    fn edited_file_with_blank_diff_compares_hashes() {
        let drifts = vec![ModuleDrift {
            module: "greeting".to_string(),
            prompt_file: "examples/greeting.napl".to_string(),
            target: "typescript".to_string(),
            files: vec![DriftedFile {
                file: "greet.ts".to_string(),
                reason: DriftReason::Edited,
                expected_hash: None,
                actual_hash: None,
                baseline: None,
                current: None,
                diff: Some("   \n".to_string()),
            }],
        }];

        let report = format_gen_drift_report(&drifts, "typescript");

        assert!(report.contains("comparing hashes only"));
        assert!(report.contains("recorded: (none)"));
        assert!(report.contains("current:  (none)"));
    }

    #[test]
    fn missing_file_with_hash() {
        let drifts = vec![ModuleDrift {
            module: "greeting".to_string(),
            prompt_file: "examples/greeting.napl".to_string(),
            target: "typescript".to_string(),
            files: vec![DriftedFile {
                file: "gone.ts".to_string(),
                reason: DriftReason::Missing,
                expected_hash: Some("h".to_string()),
                actual_hash: None,
                baseline: None,
                current: None,
                diff: None,
            }],
        }];

        let report = format_gen_drift_report(&drifts, "typescript");

        assert!(report.contains("gone.ts (missing — the locked file was deleted)"));
        assert!(report.contains("recorded hash: h"));
    }

    #[test]
    fn missing_file_without_hash_has_no_recorded_line() {
        let drifts = vec![ModuleDrift {
            module: "greeting".to_string(),
            prompt_file: "examples/greeting.napl".to_string(),
            target: "typescript".to_string(),
            files: vec![DriftedFile {
                file: "gone.ts".to_string(),
                reason: DriftReason::Missing,
                expected_hash: None,
                actual_hash: None,
                baseline: None,
                current: None,
                diff: None,
            }],
        }];

        let report = format_gen_drift_report(&drifts, "typescript");

        assert!(!report.contains("recorded hash:"));
    }

    #[test]
    fn header_and_resolutions_use_target() {
        let drifts = vec![ModuleDrift {
            module: "greeting".to_string(),
            prompt_file: "examples/greeting.napl".to_string(),
            target: "typescript".to_string(),
            files: vec![DriftedFile {
                file: "gone.ts".to_string(),
                reason: DriftReason::Missing,
                expected_hash: None,
                actual_hash: None,
                baseline: None,
                current: None,
                diff: None,
            }],
        }];

        let report = format_gen_drift_report(&drifts, "typescript");

        assert!(report
            .starts_with("BLOCKED  drift detected — cannot run 'napl gen typescript' while generated files have hand edits that are not reflected in any prompt.\n\n"));
    }

    #[test]
    fn multiple_modules_each_get_full_block() {
        let make = |module: &str| ModuleDrift {
            module: module.to_string(),
            prompt_file: format!("examples/{module}.napl"),
            target: "typescript".to_string(),
            files: vec![DriftedFile {
                file: "x.ts".to_string(),
                reason: DriftReason::Missing,
                expected_hash: None,
                actual_hash: None,
                baseline: None,
                current: None,
                diff: None,
            }],
        };
        let drifts = vec![make("a"), make("b")];

        let report = format_gen_drift_report(&drifts, "typescript");

        assert!(report.contains("module a (typescript)"));
        assert!(report.contains("module b (typescript)"));
        assert!(report.contains("napl reconcile a"));
        assert!(report.contains("napl reconcile b"));
    }

    #[test]
    fn drift_reason_and_drifted_file_support_equality_and_copy() {
        let r1 = DriftReason::Edited;
        let r2 = r1;
        assert_eq!(r1, r2);
        assert_ne!(DriftReason::Edited, DriftReason::Missing);

        let f1 = DriftedFile {
            file: "a.ts".to_string(),
            reason: DriftReason::Edited,
            expected_hash: None,
            actual_hash: None,
            baseline: None,
            current: None,
            diff: None,
        };
        let f2 = f1.clone();
        assert_eq!(f1, f2);
    }
}
