// GENERATED BY NAPL from snapshot_filter.napl — edit the prompt, not this file

use std::collections::HashSet;

/// Pure exclusion-predicate core for the snapshot walk: decides which
/// directories and files to skip, without touching the filesystem.
pub struct SnapshotFilter {
    excluded_dirs: HashSet<String>,
    excluded_files: HashSet<String>,
    excluded_root_files: HashSet<String>,
    excluded_suffixes: Vec<String>,
}

/// Build a `SnapshotFilter` from the four rule lists.
pub fn make_filter(
    exclude_dirs: &[String],
    exclude_files: &[String],
    exclude_root_files: &[String],
    exclude_suffixes: &[String],
) -> SnapshotFilter {
    SnapshotFilter {
        excluded_dirs: exclude_dirs.iter().cloned().collect(),
        excluded_files: exclude_files.iter().cloned().collect(),
        excluded_root_files: exclude_root_files.iter().cloned().collect(),
        excluded_suffixes: exclude_suffixes.to_vec(),
    }
}

impl SnapshotFilter {
    /// `true` when `name` exactly matches an excluded directory name.
    pub fn is_excluded_dir(&self, name: &str) -> bool {
        self.excluded_dirs.contains(name)
    }

    /// `true` when `name` matches a plain file rule, a root-only rule
    /// (only if `at_root`), or a suffix rule.
    pub fn is_excluded_file(&self, name: &str, at_root: bool) -> bool {
        self.excluded_files.contains(name)
            || (at_root && self.excluded_root_files.contains(name))
            || self.excluded_suffixes.iter().any(|suffix| name.ends_with(suffix.as_str()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn strs(items: &[&str]) -> Vec<String> {
        items.iter().map(|s| s.to_string()).collect()
    }

    fn worked_filter() -> SnapshotFilter {
        make_filter(
            &strs(&["node_modules", ".git"]),
            &strs(&["AGENTS.md"]),
            &strs(&["Cargo.toml"]),
            &strs(&[".d.ts"]),
        )
    }

    #[test]
    fn dir_exact_match_excluded() {
        let f = worked_filter();
        assert!(f.is_excluded_dir("node_modules"));
        assert!(f.is_excluded_dir(".git"));
    }

    #[test]
    fn dir_non_match_not_excluded() {
        let f = worked_filter();
        assert!(!f.is_excluded_dir("src"));
    }

    #[test]
    fn dir_no_suffix_or_prefix_logic() {
        let f = worked_filter();
        assert!(!f.is_excluded_dir("node_modules_extra"));
        assert!(!f.is_excluded_dir("my_node_modules"));
    }

    #[test]
    fn plain_file_rule_excluded_regardless_of_depth() {
        let f = worked_filter();
        assert!(f.is_excluded_file("AGENTS.md", false));
        assert!(f.is_excluded_file("AGENTS.md", true));
    }

    #[test]
    fn suffix_rule_excluded_anywhere() {
        let f = worked_filter();
        assert!(f.is_excluded_file("types.d.ts", false));
        assert!(f.is_excluded_file("types.d.ts", true));
    }

    #[test]
    fn root_only_rule_applies_at_root() {
        let f = worked_filter();
        assert!(f.is_excluded_file("Cargo.toml", true));
    }

    #[test]
    fn root_only_rule_ignored_below_root() {
        let f = worked_filter();
        assert!(!f.is_excluded_file("Cargo.toml", false));
    }

    #[test]
    fn no_matching_rule_not_excluded() {
        let f = worked_filter();
        assert!(!f.is_excluded_file("keep.ts", false));
        assert!(!f.is_excluded_file("keep.ts", true));
    }

    #[test]
    fn empty_rules_exclude_nothing() {
        let f = make_filter(&[], &[], &[], &[]);
        assert!(!f.is_excluded_dir("anything"));
        assert!(!f.is_excluded_file("anything", true));
        assert!(!f.is_excluded_file("anything", false));
    }
}
