// GENERATED BY NAPL from guard.napl — edit the prompt, not this file

use serde_json::{Map, Value};

pub const GUARD_DOC: &str = "Files in this tree are GENERATED by NAPL from the .napl prompt files in the project root. Do not edit them directly — edit the prompts and run napl gen. Direct edits are detected as DRIFT and block compilation.\n";

pub const GUARD_FILE_NAMES: [&str; 2] = ["AGENTS.md", "CLAUDE.md"];

pub const PRE_COMMIT_HOOK: &str = "#!/bin/sh\nif ! napl status; then\n\techo \"napl: commit blocked — generated code has drifted from its prompts (see above).\" >&2\n\techo \"napl: to commit anyway (work in progress), run: git commit --no-verify\" >&2\n\texit 1\nfi\n";

pub const PRE_COMMIT_HOOK_LINE: &str = "napl status";

pub const NAPL_DENY_RULES: [&str; 1] = ["Edit(/.napl/src/**)"];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SettingsMergeAction {
    Create,
    Update,
    Unchanged,
    Manual,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SettingsMergeResult {
    pub action: SettingsMergeAction,
    pub content: Option<String>,
    pub added: Vec<String>,
}

pub fn claude_settings_snippet() -> String {
    let mut deny = Vec::new();
    let mut permissions = Map::new();
    for rule in NAPL_DENY_RULES {
        deny.push(Value::String(rule.to_string()));
    }
    permissions.insert("deny".to_string(), Value::Array(deny));
    let mut root = Map::new();
    root.insert("permissions".to_string(), Value::Object(permissions));
    let mut content = serde_json::to_string_pretty(&Value::Object(root)).unwrap();
    content.push('\n');
    content
}

pub fn merge_claude_settings(existing: Option<&str>) -> SettingsMergeResult {
    let existing = match existing {
        None => {
            return SettingsMergeResult {
                action: SettingsMergeAction::Create,
                content: Some(claude_settings_snippet()),
                added: NAPL_DENY_RULES.iter().map(|s| s.to_string()).collect(),
            };
        }
        Some(existing) => existing,
    };

    let manual = SettingsMergeResult {
        action: SettingsMergeAction::Manual,
        content: None,
        added: Vec::new(),
    };

    let parsed: Value = match serde_json::from_str(existing) {
        Ok(value) => value,
        Err(_) => return manual,
    };

    let mut root = match parsed {
        Value::Object(map) => map,
        _ => return manual,
    };

    let mut permissions = match root.get("permissions") {
        None => Map::new(),
        Some(Value::Object(map)) => map.clone(),
        Some(_) => return manual,
    };

    let mut deny = match permissions.get("deny") {
        None => Vec::new(),
        Some(Value::Array(array)) => array.clone(),
        Some(_) => return manual,
    };

    let mut added = Vec::new();
    for rule in NAPL_DENY_RULES {
        let already_present = deny.iter().any(|value| value.as_str() == Some(rule));
        if !already_present {
            deny.push(Value::String(rule.to_string()));
            added.push(rule.to_string());
        }
    }

    if added.is_empty() {
        return SettingsMergeResult {
            action: SettingsMergeAction::Unchanged,
            content: None,
            added: Vec::new(),
        };
    }

    permissions.insert("deny".to_string(), Value::Array(deny));
    root.insert("permissions".to_string(), Value::Object(permissions));

    let mut content = serde_json::to_string_pretty(&Value::Object(root)).unwrap();
    content.push('\n');

    SettingsMergeResult {
        action: SettingsMergeAction::Update,
        content: Some(content),
        added,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SNIPPET: &str = "{\n  \"permissions\": {\n    \"deny\": [\n      \"Edit(/.napl/src/**)\"\n    ]\n  }\n}\n";

    #[test]
    fn guard_doc_is_pinned() {
        assert_eq!(
            GUARD_DOC,
            "Files in this tree are GENERATED by NAPL from the .napl prompt files in the project root. Do not edit them directly — edit the prompts and run napl gen. Direct edits are detected as DRIFT and block compilation.\n"
        );
    }

    #[test]
    fn guard_file_names_are_pinned() {
        assert_eq!(GUARD_FILE_NAMES, ["AGENTS.md", "CLAUDE.md"]);
    }

    #[test]
    fn pre_commit_hook_is_pinned() {
        assert_eq!(
            PRE_COMMIT_HOOK,
            "#!/bin/sh\nif ! napl status; then\n\techo \"napl: commit blocked — generated code has drifted from its prompts (see above).\" >&2\n\techo \"napl: to commit anyway (work in progress), run: git commit --no-verify\" >&2\n\texit 1\nfi\n"
        );
    }

    #[test]
    fn pre_commit_hook_line_is_pinned() {
        assert_eq!(PRE_COMMIT_HOOK_LINE, "napl status");
    }

    #[test]
    fn napl_deny_rules_are_pinned() {
        assert_eq!(NAPL_DENY_RULES, ["Edit(/.napl/src/**)"]);
    }

    #[test]
    fn snippet_matches_pinned_string() {
        assert_eq!(claude_settings_snippet(), SNIPPET);
    }

    #[test]
    fn merge_with_no_existing_content_creates() {
        let result = merge_claude_settings(None);
        assert_eq!(result.action, SettingsMergeAction::Create);
        assert_eq!(result.content, Some(SNIPPET.to_string()));
        assert_eq!(result.added, vec!["Edit(/.napl/src/**)".to_string()]);
    }

    #[test]
    fn merge_with_snippet_already_present_is_unchanged() {
        let result = merge_claude_settings(Some(SNIPPET));
        assert_eq!(result.action, SettingsMergeAction::Unchanged);
        assert_eq!(result.content, None);
        assert!(result.added.is_empty());
    }

    #[test]
    fn merge_preserves_unrelated_keys_and_allow_list() {
        let existing = r#"{ "other": true, "permissions": { "allow": ["Read"] } }"#;
        let result = merge_claude_settings(Some(existing));
        assert_eq!(result.action, SettingsMergeAction::Update);
        let content = result.content.expect("content present on update");
        assert!(content.contains("\"other\": true"));
        assert!(content.contains("\"allow\""));
        assert!(content.contains("Edit(/.napl/src/**)"));
        assert!(content.ends_with("}\n"));
        assert_eq!(result.added, vec!["Edit(/.napl/src/**)".to_string()]);
    }

    #[test]
    fn merge_invalid_json_is_manual() {
        let result = merge_claude_settings(Some("not json"));
        assert_eq!(result.action, SettingsMergeAction::Manual);
        assert_eq!(result.content, None);
        assert!(result.added.is_empty());
    }

    #[test]
    fn merge_non_object_root_is_manual() {
        let result = merge_claude_settings(Some("[1,2,3]"));
        assert_eq!(result.action, SettingsMergeAction::Manual);
    }

    #[test]
    fn merge_non_object_permissions_is_manual() {
        let result = merge_claude_settings(Some(r#"{"permissions": 5}"#));
        assert_eq!(result.action, SettingsMergeAction::Manual);
    }

    #[test]
    fn merge_non_array_deny_is_manual() {
        let result = merge_claude_settings(Some(r#"{"permissions": {"deny": 5}}"#));
        assert_eq!(result.action, SettingsMergeAction::Manual);
    }

    #[test]
    fn merge_missing_permissions_treats_as_empty_object() {
        let existing = r#"{"foo": "bar"}"#;
        let result = merge_claude_settings(Some(existing));
        assert_eq!(result.action, SettingsMergeAction::Update);
        let content = result.content.unwrap();
        assert!(content.contains("Edit(/.napl/src/**)"));
        assert!(content.contains("\"foo\": \"bar\""));
    }
}
