// GENERATED BY NAPL from parse_output.napl — edit the prompt, not this file

/// Extracts the YAML content from a language-model response, unwrapping a
/// Markdown code fence if one is present. Returns the whole input trimmed
/// when no complete fenced block is found.
pub fn extract_yaml(text: &str) -> String {
    match find_fenced_block(text) {
        Some(content) => content.trim().to_string(),
        None => text.trim().to_string(),
    }
}

fn find_fenced_block(text: &str) -> Option<&str> {
    let fence_start = find_fence_line_start(text)?;
    let after_fence = &text[fence_start + 3..];
    let newline_offset = after_fence.find('\n')?;
    let content_start = fence_start + 3 + newline_offset + 1;
    let content = &text[content_start..];
    let close_offset = content.find("```")?;
    Some(&content[..close_offset])
}

fn find_fence_line_start(text: &str) -> Option<usize> {
    if text.starts_with("```") {
        return Some(0);
    }
    text.find("\n```").map(|relative| relative + 1)
}

#[cfg(test)]
mod tests {
    use super::extract_yaml;

    #[test]
    fn extracts_yaml_fenced_with_info_string() {
        let text = "```yaml\nmodule: greeting\ntests: []\n```";
        assert_eq!(extract_yaml(text), "module: greeting\ntests: []");
    }

    #[test]
    fn extracts_bare_fence() {
        let text = "```\n[]\n```";
        assert_eq!(extract_yaml(text), "[]");
    }

    #[test]
    fn returns_trimmed_plain_text_when_no_fence() {
        let text = "  hello world  ";
        assert_eq!(extract_yaml(text), "hello world");
    }

    #[test]
    fn returns_trimmed_text_when_opening_fence_has_no_closing_fence() {
        let text = "```yaml\nmodule: greeting\n";
        assert_eq!(extract_yaml(text), text.trim());
    }

    #[test]
    fn returns_trimmed_text_when_fence_has_no_newline() {
        let text = "```yaml module: greeting";
        assert_eq!(extract_yaml(text), text.trim());
    }

    #[test]
    fn ignores_text_before_fence_and_after_closing_fence() {
        let text = "Here is the result:\n```yml\nkey: value\n```\nHope that helps!";
        assert_eq!(extract_yaml(text), "key: value");
    }

    #[test]
    fn trims_surrounding_whitespace_inside_fence() {
        let text = "```yaml\n\n  key: value  \n\n```";
        assert_eq!(extract_yaml(text), "key: value");
    }

    #[test]
    fn handles_fence_opening_line_with_extra_characters() {
        let text = "```yaml some extra stuff\nkey: value\n```";
        assert_eq!(extract_yaml(text), "key: value");
    }

    #[test]
    fn finds_first_fence_when_multiple_present() {
        let text = "```yaml\nfirst: block\n```\n```yaml\nsecond: block\n```";
        assert_eq!(extract_yaml(text), "first: block");
    }

    #[test]
    fn empty_text_returns_empty_string() {
        assert_eq!(extract_yaml(""), "");
    }
}
