// GENERATED BY NAPL from schemas_frontmatter.napl — edit the prompt, not this file

use std::fmt;

use serde::Deserialize;

fn default_mapping() -> serde_yaml::Value {
    serde_yaml::Value::Mapping(serde_yaml::Mapping::new())
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct PromptTest {
    pub name: String,
    #[serde(default = "default_mapping")]
    pub given: serde_yaml::Value,
    #[serde(default = "default_mapping")]
    pub expect: serde_yaml::Value,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Frontmatter {
    pub module: String,
    #[serde(default)]
    pub deps: Vec<String>,
    #[serde(default)]
    pub targets: Vec<String>,
    #[serde(default)]
    pub tests: Vec<PromptTest>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ParsedPrompt {
    pub frontmatter: Frontmatter,
    pub body: String,
}

#[derive(Debug)]
pub enum FrontmatterError {
    MissingFrontmatter,
    InvalidYaml(serde_yaml::Error),
    EmptyModule,
    InvalidTestField { test_name: String, field: &'static str },
}

impl fmt::Display for FrontmatterError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            FrontmatterError::MissingFrontmatter => {
                write!(f, "prompt file does not start with a valid YAML frontmatter block")
            }
            FrontmatterError::InvalidYaml(err) => write!(f, "invalid frontmatter YAML: {err}"),
            FrontmatterError::EmptyModule => write!(f, "frontmatter `module` must be a non-empty string"),
            FrontmatterError::InvalidTestField { test_name, field } => write!(
                f,
                "test `{test_name}` field `{field}` must be a YAML mapping"
            ),
        }
    }
}

impl std::error::Error for FrontmatterError {}

fn split_delimiters(raw: &str) -> Result<(&str, &str), FrontmatterError> {
    let after_open = raw
        .strip_prefix("---\r\n")
        .or_else(|| raw.strip_prefix("---\n"))
        .ok_or(FrontmatterError::MissingFrontmatter)?;

    let mut pos = 0usize;
    loop {
        let newline_pos = after_open[pos..].find('\n').map(|i| pos + i);
        let line_end = newline_pos.unwrap_or(after_open.len());
        let line = &after_open[pos..line_end];
        let line = line.strip_suffix('\r').unwrap_or(line);

        if line == "---" {
            let yaml_text = &after_open[..pos];
            let body_start = match newline_pos {
                Some(nl) => nl + 1,
                None => after_open.len(),
            };
            let body = &after_open[body_start..];
            return Ok((yaml_text, body));
        }

        match newline_pos {
            Some(nl) => pos = nl + 1,
            None => return Err(FrontmatterError::MissingFrontmatter),
        }
    }
}

fn strip_leading_blank_line(body: &str) -> &str {
    if let Some(rel_nl) = body.find('\n') {
        if body[..rel_nl].trim().is_empty() {
            return &body[rel_nl + 1..];
        }
    }
    body
}

pub fn parse_frontmatter(raw: &str) -> Result<ParsedPrompt, FrontmatterError> {
    let (yaml_text, raw_body) = split_delimiters(raw)?;

    let value: serde_yaml::Value = if yaml_text.trim().is_empty() {
        default_mapping()
    } else {
        let parsed: serde_yaml::Value =
            serde_yaml::from_str(yaml_text).map_err(FrontmatterError::InvalidYaml)?;
        if parsed.is_null() {
            default_mapping()
        } else {
            parsed
        }
    };

    let frontmatter: Frontmatter =
        serde_yaml::from_value(value).map_err(FrontmatterError::InvalidYaml)?;

    if frontmatter.module.is_empty() {
        return Err(FrontmatterError::EmptyModule);
    }

    for test in &frontmatter.tests {
        if !test.given.is_mapping() {
            return Err(FrontmatterError::InvalidTestField {
                test_name: test.name.clone(),
                field: "given",
            });
        }
        if !test.expect.is_mapping() {
            return Err(FrontmatterError::InvalidTestField {
                test_name: test.name.clone(),
                field: "expect",
            });
        }
    }

    let body = strip_leading_blank_line(raw_body).to_string();

    Ok(ParsedPrompt { frontmatter, body })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_full_frontmatter_with_test_case() {
        let raw = "---\nmodule: auth/session\ndeps: [auth/tokens]\ntargets: [typescript]\ntests:\n  - name: expired token rejected\n    given: { token: expired }\n    expect: { error: SESSION_EXPIRED }\n---\nManage user sessions. Sessions expire after 30 minutes.";

        let parsed = parse_frontmatter(raw).expect("should parse");

        assert_eq!(parsed.frontmatter.module, "auth/session");
        assert_eq!(parsed.frontmatter.deps, vec!["auth/tokens".to_string()]);
        assert_eq!(parsed.frontmatter.targets, vec!["typescript".to_string()]);
        assert_eq!(parsed.frontmatter.tests.len(), 1);

        let test = &parsed.frontmatter.tests[0];
        assert_eq!(test.name, "expired token rejected");
        let given = test.given.as_mapping().expect("mapping");
        assert_eq!(
            given.get("token").and_then(|v| v.as_str()),
            Some("expired")
        );
        let expect = test.expect.as_mapping().expect("mapping");
        assert_eq!(
            expect.get("error").and_then(|v| v.as_str()),
            Some("SESSION_EXPIRED")
        );

        assert!(parsed.body.starts_with("Manage user sessions."));
    }

    #[test]
    fn parses_minimal_frontmatter_with_defaults() {
        let raw = "---\nmodule: solo\n---\nBody here.\n";
        let parsed = parse_frontmatter(raw).expect("should parse");

        assert_eq!(parsed.frontmatter.module, "solo");
        assert!(parsed.frontmatter.deps.is_empty());
        assert!(parsed.frontmatter.targets.is_empty());
        assert!(parsed.frontmatter.tests.is_empty());
        assert_eq!(parsed.body, "Body here.\n");
    }

    #[test]
    fn test_given_and_expect_default_to_empty_mapping() {
        let raw = "---\nmodule: m\ntests:\n  - name: bare test\n---\nBody\n";
        let parsed = parse_frontmatter(raw).expect("should parse");

        let test = &parsed.frontmatter.tests[0];
        assert_eq!(test.given, serde_yaml::Value::Mapping(Default::default()));
        assert_eq!(test.expect, serde_yaml::Value::Mapping(Default::default()));
    }

    #[test]
    fn rejects_missing_frontmatter_entirely() {
        let raw = "no frontmatter here";
        let err = parse_frontmatter(raw).unwrap_err();
        assert!(matches!(err, FrontmatterError::MissingFrontmatter));
    }

    #[test]
    fn rejects_missing_module_key() {
        let raw = "---\ndeps: []\n---\nbody";
        let err = parse_frontmatter(raw).unwrap_err();
        assert!(matches!(err, FrontmatterError::InvalidYaml(_)));
    }

    #[test]
    fn rejects_empty_module_value() {
        let raw = "---\nmodule: \"\"\n---\nbody";
        let err = parse_frontmatter(raw).unwrap_err();
        assert!(matches!(err, FrontmatterError::EmptyModule));
    }

    #[test]
    fn rejects_missing_closing_delimiter() {
        let raw = "---\nmodule: m\nno closing delimiter here\n";
        let err = parse_frontmatter(raw).unwrap_err();
        assert!(matches!(err, FrontmatterError::MissingFrontmatter));
    }

    #[test]
    fn rejects_non_mapping_given() {
        let raw = "---\nmodule: m\ntests:\n  - name: t\n    given: [1, 2]\n---\nbody";
        let err = parse_frontmatter(raw).unwrap_err();
        assert!(matches!(
            err,
            FrontmatterError::InvalidTestField { field: "given", .. }
        ));
    }

    #[test]
    fn rejects_non_mapping_expect() {
        let raw = "---\nmodule: m\ntests:\n  - name: t\n    expect: 5\n---\nbody";
        let err = parse_frontmatter(raw).unwrap_err();
        assert!(matches!(
            err,
            FrontmatterError::InvalidTestField { field: "expect", .. }
        ));
    }

    #[test]
    fn strips_single_leading_blank_line_from_body() {
        let raw = "---\nmodule: m\n---\n\nActual body.\n";
        let parsed = parse_frontmatter(raw).expect("should parse");
        assert_eq!(parsed.body, "Actual body.\n");
    }

    #[test]
    fn does_not_strip_body_without_leading_blank_line() {
        let raw = "---\nmodule: m\n---\nFirst line.\nSecond line.\n";
        let parsed = parse_frontmatter(raw).expect("should parse");
        assert_eq!(parsed.body, "First line.\nSecond line.\n");
    }

    #[test]
    fn handles_crlf_line_endings() {
        let raw = "---\r\nmodule: m\r\n---\r\nBody.\r\n";
        let parsed = parse_frontmatter(raw).expect("should parse");
        assert_eq!(parsed.frontmatter.module, "m");
        assert_eq!(parsed.body, "Body.\r\n");
    }

    #[test]
    fn empty_yaml_block_treated_as_empty_mapping_still_requires_module() {
        let raw = "---\n---\nbody";
        let err = parse_frontmatter(raw).unwrap_err();
        assert!(matches!(err, FrontmatterError::InvalidYaml(_)));
    }
}
