// GENERATED BY NAPL from scanner.napl — edit the prompt, not this file

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Position {
    pub line: usize,
    pub character: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Span {
    pub start: Position,
    pub end: Position,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegionSpan {
    pub present: bool,
    pub span: Option<Span>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FrontmatterKeyToken {
    pub key: String,
    pub key_span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModuleValueToken {
    pub value: String,
    pub span: Span,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DepSource {
    Deps,
    Extends,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DepToken {
    pub value: String,
    pub span: Span,
    pub source: DepSource,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RefToken {
    pub module: String,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScanResult {
    pub frontmatter: RegionSpan,
    pub body: RegionSpan,
    pub keys: Vec<FrontmatterKeyToken>,
    pub module_value: Option<ModuleValueToken>,
    pub deps: Vec<DepToken>,
    pub refs: Vec<RefToken>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Target {
    ModuleValue { module: String, span: Span },
    Dep { module: String, span: Span, source: DepSource },
    Ref { module: String, span: Span },
}

fn split_lines(text: &str) -> Vec<&str> {
    text.split('\n')
        .map(|line| line.strip_suffix('\r').unwrap_or(line))
        .collect()
}

fn utf16_len(s: &str) -> usize {
    s.chars().map(|c| c.len_utf16()).sum()
}

fn strip_quotes(s: &str) -> (String, bool) {
    let bytes = s.as_bytes();
    if bytes.len() >= 2 {
        let first = bytes[0];
        let last = bytes[bytes.len() - 1];
        if (first == b'\'' || first == b'"') && first == last {
            return (s[1..s.len() - 1].to_string(), true);
        }
    }
    (s.to_string(), false)
}

fn match_key(line: &str) -> Option<&str> {
    let bytes = line.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        let is_key_char = b.is_ascii_alphanumeric() || b == b'_' || b == b'-';
        if !is_key_char {
            break;
        }
        i += 1;
    }
    if i == 0 || i >= bytes.len() || bytes[i] != b':' {
        return None;
    }
    Some(&line[..i])
}

fn scalar_after_colon(rest: &str, key_end_char: usize) -> Option<(String, usize, usize)> {
    let leading_ws: usize = rest
        .chars()
        .take_while(|c| c.is_whitespace())
        .map(|c| c.len_utf16())
        .sum();
    let trimmed = rest.trim();
    if trimmed.is_empty() {
        return None;
    }
    let mut start = key_end_char + leading_ws;
    let (value, quoted) = strip_quotes(trimmed);
    if quoted {
        start += 1;
    }
    let end = start + utf16_len(&value);
    Some((value, start, end))
}

fn match_block_item(line: &str) -> Option<(usize, usize, String)> {
    let chars: Vec<char> = line.chars().collect();
    let mut idx = 0;
    let mut indent_units = 0usize;
    while idx < chars.len() && chars[idx].is_whitespace() {
        indent_units += chars[idx].len_utf16();
        idx += 1;
    }
    if idx >= chars.len() || chars[idx] != '-' {
        return None;
    }
    idx += 1;
    let mut space_count = 0usize;
    while idx < chars.len() && chars[idx].is_whitespace() {
        space_count += 1;
        idx += 1;
    }
    if space_count == 0 {
        return None;
    }
    let rest: String = chars[idx..].iter().collect();
    Some((indent_units, space_count, rest))
}

fn parse_inline_list(rest: &str, key_end_char: usize, line_idx: usize, source: DepSource) -> Vec<DepToken> {
    let mut result = Vec::new();
    let open_byte = match rest.find('[') {
        Some(p) => p,
        None => return result,
    };
    let close_byte = match rest.rfind(']') {
        Some(p) if p > open_byte => p,
        _ => rest.len(),
    };
    let inner = &rest[open_byte + 1..close_byte];
    let open_utf16_offset = utf16_len(&rest[..open_byte]);
    let base_column = key_end_char + open_utf16_offset + 1;

    let mut segments: Vec<(usize, usize)> = Vec::new();
    let mut seg_start = 0usize;
    for (idx, c) in inner.char_indices() {
        if c == ',' {
            segments.push((seg_start, idx));
            seg_start = idx + c.len_utf8();
        }
    }
    segments.push((seg_start, inner.len()));

    for (s, e) in segments {
        let raw_item = &inner[s..e];
        let trimmed = raw_item.trim();
        if trimmed.is_empty() {
            continue;
        }
        let lead_ws_bytes = raw_item.len() - raw_item.trim_start().len();
        let leading_ws_units = utf16_len(&raw_item[..lead_ws_bytes]);
        let item_offset_units = utf16_len(&inner[..s]) + leading_ws_units;
        let (value, quoted) = strip_quotes(trimmed);
        let mut start = base_column + item_offset_units;
        if quoted {
            start += 1;
        }
        let end = start + utf16_len(&value);
        result.push(DepToken {
            value,
            span: Span {
                start: Position { line: line_idx, character: start },
                end: Position { line: line_idx, character: end },
            },
            source,
        });
    }
    result
}

fn scan_frontmatter(
    lines: &[&str],
    start_idx: usize,
) -> (Vec<FrontmatterKeyToken>, Option<ModuleValueToken>, Vec<DepToken>) {
    let mut keys = Vec::new();
    let mut module_value = None;
    let mut deps = Vec::new();
    let mut block_state: Option<DepSource> = None;

    for (offset, line) in lines.iter().enumerate() {
        let i = start_idx + offset;
        if let Some(key) = match_key(line) {
            block_state = None;
            let key_len = utf16_len(key);
            let key_span = Span {
                start: Position { line: i, character: 0 },
                end: Position { line: i, character: key_len },
            };
            keys.push(FrontmatterKeyToken { key: key.to_string(), key_span });
            let key_end_char = key_len + 1;
            let rest = &line[key.len() + 1..];
            match key {
                "module" => {
                    if let Some((value, start, end)) = scalar_after_colon(rest, key_end_char) {
                        module_value = Some(ModuleValueToken {
                            value,
                            span: Span {
                                start: Position { line: i, character: start },
                                end: Position { line: i, character: end },
                            },
                        });
                    }
                }
                "deps" | "extends" => {
                    let source = if key == "deps" { DepSource::Deps } else { DepSource::Extends };
                    let trimmed_rest = rest.trim();
                    if trimmed_rest.starts_with('[') {
                        deps.extend(parse_inline_list(rest, key_end_char, i, source));
                    } else if trimmed_rest.is_empty() {
                        block_state = Some(source);
                    } else if let Some((value, start, end)) = scalar_after_colon(rest, key_end_char) {
                        deps.push(DepToken {
                            value,
                            span: Span {
                                start: Position { line: i, character: start },
                                end: Position { line: i, character: end },
                            },
                            source,
                        });
                    }
                }
                _ => {}
            }
        } else if let Some(source) = block_state {
            if let Some((indent_units, space_count, rest)) = match_block_item(line) {
                let trimmed = rest.trim();
                if !trimmed.is_empty() {
                    let (value, quoted) = strip_quotes(trimmed);
                    let mut start = indent_units + 1 + space_count;
                    if quoted {
                        start += 1;
                    }
                    let end = start + utf16_len(&value);
                    deps.push(DepToken {
                        value,
                        span: Span {
                            start: Position { line: i, character: start },
                            end: Position { line: i, character: end },
                        },
                        source,
                    });
                }
            }
        }
    }
    (keys, module_value, deps)
}

fn is_ref_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_' || c == '/' || c == '-'
}

fn scan_refs_in_line(line: &str, line_idx: usize) -> Vec<RefToken> {
    let mut refs = Vec::new();
    let chars: Vec<char> = line.chars().collect();
    let mut col = 0usize;
    let mut i = 0usize;
    while i < chars.len() {
        let c = chars[i];
        if c == '@' {
            let mut j = i + 1;
            let mut name = String::new();
            while j < chars.len() && is_ref_char(chars[j]) {
                name.push(chars[j]);
                j += 1;
            }
            if !name.is_empty() {
                let mut token_len = c.len_utf16();
                for k in i + 1..j {
                    token_len += chars[k].len_utf16();
                }
                let start_col = col;
                let end_col = start_col + token_len;
                refs.push(RefToken {
                    module: name,
                    span: Span {
                        start: Position { line: line_idx, character: start_col },
                        end: Position { line: line_idx, character: end_col },
                    },
                });
                for k in i..j {
                    col += chars[k].len_utf16();
                }
                i = j;
                continue;
            }
        }
        col += c.len_utf16();
        i += 1;
    }
    refs
}

pub fn scan(text: &str) -> ScanResult {
    let lines = split_lines(text);
    let last_idx = lines.len() - 1;

    let first_trimmed = lines[0].trim_end();
    let mut close: Option<usize> = None;
    if first_trimmed == "---" {
        for idx in 1..lines.len() {
            if lines[idx].trim_end() == "---" {
                close = Some(idx);
                break;
            }
        }
    }

    let mut keys = Vec::new();
    let mut module_value = None;
    let mut deps = Vec::new();
    let mut refs = Vec::new();
    let frontmatter;
    let body;

    if let Some(close_idx) = close {
        let inner_lines = &lines[1..close_idx];
        if inner_lines.is_empty() {
            frontmatter = RegionSpan {
                present: true,
                span: Some(Span {
                    start: Position { line: 1, character: 0 },
                    end: Position { line: 1, character: 0 },
                }),
            };
        } else {
            let last_inner_idx = close_idx - 1;
            frontmatter = RegionSpan {
                present: true,
                span: Some(Span {
                    start: Position { line: 1, character: 0 },
                    end: Position { line: last_inner_idx, character: utf16_len(lines[last_inner_idx]) },
                }),
            };
        }
        let (k, mv, d) = scan_frontmatter(inner_lines, 1);
        keys = k;
        module_value = mv;
        deps = d;

        let body_start = close_idx + 1;
        if body_start < lines.len() {
            body = RegionSpan {
                present: true,
                span: Some(Span {
                    start: Position { line: body_start, character: 0 },
                    end: Position { line: last_idx, character: utf16_len(lines[last_idx]) },
                }),
            };
            for idx in body_start..lines.len() {
                refs.extend(scan_refs_in_line(lines[idx], idx));
            }
        } else {
            body = RegionSpan { present: false, span: None };
        }
    } else {
        frontmatter = RegionSpan { present: false, span: None };
        body = RegionSpan {
            present: true,
            span: Some(Span {
                start: Position { line: 0, character: 0 },
                end: Position { line: last_idx, character: utf16_len(lines[last_idx]) },
            }),
        };
        for idx in 0..lines.len() {
            refs.extend(scan_refs_in_line(lines[idx], idx));
        }
    }

    ScanResult { frontmatter, body, keys, module_value, deps, refs }
}

fn pos_lt(a: Position, b: Position) -> bool {
    (a.line, a.character) < (b.line, b.character)
}

fn span_contains(span: &Span, pos: Position) -> bool {
    !pos_lt(pos, span.start) && !pos_lt(span.end, pos)
}

pub fn find_target_at_position(scan: &ScanResult, position: Position) -> Option<Target> {
    if let Some(mv) = &scan.module_value {
        if span_contains(&mv.span, position) {
            return Some(Target::ModuleValue { module: mv.value.clone(), span: mv.span });
        }
    }
    for dep in &scan.deps {
        if span_contains(&dep.span, position) {
            return Some(Target::Dep { module: dep.value.clone(), span: dep.span, source: dep.source });
        }
    }
    for r in &scan.refs {
        if span_contains(&r.span, position) {
            return Some(Target::Ref { module: r.module.clone(), span: r.span });
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pos(line: usize, character: usize) -> Position {
        Position { line, character }
    }

    fn span(sl: usize, sc: usize, el: usize, ec: usize) -> Span {
        Span { start: pos(sl, sc), end: pos(el, ec) }
    }

    const MAIN_DOC: &str = "---\nmodule: auth/session\ndeps: [auth/tokens, auth/users]\ntargets: [typescript]\n---\n# Session\n\nManage sessions. See @auth/tokens and @auth/users for details.\nRefreshes via @auth/session.\n";

    #[test]
    fn main_doc_module_value() {
        let result = scan(MAIN_DOC);
        let mv = result.module_value.expect("module value present");
        assert_eq!(mv.value, "auth/session");
        assert_eq!(mv.span, span(1, 8, 1, 20));
    }

    #[test]
    fn main_doc_deps() {
        let result = scan(MAIN_DOC);
        assert_eq!(result.deps.len(), 2);
        assert_eq!(result.deps[0].value, "auth/tokens");
        assert_eq!(result.deps[0].source, DepSource::Deps);
        assert_eq!(result.deps[0].span, span(2, 7, 2, 18));
        assert_eq!(result.deps[1].value, "auth/users");
        assert_eq!(result.deps[1].span.start, pos(2, 20));
        assert_eq!(result.deps[1].span.end, pos(2, 30));
    }

    #[test]
    fn main_doc_refs() {
        let result = scan(MAIN_DOC);
        let names: Vec<&str> = result.refs.iter().map(|r| r.module.as_str()).collect();
        assert_eq!(names, vec!["auth/tokens", "auth/users", "auth/session"]);
        assert_eq!(result.refs[0].span, span(7, 21, 7, 33));
    }

    #[test]
    fn main_doc_regions() {
        let result = scan(MAIN_DOC);
        assert!(result.frontmatter.present);
        assert_eq!(result.frontmatter.span.unwrap().start, pos(1, 0));
        assert_eq!(result.frontmatter.span.unwrap().end.line, 3);
        assert!(result.body.present);
        assert_eq!(result.body.span.unwrap().start.line, 5);
    }

    #[test]
    fn main_doc_find_target() {
        let result = scan(MAIN_DOC);
        match find_target_at_position(&result, pos(1, 10)) {
            Some(Target::ModuleValue { module, .. }) => assert_eq!(module, "auth/session"),
            other => panic!("unexpected: {:?}", other),
        }
        match find_target_at_position(&result, pos(2, 10)) {
            Some(Target::Dep { module, source, .. }) => {
                assert_eq!(module, "auth/tokens");
                assert_eq!(source, DepSource::Deps);
            }
            other => panic!("unexpected: {:?}", other),
        }
        match find_target_at_position(&result, pos(7, 25)) {
            Some(Target::Ref { module, .. }) => assert_eq!(module, "auth/tokens"),
            other => panic!("unexpected: {:?}", other),
        }
        assert!(find_target_at_position(&result, pos(5, 0)).is_none());
    }

    #[test]
    fn block_list_deps() {
        let doc = "---\nmodule: a\ndeps:\n  - one\n  - \"two/x\"\nextends: base\n---\nbody\n";
        let result = scan(doc);
        assert_eq!(result.deps.len(), 3);

        assert_eq!(result.deps[0].source, DepSource::Deps);
        assert_eq!(result.deps[0].value, "one");
        assert_eq!(result.deps[0].span, span(3, 4, 3, 7));

        assert_eq!(result.deps[1].source, DepSource::Deps);
        assert_eq!(result.deps[1].value, "two/x");
        assert_eq!(result.deps[1].span.start, pos(4, 5));

        assert_eq!(result.deps[2].source, DepSource::Extends);
        assert_eq!(result.deps[2].value, "base");
        assert_eq!(result.deps[2].span.start, pos(5, 9));
    }

    #[test]
    fn empty_inline_list() {
        let doc = "---\nmodule: greeting\ndeps: []\n---\nbody\n";
        let result = scan(doc);
        assert!(result.deps.is_empty());
        assert_eq!(result.module_value.unwrap().value, "greeting");
    }

    #[test]
    fn astral_emoji_ref_offset() {
        let doc = "---\nmodule: m\n---\n\u{1F600}\u{1F600}@auth/x\n";
        let result = scan(doc);
        assert_eq!(result.refs.len(), 1);
        assert_eq!(result.refs[0].module, "auth/x");
        assert_eq!(result.refs[0].span, span(3, 4, 3, 11));
    }

    #[test]
    fn bmp_char_ref_offset() {
        let doc = "---\nmodule: m\n---\n\u{00E9}@x/y\n";
        let result = scan(doc);
        assert_eq!(result.refs.len(), 1);
        assert_eq!(result.refs[0].span.start, pos(3, 1));
    }

    #[test]
    fn no_frontmatter_body_present() {
        let doc = "# just a heading\nwith @a/b ref\n";
        let result = scan(doc);
        assert!(!result.frontmatter.present);
        assert!(result.body.present);
        assert_eq!(result.body.span.unwrap().start, pos(0, 0));
        assert_eq!(result.refs.len(), 1);
        assert_eq!(result.refs[0].module, "a/b");
    }

    #[test]
    fn frontmatter_with_no_body_after() {
        // trailing "\n" still yields one empty body line, so body is present but empty
        let doc = "---\nmodule: a\n---\n";
        let result = scan(doc);
        assert!(result.frontmatter.present);
        assert!(result.body.present);
        assert_eq!(result.body.span.unwrap(), span(3, 0, 3, 0));
    }

    #[test]
    fn frontmatter_with_truly_nothing_after() {
        let doc = "---\nmodule: a\n---";
        let result = scan(doc);
        assert!(result.frontmatter.present);
        assert!(!result.body.present);
    }

    #[test]
    fn bare_at_is_not_a_ref() {
        let doc = "hello @ world\n";
        let result = scan(doc);
        assert!(result.refs.is_empty());
    }

    #[test]
    fn dash_without_space_is_not_block_item() {
        let doc = "---\nmodule: a\ndeps:\n  -nospace\n---\nbody\n";
        let result = scan(doc);
        assert!(result.deps.is_empty());
    }

    #[test]
    fn crlf_lines_behave_like_lf() {
        let doc = "---\r\nmodule: a\r\n---\r\nbody\r\n";
        let result = scan(doc);
        assert!(result.frontmatter.present);
        assert_eq!(result.module_value.unwrap().value, "a");
    }
}
