import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { runInit } from '../src/commands/init.js';

let root: string;

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), 'napl-init-'));
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

describe('runInit guard docs', () => {
  it('writes AGENTS.md and CLAUDE.md into every target src tree', async () => {
    await runInit({ root });
    for (const target of ['typescript', 'react']) {
      for (const name of ['AGENTS.md', 'CLAUDE.md']) {
        const content = await readFile(join(root, '.napl', 'src', target, name), 'utf8');
        expect(content).toContain('GENERATED by NAPL');
        expect(content).toContain('block compilation');
      }
    }
  });
});

describe('runInit Claude deny rules', () => {
  it('creates .claude/settings.json denying edits to .napl/src', async () => {
    await runInit({ root });
    const settings = JSON.parse(await readFile(join(root, '.claude', 'settings.json'), 'utf8'));
    expect(settings.permissions.deny).toContain('Edit(/.napl/src/**)');
  });

  it('merges into an existing settings.json without clobbering other keys', async () => {
    await mkdir(join(root, '.claude'), { recursive: true });
    await writeFile(
      join(root, '.claude', 'settings.json'),
      JSON.stringify({ permissions: { allow: ['Bash(ls)'] }, model: 'opus' }, null, 2),
      'utf8',
    );
    await runInit({ root });
    const settings = JSON.parse(await readFile(join(root, '.claude', 'settings.json'), 'utf8'));
    expect(settings.model).toBe('opus');
    expect(settings.permissions.allow).toEqual(['Bash(ls)']);
    expect(settings.permissions.deny).toContain('Edit(/.napl/src/**)');
  });

  it('leaves an unparseable settings file untouched and prints the snippet', async () => {
    await mkdir(join(root, '.claude'), { recursive: true });
    await writeFile(join(root, '.claude', 'settings.json'), '{ broken', 'utf8');
    const logs: string[] = [];
    await runInit({ root, log: (m) => logs.push(m) });
    expect(await readFile(join(root, '.claude', 'settings.json'), 'utf8')).toBe('{ broken');
    expect(logs.some((line) => line.includes('Edit(/.napl/src/**)'))).toBe(true);
  });
});

describe('runInit pre-commit hook', () => {
  it('installs an executable pre-commit hook when a .git directory exists', async () => {
    await mkdir(join(root, '.git'), { recursive: true });
    await runInit({ root });
    const hookPath = join(root, '.git', 'hooks', 'pre-commit');
    expect(existsSync(hookPath)).toBe(true);
    const content = await readFile(hookPath, 'utf8');
    expect(content).toContain('napl status');
    expect(content).toContain('git commit --no-verify');
    expect((await stat(hookPath)).mode & 0o100).toBeTruthy();
  });

  it('does not overwrite an existing pre-commit hook', async () => {
    await mkdir(join(root, '.git', 'hooks'), { recursive: true });
    await writeFile(join(root, '.git', 'hooks', 'pre-commit'), '#!/bin/sh\necho custom\n', 'utf8');
    const logs: string[] = [];
    await runInit({ root, log: (m) => logs.push(m) });
    expect(await readFile(join(root, '.git', 'hooks', 'pre-commit'), 'utf8')).toBe('#!/bin/sh\necho custom\n');
    expect(logs.some((line) => line.includes('leaving it untouched'))).toBe(true);
  });
});

describe('runInit idempotency', () => {
  it('reports guard docs as exists on a second run and stays stable', async () => {
    await runInit({ root });
    const logs: string[] = [];
    await runInit({ root, log: (m) => logs.push(m) });
    expect(logs.some((line) => line.startsWith('exists') && line.includes('AGENTS.md'))).toBe(true);
    expect(logs.some((line) => line.includes('already denies edits'))).toBe(true);
  });
});
