// GENERATED BY NAPL from schemas_attribution.napl — edit the prompt, not this file

use schemas_line_range::LineRange;
use serde::Deserialize;

fn default_note() -> String {
    String::new()
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct AttributionEntry {
    #[serde(rename = "promptLines")]
    pub prompt_lines: LineRange,
    pub file: String,
    pub lines: LineRange,
    #[serde(default = "default_note")]
    pub note: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct Attribution {
    pub module: String,
    pub target: String,
    #[serde(default)]
    pub entries: Vec<AttributionEntry>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AttributionError {
    Parse(String),
    EmptyModule,
    EmptyTarget,
    EmptyFile,
}

impl std::fmt::Display for AttributionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AttributionError::Parse(msg) => write!(f, "failed to parse attribution: {msg}"),
            AttributionError::EmptyModule => write!(f, "module must not be empty"),
            AttributionError::EmptyTarget => write!(f, "target must not be empty"),
            AttributionError::EmptyFile => write!(f, "entry file must not be empty"),
        }
    }
}

impl std::error::Error for AttributionError {}

pub fn validate_attribution(value: serde_json::Value) -> Result<Attribution, AttributionError> {
    let attribution: Attribution =
        serde_json::from_value(value).map_err(|e| AttributionError::Parse(e.to_string()))?;

    if attribution.module.is_empty() {
        return Err(AttributionError::EmptyModule);
    }
    if attribution.target.is_empty() {
        return Err(AttributionError::EmptyTarget);
    }
    for entry in &attribution.entries {
        if entry.file.is_empty() {
            return Err(AttributionError::EmptyFile);
        }
    }

    Ok(attribution)
}

pub fn parse_attribution_entries(
    value: serde_json::Value,
) -> Result<Vec<AttributionEntry>, AttributionError> {
    if !value.is_array() {
        return Ok(Vec::new());
    }

    let entries: Vec<AttributionEntry> =
        serde_json::from_value(value).map_err(|e| AttributionError::Parse(e.to_string()))?;

    for entry in &entries {
        if entry.file.is_empty() {
            return Err(AttributionError::EmptyFile);
        }
    }

    Ok(entries)
}

pub fn entries_at_body_line(
    attribution: &Attribution,
    body_line: u32,
) -> Vec<&AttributionEntry> {
    attribution
        .entries
        .iter()
        .filter(|entry| {
            entry.prompt_lines.start <= body_line && body_line <= entry.prompt_lines.end
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn sample_document() -> serde_json::Value {
        json!({
            "module": "m",
            "target": "rust",
            "entries": [
                {"promptLines": [2, 2], "file": "a.rs", "lines": 1, "note": "builds the greeting"},
                {"promptLines": [3, 4], "file": "a.rs", "lines": 2, "note": "trims whitespace"},
                {"promptLines": [3, 3], "file": "a.rs", "lines": 3, "note": "covers trimming"}
            ]
        })
    }

    #[test]
    fn validates_a_well_formed_document() {
        let attribution = validate_attribution(sample_document()).unwrap();
        assert_eq!(attribution.module, "m");
        assert_eq!(attribution.target, "rust");
        assert_eq!(attribution.entries.len(), 3);
    }

    #[test]
    fn entry_field_normalization() {
        let value = json!({
            "module": "m",
            "target": "rust",
            "entries": [
                {"promptLines": [8], "file": "a.rs", "lines": 3}
            ]
        });
        let attribution = validate_attribution(value).unwrap();
        let entry = &attribution.entries[0];
        assert_eq!(entry.prompt_lines, LineRange::new(8, 8));
        assert_eq!(entry.lines, LineRange::new(3, 3));
        assert_eq!(entry.note, "");
    }

    #[test]
    fn entries_default_to_empty_when_absent() {
        let value = json!({"module": "m", "target": "rust"});
        let attribution = validate_attribution(value).unwrap();
        assert!(attribution.entries.is_empty());
    }

    #[test]
    fn rejects_empty_module() {
        let value = json!({"module": "", "target": "rust", "entries": []});
        assert_eq!(validate_attribution(value), Err(AttributionError::EmptyModule));
    }

    #[test]
    fn rejects_empty_target() {
        let value = json!({"module": "m", "target": "", "entries": []});
        assert_eq!(validate_attribution(value), Err(AttributionError::EmptyTarget));
    }

    #[test]
    fn rejects_entry_with_empty_file() {
        let value = json!({
            "module": "m",
            "target": "rust",
            "entries": [
                {"promptLines": 1, "file": "", "lines": 1}
            ]
        });
        assert_eq!(validate_attribution(value), Err(AttributionError::EmptyFile));
    }

    #[test]
    fn rejects_entry_missing_file() {
        let value = json!({
            "module": "m",
            "target": "rust",
            "entries": [
                {"promptLines": 1, "lines": 1}
            ]
        });
        assert!(matches!(
            validate_attribution(value),
            Err(AttributionError::Parse(_))
        ));
    }

    #[test]
    fn rejects_malformed_line_range() {
        let value = json!({
            "module": "m",
            "target": "rust",
            "entries": [
                {"promptLines": 1.5, "file": "a.rs", "lines": 1}
            ]
        });
        assert!(matches!(
            validate_attribution(value),
            Err(AttributionError::Parse(_))
        ));
    }

    #[test]
    fn parse_entries_returns_empty_for_non_array() {
        let value = json!({"not": "an array"});
        assert_eq!(parse_attribution_entries(value).unwrap(), Vec::new());
    }

    #[test]
    fn parse_entries_parses_a_valid_list() {
        let value = json!([
            {"promptLines": [2, 2], "file": "a.rs", "lines": 1}
        ]);
        let entries = parse_attribution_entries(value).unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].file, "a.rs");
    }

    #[test]
    fn parse_entries_rejects_entry_with_empty_file() {
        let value = json!([
            {"promptLines": [2, 2], "file": "", "lines": 1}
        ]);
        assert_eq!(
            parse_attribution_entries(value),
            Err(AttributionError::EmptyFile)
        );
    }

    #[test]
    fn parse_entries_errors_on_malformed_list() {
        let value = json!([
            {"promptLines": "nope", "file": "a.rs", "lines": 1}
        ]);
        assert!(matches!(
            parse_attribution_entries(value),
            Err(AttributionError::Parse(_))
        ));
    }

    #[test]
    fn entries_at_body_line_finds_all_containing_entries() {
        let attribution = validate_attribution(sample_document()).unwrap();

        let at_3 = entries_at_body_line(&attribution, 3);
        assert_eq!(at_3.len(), 2);
        assert_eq!(at_3[0].note, "trims whitespace");
        assert_eq!(at_3[1].note, "covers trimming");

        let at_2 = entries_at_body_line(&attribution, 2);
        assert_eq!(at_2.len(), 1);
        assert_eq!(at_2[0].note, "builds the greeting");

        let at_9 = entries_at_body_line(&attribution, 9);
        assert!(at_9.is_empty());
    }
}
