// GENERATED BY NAPL from extensions.napl — edit the prompt, not this file

/// The canonical prompt (human-authored source) extension.
pub const PROMPT_EXTENSION: &str = ".napl";

/// The canonical machine (compiled) extension.
pub const MACHINE_EXTENSION: &str = ".mapl";

/// The emoji spelling of a compiled file: a dot followed by the robot-face emoji (U+1F916).
pub const MACHINE_ALIAS: &str = ".\u{1F916}";

/// The six curated "single person" emoji prompt aliases, in the order NAPL treats as canonical.
pub const CURATED_PROMPT_ALIASES: [&str; 6] = [
    ".\u{1F9D1}", // person
    ".\u{1F9D3}", // older person
    ".\u{1F464}", // bust in silhouette
    ".\u{1F468}", // man
    ".\u{1F469}", // woman
    ".\u{1F9D2}", // child
];

/// The curated prompt aliases as owned strings, in canonical order.
pub fn default_prompt_aliases() -> Vec<String> {
    CURATED_PROMPT_ALIASES.iter().map(|s| s.to_string()).collect()
}

/// The canonical `.napl` extension followed by either the given aliases or the curated ones.
pub fn prompt_extensions(aliases: Option<&[&str]>) -> Vec<String> {
    let mut result = vec![PROMPT_EXTENSION.to_string()];
    match aliases {
        Some(given) => result.extend(given.iter().map(|s| s.to_string())),
        None => result.extend(default_prompt_aliases()),
    }
    result
}

/// The canonical machine extension followed by the emoji machine alias.
pub fn machine_extensions() -> Vec<&'static str> {
    vec![MACHINE_EXTENSION, MACHINE_ALIAS]
}

/// True when `path` ends with any recognized prompt extension.
pub fn is_prompt_file(path: &str, aliases: Option<&[&str]>) -> bool {
    prompt_extensions(aliases).iter().any(|ext| path.ends_with(ext.as_str()))
}

/// True when `path` ends with any recognized machine extension.
pub fn is_machine_file(path: &str) -> bool {
    machine_extensions().iter().any(|ext| path.ends_with(ext))
}

/// The machine extension whose spelling mirrors `prompt_path`'s prompt extension.
pub fn machine_extension_for_prompt(prompt_path: &str) -> &'static str {
    if prompt_path.ends_with(PROMPT_EXTENSION) {
        MACHINE_EXTENSION
    } else {
        MACHINE_ALIAS
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_constants() {
        assert_eq!(PROMPT_EXTENSION, ".napl");
        assert_eq!(MACHINE_EXTENSION, ".mapl");
        assert_eq!(MACHINE_ALIAS, ".\u{1F916}");
    }

    #[test]
    fn curated_aliases_in_order() {
        let expected = [
            ".\u{1F9D1}",
            ".\u{1F9D3}",
            ".\u{1F464}",
            ".\u{1F468}",
            ".\u{1F469}",
            ".\u{1F9D2}",
        ];
        assert_eq!(CURATED_PROMPT_ALIASES, expected);
        assert_eq!(
            default_prompt_aliases(),
            expected.iter().map(|s| s.to_string()).collect::<Vec<_>>()
        );
    }

    #[test]
    fn prompt_extensions_defaults_to_curated() {
        let exts = prompt_extensions(None);
        assert_eq!(exts[0], ".napl");
        assert_eq!(exts.len(), 7);
        assert_eq!(&exts[1..], default_prompt_aliases().as_slice());
    }

    #[test]
    fn prompt_extensions_with_override() {
        let overrides = [".foo", ".bar"];
        let exts = prompt_extensions(Some(&overrides));
        assert_eq!(exts, vec![".napl".to_string(), ".foo".to_string(), ".bar".to_string()]);
    }

    #[test]
    fn machine_extensions_lists_both() {
        assert_eq!(machine_extensions(), vec![".mapl", ".\u{1F916}"]);
    }

    #[test]
    fn is_prompt_file_matches_canonical() {
        assert!(is_prompt_file("foo.napl", None));
        assert!(!is_prompt_file("foo.mapl", None));
    }

    #[test]
    fn is_prompt_file_matches_curated_aliases() {
        assert!(is_prompt_file("foo.\u{1F9D1}", None));
        assert!(is_prompt_file("foo.\u{1F9D3}", None));
        assert!(is_prompt_file("foo.\u{1F464}", None));
        assert!(is_prompt_file("foo.\u{1F468}", None));
        assert!(is_prompt_file("foo.\u{1F469}", None));
        assert!(is_prompt_file("foo.\u{1F9D2}", None));
    }

    #[test]
    fn is_prompt_file_override_excludes_curated() {
        let overrides = [".xyz"];
        assert!(is_prompt_file("foo.napl", Some(&overrides)));
        assert!(is_prompt_file("foo.xyz", Some(&overrides)));
        assert!(!is_prompt_file("foo.\u{1F9D1}", Some(&overrides)));
    }

    #[test]
    fn composite_emoji_sequence_is_not_a_prompt_file() {
        // man (U+1F468) + ZWJ (U+200D) + laptop (U+1F4BB): a four-scalar composite,
        // not the single-scalar "man" alias, and does not end with any recognized extension.
        let composite = format!("foo.\u{1F468}\u{200D}\u{1F4BB}");
        assert!(!is_prompt_file(&composite, None));
    }

    #[test]
    fn robot_emoji_is_machine_not_prompt() {
        let path = format!("foo.{}", "\u{1F916}");
        assert!(!is_prompt_file(&path, None));
        assert!(is_machine_file(&format!("foo.\u{1F916}")));
    }

    #[test]
    fn is_machine_file_matches_canonical_and_alias() {
        assert!(is_machine_file("foo.mapl"));
        assert!(is_machine_file("foo.\u{1F916}"));
        assert!(!is_machine_file("foo.napl"));
    }

    #[test]
    fn machine_extension_for_prompt_mirrors_canonical() {
        assert_eq!(machine_extension_for_prompt("foo.napl"), ".mapl");
    }

    #[test]
    fn machine_extension_for_prompt_mirrors_emoji() {
        assert_eq!(
            machine_extension_for_prompt("foo.\u{1F9D1}"),
            ".\u{1F916}"
        );
        assert_eq!(
            machine_extension_for_prompt("foo.\u{1F464}"),
            ".\u{1F916}"
        );
    }
}
