// GENERATED BY NAPL from schemas_ordered_map.napl — edit the prompt, not this file

use std::fmt;
use std::marker::PhantomData;

use serde::de::{Deserialize, Deserializer, MapAccess, Visitor};
use serde::ser::{Serialize, SerializeMap, Serializer};

/// A string-keyed map that preserves first-insertion order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OrderedMap<V> {
    entries: Vec<(String, V)>,
}

impl<V> Default for OrderedMap<V> {
    fn default() -> Self {
        OrderedMap { entries: Vec::new() }
    }
}

impl<V> OrderedMap<V> {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn contains_key(&self, key: &str) -> bool {
        self.entries.iter().any(|(k, _)| k == key)
    }

    pub fn get(&self, key: &str) -> Option<&V> {
        self.entries.iter().find(|(k, _)| k == key).map(|(_, v)| v)
    }

    pub fn get_mut(&mut self, key: &str) -> Option<&mut V> {
        self.entries.iter_mut().find(|(k, _)| k == key).map(|(_, v)| v)
    }

    pub fn insert(&mut self, key: String, value: V) {
        if let Some(existing) = self.get_mut(&key) {
            *existing = value;
        } else {
            self.entries.push((key, value));
        }
    }

    pub fn remove(&mut self, key: &str) -> Option<V> {
        let pos = self.entries.iter().position(|(k, _)| k == key)?;
        Some(self.entries.remove(pos).1)
    }

    pub fn iter(&self) -> impl Iterator<Item = (&String, &V)> {
        self.entries.iter().map(|(k, v)| (k, v))
    }

    pub fn keys(&self) -> impl Iterator<Item = &String> {
        self.entries.iter().map(|(k, _)| k)
    }

    pub fn values(&self) -> impl Iterator<Item = &V> {
        self.entries.iter().map(|(_, v)| v)
    }
}

impl<V: Serialize> Serialize for OrderedMap<V> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut map = serializer.serialize_map(Some(self.entries.len()))?;
        for (k, v) in &self.entries {
            map.serialize_entry(k, v)?;
        }
        map.end()
    }
}

impl<'de, V: Deserialize<'de>> Deserialize<'de> for OrderedMap<V> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct OrderedMapVisitor<V> {
            marker: PhantomData<V>,
        }

        impl<'de, V: Deserialize<'de>> Visitor<'de> for OrderedMapVisitor<V> {
            type Value = OrderedMap<V>;

            fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                formatter.write_str("a map")
            }

            fn visit_map<A>(self, mut access: A) -> Result<Self::Value, A::Error>
            where
                A: MapAccess<'de>,
            {
                let mut map = OrderedMap::new();
                while let Some((key, value)) = access.next_entry::<String, V>()? {
                    map.insert(key, value);
                }
                Ok(map)
            }
        }

        deserializer.deserialize_map(OrderedMapVisitor { marker: PhantomData })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_and_new_are_empty() {
        let m: OrderedMap<i32> = OrderedMap::default();
        assert!(m.is_empty());
        assert_eq!(m.len(), 0);

        let m2: OrderedMap<i32> = OrderedMap::new();
        assert_eq!(m, m2);
    }

    #[test]
    fn preserves_first_insertion_order() {
        let mut m = OrderedMap::new();
        m.insert("z".to_string(), 1);
        m.insert("a".to_string(), 2);
        m.insert("m".to_string(), 3);

        let keys: Vec<&String> = m.keys().collect();
        assert_eq!(keys, vec!["z", "a", "m"]);
    }

    #[test]
    fn reinsert_replaces_in_place_without_moving() {
        let mut m = OrderedMap::new();
        m.insert("a".to_string(), 1);
        m.insert("b".to_string(), 2);
        m.insert("a".to_string(), 9);

        assert_eq!(m.get("a"), Some(&9));
        let keys: Vec<&String> = m.keys().collect();
        assert_eq!(keys, vec!["a", "b"]);
    }

    #[test]
    fn remove_closes_gap_and_returns_value() {
        let mut m = OrderedMap::new();
        m.insert("a".to_string(), 1);
        m.insert("b".to_string(), 2);

        let removed = m.remove("a");
        assert_eq!(removed, Some(1));
        assert!(!m.contains_key("a"));
        let keys: Vec<&String> = m.keys().collect();
        assert_eq!(keys, vec!["b"]);
    }

    #[test]
    fn remove_missing_key_returns_none() {
        let mut m: OrderedMap<i32> = OrderedMap::new();
        m.insert("a".to_string(), 1);
        assert_eq!(m.remove("nope"), None);
    }

    #[test]
    fn get_mut_updates_value() {
        let mut m = OrderedMap::new();
        m.insert("a".to_string(), 1);
        if let Some(v) = m.get_mut("a") {
            *v = 42;
        }
        assert_eq!(m.get("a"), Some(&42));
    }

    #[test]
    fn iter_and_values_follow_insertion_order() {
        let mut m = OrderedMap::new();
        m.insert("z".to_string(), 1);
        m.insert("a".to_string(), 2);

        let pairs: Vec<(&String, &i32)> = m.iter().collect();
        assert_eq!(pairs, vec![(&"z".to_string(), &1), (&"a".to_string(), &2)]);

        let values: Vec<&i32> = m.values().collect();
        assert_eq!(values, vec![&1, &2]);
    }

    #[test]
    fn serializes_in_insertion_order() {
        let mut m = OrderedMap::new();
        m.insert("z".to_string(), 1);
        m.insert("a".to_string(), 2);

        let json = serde_json::to_string(&m).unwrap();
        assert_eq!(json, r#"{"z":1,"a":2}"#);
    }

    #[test]
    fn round_trips_through_json_preserving_order() {
        let mut m = OrderedMap::new();
        m.insert("z".to_string(), 1);
        m.insert("a".to_string(), 2);

        let json = serde_json::to_string(&m).unwrap();
        let decoded: OrderedMap<i32> = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded, m);
        let keys: Vec<&String> = decoded.keys().collect();
        assert_eq!(keys, vec!["z", "a"]);
    }
}
