// GENERATED BY NAPL from watch_filter.napl — edit the prompt, not this file

use std::path::Path;

/// Directory names that are always ignored, in this exact order.
pub const IGNORED_DIRS: [&str; 3] = ["node_modules", ".napl", ".git"];

/// `true` when `path`, made relative to `root`, contains a component that
/// exactly matches one of [`IGNORED_DIRS`] at any depth.
pub fn is_ignored(path: &Path, root: &Path) -> bool {
    let relative = path.strip_prefix(root).unwrap_or(path);
    relative
        .components()
        .any(|component| {
            let name = component.as_os_str().to_string_lossy();
            IGNORED_DIRS.iter().any(|ignored| name == *ignored)
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn check(root: &str, path: &str) -> bool {
        is_ignored(&PathBuf::from(path), &PathBuf::from(root))
    }

    #[test]
    fn node_modules_component_ignored() {
        assert!(check("/proj", "/proj/node_modules/dep.js"));
    }

    #[test]
    fn dot_napl_component_ignored() {
        assert!(check("/proj", "/proj/.napl/src/rust/x.rs"));
    }

    #[test]
    fn dot_git_component_ignored() {
        assert!(check("/proj", "/proj/.git/HEAD"));
    }

    #[test]
    fn nested_ignored_dir_at_any_depth() {
        assert!(check("/proj", "/proj/src/a/.napl/b"));
    }

    #[test]
    fn napl_file_extension_is_not_a_directory_match() {
        assert!(!check("/proj", "/proj/examples/greeting.napl"));
    }

    #[test]
    fn plain_source_file_not_ignored() {
        assert!(!check("/proj", "/proj/src/lib.rs"));
    }

    #[test]
    fn path_not_under_root_used_unchanged() {
        assert!(check("/proj", "/other/node_modules/x"));
        assert!(!check("/proj", "/other/src/x"));
    }

    #[test]
    fn ignored_dirs_constant_order() {
        assert_eq!(IGNORED_DIRS, ["node_modules", ".napl", ".git"]);
    }
}
