// GENERATED BY NAPL from reverse.napl — edit the prompt, not this file

use body_lines::PromptBody;
use schemas_attribution::AttributionEntry;
use schemas_line_range::LineRange;

pub const GENERATED_PREFIX: &str = ".napl/src/";
pub const DRIFT_LENS_PREFIX: &str = "DRIFT — edits here are not reflected in any prompt";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedPathInfo {
    pub target: String,
    pub target_rel_path: String,
}

pub fn parse_generated_path(rel_full: &str) -> Option<GeneratedPathInfo> {
    let normalized = rel_full.replace('\\', "/");
    let rest = normalized.strip_prefix(GENERATED_PREFIX)?;
    let slash_idx = rest.find('/')?;
    let target = &rest[..slash_idx];
    let target_rel_path = &rest[slash_idx + 1..];
    if target.is_empty() || target_rel_path.is_empty() {
        return None;
    }
    Some(GeneratedPathInfo {
        target: target.to_string(),
        target_rel_path: target_rel_path.to_string(),
    })
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttributionSource {
    pub module: String,
    pub target: String,
    pub entries: Vec<AttributionEntry>,
    pub prompt_files: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReverseMatch {
    pub module: String,
    pub target: String,
    pub prompt_file: String,
    pub note: String,
    pub prompt_lines: LineRange,
    pub code_lines: LineRange,
}

pub fn reverse_matches(
    sources: &[AttributionSource],
    target: &str,
    target_rel_path: &str,
    code_line: Option<u32>,
) -> Vec<ReverseMatch> {
    let mut matches = Vec::new();
    for source in sources {
        if source.target != target {
            continue;
        }
        for entry in &source.entries {
            if entry.file != target_rel_path {
                continue;
            }
            if let Some(line) = code_line {
                if line < entry.lines.start || line > entry.lines.end {
                    continue;
                }
            }
            for prompt_file in &source.prompt_files {
                matches.push(ReverseMatch {
                    module: source.module.clone(),
                    target: source.target.clone(),
                    prompt_file: prompt_file.clone(),
                    note: entry.note.clone(),
                    prompt_lines: entry.prompt_lines,
                    code_lines: entry.lines,
                });
            }
        }
    }
    matches
}

pub fn prompt_absolute_lines(body_start_line: usize, prompt_lines: LineRange) -> (usize, usize) {
    (
        body_start_line + prompt_lines.start as usize - 1,
        body_start_line + prompt_lines.end as usize - 1,
    )
}

pub fn match_prompt_lines(body: &PromptBody, prompt_lines: LineRange) -> (usize, usize) {
    prompt_absolute_lines(body.body_start_line, prompt_lines)
}

pub fn is_file_drifted(recorded_hash: Option<&str>, actual_hash: &str) -> bool {
    match recorded_hash {
        Some(hash) => hash != actual_hash,
        None => false,
    }
}

pub fn code_lens_title(prompt_basename: &str, absolute_line: usize, note: &str) -> String {
    if note.is_empty() {
        format!("⇠ {prompt_basename}:{absolute_line}")
    } else {
        format!("⇠ {prompt_basename}:{absolute_line} — {note}")
    }
}

pub fn dedupe_matches(matches: &[ReverseMatch]) -> Vec<ReverseMatch> {
    let mut seen = std::collections::HashSet::new();
    let mut result = Vec::new();
    for m in matches {
        let key = (m.prompt_file.clone(), m.prompt_lines.start, m.prompt_lines.end);
        if seen.insert(key) {
            result.push(m.clone());
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use body_lines::prompt_body_lines;

    fn entry(prompt_lines: (u32, u32), file: &str, lines: (u32, u32), note: &str) -> AttributionEntry {
        AttributionEntry {
            prompt_lines: LineRange::new(prompt_lines.0, prompt_lines.1),
            file: file.to_string(),
            lines: LineRange::new(lines.0, lines.1),
            note: note.to_string(),
        }
    }

    #[test]
    fn parses_a_generated_path() {
        let info = parse_generated_path(".napl/src/typescript/src/greeting.ts").unwrap();
        assert_eq!(info.target, "typescript");
        assert_eq!(info.target_rel_path, "src/greeting.ts");
    }

    #[test]
    fn normalizes_backslashes() {
        let info = parse_generated_path(".napl\\src\\typescript\\src\\greeting.ts").unwrap();
        assert_eq!(info.target, "typescript");
        assert_eq!(info.target_rel_path, "src/greeting.ts");
    }

    #[test]
    fn none_without_trailing_path() {
        assert_eq!(parse_generated_path(".napl/src/typescript"), None);
    }

    #[test]
    fn none_without_prefix() {
        assert_eq!(parse_generated_path("examples/greeting.napl"), None);
        assert_eq!(parse_generated_path("src/greeting.ts"), None);
    }

    #[test]
    fn none_with_empty_target() {
        assert_eq!(parse_generated_path(".napl/src//src/greeting.ts"), None);
    }

    #[test]
    fn none_with_empty_rel_path() {
        assert_eq!(parse_generated_path(".napl/src/typescript/"), None);
    }

    #[test]
    fn reverse_matches_filters_by_target_and_file() {
        let sources = vec![
            AttributionSource {
                module: "greeting".to_string(),
                target: "rust".to_string(),
                entries: vec![entry((2, 2), "src/lib.rs", (5, 5), "builds greeting")],
                prompt_files: vec!["greeting.napl".to_string()],
            },
            AttributionSource {
                module: "other".to_string(),
                target: "typescript".to_string(),
                entries: vec![entry((3, 3), "src/lib.rs", (5, 5), "wrong target")],
                prompt_files: vec!["other.napl".to_string()],
            },
        ];
        let matches = reverse_matches(&sources, "rust", "src/lib.rs", None);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].module, "greeting");
        assert_eq!(matches[0].note, "builds greeting");
    }

    #[test]
    fn reverse_matches_none_code_line_ignores_line_filter() {
        let sources = vec![AttributionSource {
            module: "m".to_string(),
            target: "rust".to_string(),
            entries: vec![
                entry((2, 2), "src/lib.rs", (5, 5), "a"),
                entry((3, 3), "src/lib.rs", (10, 12), "b"),
            ],
            prompt_files: vec!["p.napl".to_string()],
        }];
        let matches = reverse_matches(&sources, "rust", "src/lib.rs", None);
        assert_eq!(matches.len(), 2);
    }

    #[test]
    fn reverse_matches_some_code_line_filters_by_containment() {
        let sources = vec![AttributionSource {
            module: "m".to_string(),
            target: "rust".to_string(),
            entries: vec![
                entry((2, 2), "src/lib.rs", (5, 5), "a"),
                entry((3, 3), "src/lib.rs", (10, 12), "b"),
            ],
            prompt_files: vec!["p.napl".to_string()],
        }];
        let matches = reverse_matches(&sources, "rust", "src/lib.rs", Some(11));
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].note, "b");

        let none = reverse_matches(&sources, "rust", "src/lib.rs", Some(6));
        assert!(none.is_empty());
    }

    #[test]
    fn reverse_matches_emits_one_per_prompt_file() {
        let sources = vec![AttributionSource {
            module: "m".to_string(),
            target: "rust".to_string(),
            entries: vec![entry((2, 2), "src/lib.rs", (5, 5), "a")],
            prompt_files: vec!["p1.napl".to_string(), "p2.napl".to_string()],
        }];
        let matches = reverse_matches(&sources, "rust", "src/lib.rs", None);
        assert_eq!(matches.len(), 2);
        assert_eq!(matches[0].prompt_file, "p1.napl");
        assert_eq!(matches[1].prompt_file, "p2.napl");
    }

    #[test]
    fn prompt_absolute_lines_converts_body_relative_to_absolute() {
        assert_eq!(prompt_absolute_lines(12, LineRange::new(7, 7)), (18, 18));
        assert_eq!(prompt_absolute_lines(12, LineRange::new(3, 4)), (14, 15));
        assert_eq!(prompt_absolute_lines(3, LineRange::new(1, 1)), (3, 3));
    }

    #[test]
    fn match_prompt_lines_uses_body_start_line() {
        let body = prompt_body_lines("---\nkey: value\n---\nfirst\nsecond");
        assert_eq!(body.body_start_line, 3);
        assert_eq!(match_prompt_lines(&body, LineRange::new(1, 1)), (3, 3));
        assert_eq!(match_prompt_lines(&body, LineRange::new(2, 2)), (4, 4));
    }

    #[test]
    fn is_file_drifted_detects_hash_mismatch() {
        assert!(is_file_drifted(Some("abc"), "def"));
        assert!(!is_file_drifted(Some("abc"), "abc"));
        assert!(!is_file_drifted(None, "abc"));
    }

    #[test]
    fn code_lens_title_without_note() {
        assert_eq!(code_lens_title("greeting.napl", 18, ""), "⇠ greeting.napl:18");
    }

    #[test]
    fn code_lens_title_with_note() {
        assert_eq!(
            code_lens_title("greeting.napl", 18, "builds the greeting"),
            "⇠ greeting.napl:18 — builds the greeting"
        );
    }

    #[test]
    fn dedupe_matches_keeps_first_occurrence_per_span() {
        let matches = vec![
            ReverseMatch {
                module: "m".to_string(),
                target: "rust".to_string(),
                prompt_file: "p.napl".to_string(),
                note: "first".to_string(),
                prompt_lines: LineRange::new(2, 2),
                code_lines: LineRange::new(5, 5),
            },
            ReverseMatch {
                module: "m".to_string(),
                target: "rust".to_string(),
                prompt_file: "p.napl".to_string(),
                note: "duplicate".to_string(),
                prompt_lines: LineRange::new(2, 2),
                code_lines: LineRange::new(9, 9),
            },
            ReverseMatch {
                module: "m".to_string(),
                target: "rust".to_string(),
                prompt_file: "p.napl".to_string(),
                note: "different span".to_string(),
                prompt_lines: LineRange::new(3, 3),
                code_lines: LineRange::new(6, 6),
            },
        ];
        let deduped = dedupe_matches(&matches);
        assert_eq!(deduped.len(), 2);
        assert_eq!(deduped[0].note, "first");
        assert_eq!(deduped[1].note, "different span");
    }
}
