// GENERATED BY NAPL from schemas_lock.napl — edit the prompt, not this file

use serde::{Deserialize, Serialize};

const ZWJ: char = '\u{200D}';

pub const DEFAULT_MODEL: &str = "claude-sonnet-5";
pub const DEFAULT_BACKEND: Backend = Backend::ClaudeCli;
pub const DEFAULT_AGENT_PRESET: AgentPreset = AgentPreset::Claude;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Backend {
    ClaudeCli,
    AnthropicApi,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AgentPreset {
    Claude,
    Codex,
    Custom,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentConfig {
    pub preset: AgentPreset,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub command: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HlLock {
    pub model: String,
    #[serde(default = "default_backend_value")]
    pub backend: Backend,
    #[serde(rename = "promptAliases", skip_serializing_if = "Option::is_none", default)]
    pub prompt_aliases: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub agent: Option<AgentConfig>,
}

fn default_backend_value() -> Backend {
    DEFAULT_BACKEND
}

pub fn default_agent_config() -> AgentConfig {
    AgentConfig {
        preset: DEFAULT_AGENT_PRESET,
        command: None,
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockError {
    Parse(String),
    EmptyModel,
    InvalidPromptAlias(String),
    CustomAgentMissingCommand,
    NonCustomAgentHasCommand,
}

impl std::fmt::Display for LockError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LockError::Parse(msg) => write!(f, "failed to parse lock document: {msg}"),
            LockError::EmptyModel => write!(f, "model must not be empty"),
            LockError::InvalidPromptAlias(alias) => write!(f, "invalid prompt alias: {alias}"),
            LockError::CustomAgentMissingCommand => {
                write!(f, "custom agent preset requires a non-empty command")
            }
            LockError::NonCustomAgentHasCommand => {
                write!(f, "claude and codex agent presets must not carry a command")
            }
        }
    }
}

impl std::error::Error for LockError {}

pub fn is_valid_prompt_alias(alias: &str) -> bool {
    let Some(rest) = alias.strip_prefix('.') else {
        return false;
    };
    let code_point_count = rest.chars().count();
    if code_point_count < 1 || code_point_count > 2 {
        return false;
    }
    if rest.contains(ZWJ) {
        return false;
    }
    true
}

pub fn validate_agent_config(agent: &AgentConfig) -> Result<(), LockError> {
    match agent.preset {
        AgentPreset::Custom => match &agent.command {
            Some(command) if !command.is_empty() => Ok(()),
            _ => Err(LockError::CustomAgentMissingCommand),
        },
        AgentPreset::Claude | AgentPreset::Codex => {
            if agent.command.is_some() {
                Err(LockError::NonCustomAgentHasCommand)
            } else {
                Ok(())
            }
        }
    }
}

pub fn parse_lock(raw: &str) -> Result<HlLock, LockError> {
    let lock: HlLock = serde_json::from_str(raw).map_err(|e| LockError::Parse(e.to_string()))?;

    if lock.model.is_empty() {
        return Err(LockError::EmptyModel);
    }

    if let Some(aliases) = &lock.prompt_aliases {
        for alias in aliases {
            if !is_valid_prompt_alias(alias) {
                return Err(LockError::InvalidPromptAlias(alias.clone()));
            }
        }
    }

    if let Some(agent) = &lock.agent {
        validate_agent_config(agent)?;
    }

    Ok(lock)
}

pub fn resolve_prompt_aliases(lock: &HlLock) -> Vec<String> {
    lock.prompt_aliases
        .clone()
        .unwrap_or_else(extensions::default_prompt_aliases)
}

pub fn resolve_agent_config(lock: &HlLock) -> AgentConfig {
    lock.agent.clone().unwrap_or_else(default_agent_config)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn backend_kebab_case_round_trip() {
        assert_eq!(
            serde_json::to_string(&Backend::ClaudeCli).unwrap(),
            "\"claude-cli\""
        );
        assert_eq!(
            serde_json::to_string(&Backend::AnthropicApi).unwrap(),
            "\"anthropic-api\""
        );
        assert_eq!(
            serde_json::from_str::<Backend>("\"claude-cli\"").unwrap(),
            Backend::ClaudeCli
        );
        assert_eq!(
            serde_json::from_str::<Backend>("\"anthropic-api\"").unwrap(),
            Backend::AnthropicApi
        );
    }

    #[test]
    fn agent_preset_lowercase_round_trip() {
        assert_eq!(serde_json::to_string(&AgentPreset::Claude).unwrap(), "\"claude\"");
        assert_eq!(serde_json::to_string(&AgentPreset::Codex).unwrap(), "\"codex\"");
        assert_eq!(serde_json::to_string(&AgentPreset::Custom).unwrap(), "\"custom\"");
    }

    #[test]
    fn agent_config_denies_unknown_fields() {
        let raw = r#"{"preset": "claude", "bogus": 1}"#;
        assert!(serde_json::from_str::<AgentConfig>(raw).is_err());
    }

    #[test]
    fn agent_config_command_omitted_when_absent() {
        let config = AgentConfig {
            preset: AgentPreset::Claude,
            command: None,
        };
        let json = serde_json::to_string(&config).unwrap();
        assert_eq!(json, r#"{"preset":"claude"}"#);
    }

    #[test]
    fn hl_lock_defaults_backend_when_absent() {
        let lock: HlLock = serde_json::from_str(r#"{"model": "m"}"#).unwrap();
        assert_eq!(lock.backend, Backend::ClaudeCli);
        assert_eq!(lock.prompt_aliases, None);
        assert_eq!(lock.agent, None);
    }

    #[test]
    fn hl_lock_prompt_aliases_use_camel_case_key() {
        let lock: HlLock =
            serde_json::from_str(r#"{"model": "m", "promptAliases": [".a"]}"#).unwrap();
        assert_eq!(lock.prompt_aliases, Some(vec![".a".to_string()]));

        let json = serde_json::to_string(&lock).unwrap();
        assert!(json.contains("\"promptAliases\":[\".a\"]"));
    }

    #[test]
    fn parse_lock_rejects_corrupt_json() {
        assert!(parse_lock("not json").is_err());
    }

    #[test]
    fn parse_lock_rejects_unknown_backend_spelling() {
        let raw = r#"{"model": "m", "backend": "bogus"}"#;
        assert!(parse_lock(raw).is_err());
    }

    #[test]
    fn parse_lock_rejects_unknown_preset() {
        let raw = r#"{"model": "m", "agent": {"preset": "bogus"}}"#;
        assert!(parse_lock(raw).is_err());
    }

    #[test]
    fn parse_lock_rejects_empty_model() {
        let raw = r#"{"model": ""}"#;
        assert_eq!(parse_lock(raw).unwrap_err(), LockError::EmptyModel);
    }

    #[test]
    fn parse_lock_accepts_valid_document() {
        let raw = r#"{
            "model": "claude-sonnet-5",
            "backend": "anthropic-api",
            "promptAliases": [".a", ".ab"],
            "agent": {"preset": "custom", "command": ["run", "me"]}
        }"#;
        let lock = parse_lock(raw).unwrap();
        assert_eq!(lock.model, "claude-sonnet-5");
        assert_eq!(lock.backend, Backend::AnthropicApi);
        assert_eq!(
            lock.prompt_aliases,
            Some(vec![".a".to_string(), ".ab".to_string()])
        );
        assert_eq!(
            lock.agent,
            Some(AgentConfig {
                preset: AgentPreset::Custom,
                command: Some(vec!["run".to_string(), "me".to_string()])
            })
        );
    }

    #[test]
    fn prompt_alias_must_start_with_dot() {
        assert!(!is_valid_prompt_alias("abc"));
    }

    #[test]
    fn prompt_alias_allows_one_or_two_code_points_after_dot() {
        assert!(is_valid_prompt_alias(".a"));
        assert!(is_valid_prompt_alias(".ab"));
        assert!(is_valid_prompt_alias(".\u{1F600}"));
    }

    #[test]
    fn prompt_alias_rejects_too_many_code_points() {
        assert!(!is_valid_prompt_alias(".abc"));
    }

    #[test]
    fn prompt_alias_rejects_zwj_sequences() {
        // ".👨‍💻" — man + ZWJ + laptop: visually one glyph, three code points after the dot.
        assert!(!is_valid_prompt_alias(".\u{1F468}\u{200D}\u{1F4BB}"));
    }

    #[test]
    fn parse_lock_rejects_invalid_prompt_alias() {
        let raw = r#"{"model": "m", "promptAliases": ["abc"]}"#;
        assert!(matches!(
            parse_lock(raw),
            Err(LockError::InvalidPromptAlias(_))
        ));
    }

    #[test]
    fn custom_preset_requires_non_empty_command() {
        let missing = AgentConfig {
            preset: AgentPreset::Custom,
            command: None,
        };
        assert_eq!(
            validate_agent_config(&missing).unwrap_err(),
            LockError::CustomAgentMissingCommand
        );

        let empty = AgentConfig {
            preset: AgentPreset::Custom,
            command: Some(vec![]),
        };
        assert_eq!(
            validate_agent_config(&empty).unwrap_err(),
            LockError::CustomAgentMissingCommand
        );

        let ok = AgentConfig {
            preset: AgentPreset::Custom,
            command: Some(vec!["run".to_string()]),
        };
        assert!(validate_agent_config(&ok).is_ok());
    }

    #[test]
    fn claude_and_codex_presets_reject_command() {
        let claude_with_command = AgentConfig {
            preset: AgentPreset::Claude,
            command: Some(vec!["run".to_string()]),
        };
        assert_eq!(
            validate_agent_config(&claude_with_command).unwrap_err(),
            LockError::NonCustomAgentHasCommand
        );

        let codex_with_command = AgentConfig {
            preset: AgentPreset::Codex,
            command: Some(vec!["run".to_string()]),
        };
        assert_eq!(
            validate_agent_config(&codex_with_command).unwrap_err(),
            LockError::NonCustomAgentHasCommand
        );

        let claude_ok = AgentConfig {
            preset: AgentPreset::Claude,
            command: None,
        };
        assert!(validate_agent_config(&claude_ok).is_ok());
    }

    #[test]
    fn resolve_prompt_aliases_uses_override_or_curated_default() {
        let with_override = HlLock {
            model: "m".to_string(),
            backend: Backend::ClaudeCli,
            prompt_aliases: Some(vec![".x".to_string()]),
            agent: None,
        };
        assert_eq!(resolve_prompt_aliases(&with_override), vec![".x".to_string()]);

        let without_override = HlLock {
            model: "m".to_string(),
            backend: Backend::ClaudeCli,
            prompt_aliases: None,
            agent: None,
        };
        assert_eq!(
            resolve_prompt_aliases(&without_override),
            extensions::default_prompt_aliases()
        );
    }

    #[test]
    fn resolve_agent_config_uses_override_or_default() {
        let with_override = HlLock {
            model: "m".to_string(),
            backend: Backend::ClaudeCli,
            prompt_aliases: None,
            agent: Some(AgentConfig {
                preset: AgentPreset::Codex,
                command: None,
            }),
        };
        assert_eq!(
            resolve_agent_config(&with_override),
            AgentConfig {
                preset: AgentPreset::Codex,
                command: None
            }
        );

        let without_override = HlLock {
            model: "m".to_string(),
            backend: Backend::ClaudeCli,
            prompt_aliases: None,
            agent: None,
        };
        assert_eq!(resolve_agent_config(&without_override), default_agent_config());
    }
}
