// GENERATED BY NAPL from schemas_journal.napl — edit the prompt, not this file
//! The generation journal: an append-only JSONL history.
//!
//! Serde types and pure readers for the NAPL generation journal — one entry
//! per generation of a module against a target. No I/O: the caller reads the
//! file, this module parses the text.

use blame::BlameSourceEntry;
use serde::{Deserialize, Serialize};

/// One file touched by a generation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct JournalFile {
    pub path: String,
    pub patch: String,
    #[serde(rename = "hashBefore")]
    pub hash_before: Option<String>,
    #[serde(rename = "hashAfter")]
    pub hash_after: String,
}

/// The mode a generation ran in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum JournalMode {
    Full,
    Incremental,
    Reconcile,
    Move,
}

/// One generation of a module against a target.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct JournalEntry {
    pub gen: i64,
    pub timestamp: String,
    pub module: String,
    pub target: String,
    #[serde(rename = "promptHash")]
    pub prompt_hash: String,
    #[serde(rename = "promptDiff")]
    pub prompt_diff: String,
    pub mode: JournalMode,
    #[serde(default)]
    pub files: Vec<JournalFile>,
}

/// The unified diff for a created (`before: None`) or modified file.
pub fn file_patch(before: Option<&str>, after: &str) -> String {
    text_diff::unified_diff(before.unwrap_or(""), after)
}

fn entry_is_valid(entry: &JournalEntry) -> bool {
    entry.gen >= 1
        && !entry.module.is_empty()
        && !entry.target.is_empty()
        && entry.files.iter().all(|f| !f.path.is_empty())
}

/// Parse raw JSONL journal text, returning valid entries and one warning per
/// skipped line.
pub fn read_journal_str(raw: &str) -> (Vec<JournalEntry>, Vec<String>) {
    let mut entries = Vec::new();
    let mut warnings = Vec::new();

    for (idx, raw_line) in raw.split('\n').enumerate() {
        let line_number = idx + 1;
        let line = raw_line.strip_suffix('\r').unwrap_or(raw_line);

        if line.trim().is_empty() {
            continue;
        }

        if serde_json::from_str::<serde_json::Value>(line).is_err() {
            warnings.push(format!(
                "journal: skipping corrupt line {line_number} (invalid JSON)"
            ));
            continue;
        }

        match serde_json::from_str::<JournalEntry>(line) {
            Ok(entry) if entry_is_valid(&entry) => entries.push(entry),
            Ok(_) => warnings.push(format!(
                "journal: skipping corrupt line {line_number} (failed validation)"
            )),
            Err(err) => warnings.push(format!(
                "journal: skipping corrupt line {line_number} ({err})"
            )),
        }
    }

    (entries, warnings)
}

/// One past the highest `gen` among `entries`, or `1` for an empty slice.
pub fn next_gen_number(entries: &[JournalEntry]) -> i64 {
    entries.iter().map(|e| e.gen).max().map_or(1, |g| g + 1)
}

/// The blame-source history of `file_path` across `entries`, in entry order.
pub fn file_history(entries: &[JournalEntry], file_path: &str) -> Vec<BlameSourceEntry> {
    entries
        .iter()
        .filter_map(|entry| {
            entry
                .files
                .iter()
                .find(|f| f.path == file_path)
                .map(|f| BlameSourceEntry {
                    gen: entry.gen,
                    timestamp: entry.timestamp.clone(),
                    module: entry.module.clone(),
                    patch: f.patch.clone(),
                    prompt_diff: entry.prompt_diff.clone(),
                })
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_entry(gen: i64) -> JournalEntry {
        JournalEntry {
            gen,
            timestamp: "2024-01-01T00:00:00Z".to_string(),
            module: "hash".to_string(),
            target: "rust".to_string(),
            prompt_hash: "abc123".to_string(),
            prompt_diff: "--- prompt\n+++ prompt\n".to_string(),
            mode: JournalMode::Full,
            files: vec![JournalFile {
                path: "hash/src/lib.rs".to_string(),
                patch: "--- a\n+++ b\n".to_string(),
                hash_before: None,
                hash_after: "deadbeef".to_string(),
            }],
        }
    }

    #[test]
    fn journal_file_serde_field_names() {
        let file = JournalFile {
            path: "a.rs".to_string(),
            patch: "diff".to_string(),
            hash_before: Some("h1".to_string()),
            hash_after: "h2".to_string(),
        };
        let json = serde_json::to_value(&file).unwrap();
        assert_eq!(json["hashBefore"], "h1");
        assert_eq!(json["hashAfter"], "h2");
        let round_tripped: JournalFile = serde_json::from_value(json).unwrap();
        assert_eq!(round_tripped, file);
    }

    #[test]
    fn journal_mode_serializes_lowercase() {
        assert_eq!(
            serde_json::to_string(&JournalMode::Full).unwrap(),
            "\"full\""
        );
        assert_eq!(
            serde_json::to_string(&JournalMode::Incremental).unwrap(),
            "\"incremental\""
        );
        assert_eq!(
            serde_json::to_string(&JournalMode::Reconcile).unwrap(),
            "\"reconcile\""
        );
        assert_eq!(
            serde_json::to_string(&JournalMode::Move).unwrap(),
            "\"move\""
        );
    }

    #[test]
    fn journal_entry_field_names_and_default_files() {
        let json = serde_json::json!({
            "gen": 1,
            "timestamp": "t",
            "module": "m",
            "target": "rust",
            "promptHash": "ph",
            "promptDiff": "pd",
            "mode": "incremental"
        });
        let entry: JournalEntry = serde_json::from_value(json).unwrap();
        assert_eq!(entry.prompt_hash, "ph");
        assert_eq!(entry.prompt_diff, "pd");
        assert_eq!(entry.mode, JournalMode::Incremental);
        assert!(entry.files.is_empty());
    }

    #[test]
    fn file_patch_treats_none_as_empty_before() {
        let created = file_patch(None, "line one\n");
        let expected = text_diff::unified_diff("", "line one\n");
        assert_eq!(created, expected);

        let modified = file_patch(Some("old\n"), "new\n");
        let expected_modified = text_diff::unified_diff("old\n", "new\n");
        assert_eq!(modified, expected_modified);
    }

    #[test]
    fn read_journal_str_skips_blank_lines_silently() {
        let raw = "\n\n   \n";
        let (entries, warnings) = read_journal_str(raw);
        assert!(entries.is_empty());
        assert!(warnings.is_empty());
    }

    #[test]
    fn read_journal_str_warns_on_invalid_json() {
        let (entries, warnings) = read_journal_str("not json at all");
        assert!(entries.is_empty());
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0], "journal: skipping corrupt line 1 (invalid JSON)");
    }

    #[test]
    fn read_journal_str_warns_on_failed_validation() {
        let bad = serde_json::json!({
            "gen": 0,
            "timestamp": "t",
            "module": "m",
            "target": "rust",
            "promptHash": "ph",
            "promptDiff": "pd",
            "mode": "full",
            "files": []
        })
        .to_string();
        let (entries, warnings) = read_journal_str(&bad);
        assert!(entries.is_empty());
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].starts_with("journal: skipping corrupt line 1 ("));
    }

    #[test]
    fn read_journal_str_rejects_empty_module_target_or_file_path() {
        let make = |module: &str, target: &str, file_path: &str| {
            serde_json::json!({
                "gen": 1,
                "timestamp": "t",
                "module": module,
                "target": target,
                "promptHash": "ph",
                "promptDiff": "pd",
                "mode": "full",
                "files": [{
                    "path": file_path,
                    "patch": "p",
                    "hashBefore": null,
                    "hashAfter": "h"
                }]
            })
            .to_string()
        };

        for raw in [
            make("", "rust", "a.rs"),
            make("m", "", "a.rs"),
            make("m", "rust", ""),
        ] {
            let (entries, warnings) = read_journal_str(&raw);
            assert!(entries.is_empty(), "expected rejection for {raw}");
            assert_eq!(warnings.len(), 1);
        }
    }

    #[test]
    fn read_journal_str_accepts_valid_entries_and_strips_cr() {
        let entry_json = serde_json::to_string(&sample_entry(1)).unwrap();
        let raw = format!("{entry_json}\r\n\r\n");
        let (entries, warnings) = read_journal_str(&raw);
        assert_eq!(entries.len(), 1);
        assert!(warnings.is_empty());
        assert_eq!(entries[0].gen, 1);
    }

    #[test]
    fn read_journal_str_line_numbers_are_one_based_and_mixed() {
        let good = serde_json::to_string(&sample_entry(1)).unwrap();
        let raw = format!("{good}\nnot json\n{good}");
        let (entries, warnings) = read_journal_str(&raw);
        assert_eq!(entries.len(), 2);
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0], "journal: skipping corrupt line 2 (invalid JSON)");
    }

    #[test]
    fn next_gen_number_empty_is_one() {
        assert_eq!(next_gen_number(&[]), 1);
    }

    #[test]
    fn next_gen_number_is_one_past_max() {
        let entries = vec![sample_entry(1), sample_entry(3), sample_entry(2)];
        assert_eq!(next_gen_number(&entries), 4);
    }

    #[test]
    fn file_history_collects_matching_files_in_order() {
        let mut e1 = sample_entry(1);
        e1.files[0].path = "hash/src/lib.rs".to_string();
        e1.files[0].patch = "patch-one".to_string();

        let mut e2 = sample_entry(2);
        e2.files[0].path = "other/src/lib.rs".to_string();

        let mut e3 = sample_entry(3);
        e3.files[0].path = "hash/src/lib.rs".to_string();
        e3.files[0].patch = "patch-three".to_string();

        let entries = vec![e1, e2, e3];
        let history = file_history(&entries, "hash/src/lib.rs");

        assert_eq!(history.len(), 2);
        assert_eq!(history[0].gen, 1);
        assert_eq!(history[0].patch, "patch-one");
        assert_eq!(history[1].gen, 3);
        assert_eq!(history[1].patch, "patch-three");
    }

    #[test]
    fn file_history_empty_when_no_entry_touches_file() {
        let entries = vec![sample_entry(1)];
        assert!(file_history(&entries, "nonexistent.rs").is_empty());
    }
}
