// GENERATED BY NAPL from hash.napl — edit the prompt, not this file

use sha2::{Digest, Sha256};

/// Returns the SHA-256 digest of the UTF-8 bytes of `content`, encoded as a
/// lowercase hexadecimal string.
pub fn content_hash(content: &str) -> String {
    let digest = Sha256::digest(content.as_bytes());
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

#[cfg(test)]
mod tests {
    use super::content_hash;

    #[test]
    fn matches_known_sha256_vector() {
        assert_eq!(
            content_hash("hello"),
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
    }

    #[test]
    fn deterministic_for_same_input() {
        assert_eq!(content_hash("some content"), content_hash("some content"));
    }

    #[test]
    fn distinguishes_different_inputs() {
        assert_ne!(content_hash("some content"), content_hash("other content"));
    }

    #[test]
    fn empty_string_hashes_to_64_char_digest() {
        let digest = content_hash("");
        assert_eq!(digest.len(), 64);
        assert_eq!(digest, content_hash(""));
    }

    #[test]
    fn result_is_64_lowercase_hex_characters() {
        let digest = content_hash("Hello, World! 🦀");
        assert_eq!(digest.len(), 64);
        assert!(digest
            .chars()
            .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c)));
    }
}
