// GENERATED BY NAPL from schemas_ir.napl — edit the prompt, not this file

use serde::Deserialize;
use serde_json::Value;
use std::fmt;

#[derive(Debug, Deserialize, PartialEq, Eq, Clone)]
pub struct IrType {
    pub name: String,
    pub description: String,
}

#[derive(Debug, Deserialize, PartialEq, Eq, Clone)]
pub struct IrFunction {
    pub name: String,
    pub signature: String,
    pub behavior: String,
}

fn empty_object() -> Value {
    Value::Object(serde_json::Map::new())
}

#[derive(Debug, Deserialize, PartialEq, Clone)]
pub struct IrTest {
    pub name: String,
    #[serde(default = "empty_object")]
    pub given: Value,
    #[serde(default = "empty_object")]
    pub expect: Value,
}

#[derive(Debug, Deserialize, PartialEq, Clone)]
pub struct Ir {
    pub module: String,
    #[serde(default)]
    pub deps: Vec<String>,
    #[serde(default)]
    pub types: Vec<IrType>,
    #[serde(default)]
    pub functions: Vec<IrFunction>,
    #[serde(default)]
    pub tests: Vec<IrTest>,
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub enum IrValidationError {
    Deserialize(String),
    EmptyModule,
    InvalidTestValue { test_name: String, field: &'static str },
}

impl fmt::Display for IrValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            IrValidationError::Deserialize(msg) => write!(f, "failed to parse IR: {msg}"),
            IrValidationError::EmptyModule => write!(f, "module must be a non-empty string"),
            IrValidationError::InvalidTestValue { test_name, field } => write!(
                f,
                "test '{test_name}' field '{field}' must be a JSON object or string"
            ),
        }
    }
}

impl std::error::Error for IrValidationError {}

fn is_object_or_string(value: &Value) -> bool {
    matches!(value, Value::Object(_) | Value::String(_))
}

pub fn validate_ir(value: Value) -> Result<Ir, IrValidationError> {
    let ir: Ir =
        serde_json::from_value(value).map_err(|e| IrValidationError::Deserialize(e.to_string()))?;

    if ir.module.is_empty() {
        return Err(IrValidationError::EmptyModule);
    }

    for test in &ir.tests {
        if !is_object_or_string(&test.given) {
            return Err(IrValidationError::InvalidTestValue {
                test_name: test.name.clone(),
                field: "given",
            });
        }
        if !is_object_or_string(&test.expect) {
            return Err(IrValidationError::InvalidTestValue {
                test_name: test.name.clone(),
                field: "expect",
            });
        }
    }

    Ok(ir)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn validates_minimal_function() {
        let value = json!({
            "module": "greeting",
            "functions": [{
                "name": "greet",
                "signature": "greet(name): string",
                "behavior": "returns Hello"
            }]
        });
        let ir = validate_ir(value).expect("should validate");
        assert_eq!(ir.module, "greeting");
        assert!(ir.deps.is_empty());
        assert!(ir.types.is_empty());
        assert!(ir.tests.is_empty());
        assert_eq!(ir.functions.len(), 1);
        assert_eq!(ir.functions[0].name, "greet");
    }

    #[test]
    fn rejects_missing_module() {
        let value = json!({ "functions": [] });
        assert!(validate_ir(value).is_err());
    }

    #[test]
    fn rejects_empty_module() {
        let value = json!({ "module": "", "functions": [] });
        let err = validate_ir(value).unwrap_err();
        assert_eq!(err, IrValidationError::EmptyModule);
    }

    #[test]
    fn rejects_incomplete_function() {
        let value = json!({
            "module": "x",
            "functions": [{ "name": "f" }]
        });
        assert!(validate_ir(value).is_err());
    }

    #[test]
    fn test_expect_string_is_preserved() {
        let value = json!({
            "module": "m",
            "tests": [{ "name": "a", "given": { "x": 1 }, "expect": "ok" }]
        });
        let ir = validate_ir(value).expect("should validate");
        assert_eq!(ir.tests[0].expect, json!("ok"));
    }

    #[test]
    fn test_given_defaults_to_empty_object() {
        let value = json!({
            "module": "m",
            "tests": [{ "name": "a" }]
        });
        let ir = validate_ir(value).expect("should validate");
        assert_eq!(ir.tests[0].given, json!({}));
        assert_eq!(ir.tests[0].expect, json!({}));
    }

    #[test]
    fn rejects_non_object_non_string_given() {
        let value = json!({
            "module": "m",
            "tests": [{ "name": "a", "given": 42, "expect": "ok" }]
        });
        assert!(validate_ir(value).is_err());
    }

    #[test]
    fn rejects_non_object_non_string_expect() {
        let value = json!({
            "module": "m",
            "tests": [{ "name": "a", "given": {}, "expect": [1, 2] }]
        });
        assert!(validate_ir(value).is_err());
    }

    #[test]
    fn rejects_null_given() {
        let value = json!({
            "module": "m",
            "tests": [{ "name": "a", "given": null, "expect": "ok" }]
        });
        assert!(validate_ir(value).is_err());
    }

    #[test]
    fn rejects_boolean_expect() {
        let value = json!({
            "module": "m",
            "tests": [{ "name": "a", "given": {}, "expect": true }]
        });
        assert!(validate_ir(value).is_err());
    }
}
