// GENERATED BY NAPL from blame.napl — edit the prompt, not this file
//! Patch-replay line ancestry ("blame").
//!
//! Computes line-level generation ancestry for a generated file by replaying
//! the sequence of unified-diff patches recorded across generations against a
//! per-line generation vector. Pure: no I/O.

use text_diff::{parse_hunks, to_lines, HunkKind};

/// One recorded generation touching a file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlameSourceEntry {
    pub gen: i64,
    pub timestamp: String,
    pub module: String,
    pub patch: String,
    pub prompt_diff: String,
}

/// One blamed line of the current content.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlameLine {
    pub line: usize,
    pub gen: i64,
    pub timestamp: String,
    pub module: String,
    pub text: String,
}

/// Replay one patch against a per-line generation vector.
pub fn apply_patch_to_blame(blame: &[i64], patch: &str, gen: i64) -> Vec<i64> {
    let hunks = parse_hunks(patch);
    if hunks.is_empty() {
        return blame.to_vec();
    }

    let mut result = Vec::new();
    let mut old_idx: usize = 0;

    for hunk in &hunks {
        let hunk_start = hunk.old_start.saturating_sub(1);
        while old_idx < hunk_start && old_idx < blame.len() {
            result.push(blame[old_idx]);
            old_idx += 1;
        }

        for line in &hunk.lines {
            match line.kind {
                HunkKind::Context => {
                    if old_idx < blame.len() {
                        result.push(blame[old_idx]);
                    } else {
                        result.push(gen);
                    }
                    old_idx += 1;
                }
                HunkKind::Del => {
                    old_idx += 1;
                }
                HunkKind::Ins => {
                    result.push(gen);
                }
            }
        }
    }

    if old_idx < blame.len() {
        result.extend_from_slice(&blame[old_idx..]);
    }

    result
}

/// Compute line-level blame for a file's current content given its history.
pub fn blame_file(history: &[BlameSourceEntry], current_content: &str) -> Vec<BlameLine> {
    let mut sorted: Vec<&BlameSourceEntry> = history.iter().collect();
    sorted.sort_by_key(|entry| entry.gen);

    let mut blame: Vec<i64> = Vec::new();
    for entry in &sorted {
        blame = apply_patch_to_blame(&blame, &entry.patch, entry.gen);
    }

    let fallback_gen = sorted.last().map(|entry| entry.gen).unwrap_or(0);

    let lines = to_lines(current_content);
    lines
        .into_iter()
        .enumerate()
        .map(|(index, text)| {
            let gen = blame.get(index).copied().unwrap_or(fallback_gen);
            let entry = sorted.iter().find(|entry| entry.gen == gen);
            BlameLine {
                line: index + 1,
                gen,
                timestamp: entry.map(|e| e.timestamp.clone()).unwrap_or_default(),
                module: entry.map(|e| e.module.clone()).unwrap_or_default(),
                text,
            }
        })
        .collect()
}

/// The single `BlameLine` for a 1-based line number, or `None` if out of range.
pub fn blame_line_at(
    history: &[BlameSourceEntry],
    current_content: &str,
    line: usize,
) -> Option<BlameLine> {
    blame_file(history, current_content)
        .into_iter()
        .find(|blame_line| blame_line.line == line)
}

/// The most informative single line of a prompt diff.
pub fn first_prompt_diff_line(prompt_diff: &str) -> String {
    let mut in_hunk = false;
    let mut first_added: Option<String> = None;
    let mut first_removed: Option<String> = None;

    for raw_line in prompt_diff.lines() {
        let line = raw_line.strip_suffix('\r').unwrap_or(raw_line);

        if !in_hunk {
            if line.starts_with("@@") {
                in_hunk = true;
            }
            continue;
        }

        if line.starts_with("@@") {
            continue;
        }

        if line.is_empty() {
            continue;
        }

        let marker = line.chars().next().unwrap();
        let text = line[marker.len_utf8()..].trim();
        if text.is_empty() {
            continue;
        }

        if marker == '+' && first_added.is_none() {
            first_added = Some(text.to_string());
        } else if marker == '-' && first_removed.is_none() {
            first_removed = Some(text.to_string());
        }

        if first_added.is_some() {
            break;
        }
    }

    first_added.or(first_removed).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use text_diff::unified_diff;

    fn entry(gen: i64, timestamp: &str, module: &str, patch: &str, prompt_diff: &str) -> BlameSourceEntry {
        BlameSourceEntry {
            gen,
            timestamp: timestamp.to_string(),
            module: module.to_string(),
            patch: patch.to_string(),
            prompt_diff: prompt_diff.to_string(),
        }
    }

    #[test]
    fn apply_patch_to_blame_empty_patch_returns_unchanged() {
        let blame = vec![1, 1, 2];
        let result = apply_patch_to_blame(&blame, "", 3);
        assert_eq!(result, blame);
    }

    #[test]
    fn apply_patch_to_blame_pure_insertion_into_empty() {
        let patch = unified_diff("", "a\nb\n");
        let result = apply_patch_to_blame(&[], &patch, 1);
        assert_eq!(result, vec![1, 1]);
    }

    #[test]
    fn apply_patch_to_blame_context_lines_preserve_gen() {
        // gen1 wrote "a\nb\nc\n"; gen2 changes the middle line.
        let before = "a\nb\nc\n";
        let after = "a\nB\nc\n";
        let patch = unified_diff(before, after);
        let blame1 = vec![1, 1, 1];
        let result = apply_patch_to_blame(&blame1, &patch, 2);
        assert_eq!(result, vec![1, 2, 1]);
    }

    #[test]
    fn apply_patch_to_blame_deletion_removes_entry() {
        let before = "a\nb\nc\n";
        let after = "a\nc\n";
        let patch = unified_diff(before, after);
        let blame1 = vec![1, 1, 1];
        let result = apply_patch_to_blame(&blame1, &patch, 2);
        assert_eq!(result, vec![1, 1]);
    }

    #[test]
    fn apply_patch_to_blame_trailing_untouched_lines_preserved() {
        let before = "a\nb\nc\nd\n";
        let after = "A\nb\nc\nd\n";
        let patch = unified_diff(before, after);
        let blame1 = vec![1, 1, 1, 1];
        let result = apply_patch_to_blame(&blame1, &patch, 2);
        assert_eq!(result, vec![2, 1, 1, 1]);
    }

    #[test]
    fn blame_file_empty_history_uses_fallback_zero() {
        let lines = blame_file(&[], "a\nb\n");
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0].gen, 0);
        assert_eq!(lines[0].timestamp, "");
        assert_eq!(lines[0].module, "");
        assert_eq!(lines[0].text, "a");
        assert_eq!(lines[1].line, 2);
    }

    #[test]
    fn blame_file_single_generation() {
        let patch = unified_diff("", "a\nb\n");
        let history = vec![entry(1, "t1", "mod1", &patch, "")];
        let lines = blame_file(&history, "a\nb\n");
        assert_eq!(lines.len(), 2);
        for line in &lines {
            assert_eq!(line.gen, 1);
            assert_eq!(line.timestamp, "t1");
            assert_eq!(line.module, "mod1");
        }
        assert_eq!(lines[0].text, "a");
        assert_eq!(lines[1].text, "b");
    }

    #[test]
    fn blame_file_multiple_generations_out_of_order_input() {
        let patch1 = unified_diff("", "a\nb\nc\n");
        let after_gen2 = "a\nB\nc\n";
        let patch2 = unified_diff("a\nb\nc\n", after_gen2);

        // Provide history out of ascending order to verify sorting.
        let history = vec![
            entry(2, "t2", "mod2", &patch2, ""),
            entry(1, "t1", "mod1", &patch1, ""),
        ];

        let lines = blame_file(&history, after_gen2);
        assert_eq!(lines.len(), 3);
        assert_eq!(lines[0].gen, 1);
        assert_eq!(lines[0].module, "mod1");
        assert_eq!(lines[1].gen, 2);
        assert_eq!(lines[1].module, "mod2");
        assert_eq!(lines[2].gen, 1);
    }

    #[test]
    fn blame_line_at_returns_correct_line() {
        let patch = unified_diff("", "a\nb\nc\n");
        let history = vec![entry(1, "t1", "mod1", &patch, "")];
        let result = blame_line_at(&history, "a\nb\nc\n", 2);
        assert!(result.is_some());
        let line = result.unwrap();
        assert_eq!(line.line, 2);
        assert_eq!(line.text, "b");
    }

    #[test]
    fn blame_line_at_out_of_range_returns_none() {
        let history: Vec<BlameSourceEntry> = vec![];
        let result = blame_line_at(&history, "a\nb\n", 5);
        assert!(result.is_none());
    }

    #[test]
    fn first_prompt_diff_line_prefers_added_over_removed() {
        let diff = "--- a\n+++ b\n@@ -1,2 +1,2 @@\n-old line\n+new line\n context\n";
        assert_eq!(first_prompt_diff_line(diff), "new line");
    }

    #[test]
    fn first_prompt_diff_line_falls_back_to_removed() {
        let diff = "--- a\n+++ b\n@@ -1,2 +1,1 @@\n-removed line\n context\n";
        assert_eq!(first_prompt_diff_line(diff), "removed line");
    }

    #[test]
    fn first_prompt_diff_line_no_hunk_returns_empty() {
        let diff = "--- a\n+++ b\n";
        assert_eq!(first_prompt_diff_line(diff), "");
    }

    #[test]
    fn first_prompt_diff_line_skips_empty_lines_and_header() {
        let diff = "@@ -1,1 +1,2 @@\n \n+  \n+actual content\n";
        assert_eq!(first_prompt_diff_line(diff), "actual content");
    }

    #[test]
    fn first_prompt_diff_line_no_changes_returns_empty() {
        let diff = "@@ -1,1 +1,1 @@\n context only\n";
        assert_eq!(first_prompt_diff_line(diff), "");
    }

    #[test]
    fn first_prompt_diff_line_strips_trailing_cr() {
        let diff = "@@ -1,1 +1,1 @@\r\n+added\r\n";
        assert_eq!(first_prompt_diff_line(diff), "added");
    }
}
